classdef mask_and_offaxis_setup_and_check_validity
%MASK_AND_OFFAXIS_SETUP_AND_CHECK_VALIDITY Setup-side owner for mask and launch helpers.
% cerupp.m still owns the launch/mask knobs and the later build_masks(...)
% call. These methods settle the mask geometry, convert launch angles into
% transverse-k offsets, and print the setup-only diagnostics before
% propagation starts.
%
% Call the stage methods directly from the driver:
%   mask_and_offaxis_setup_and_check_validity.mask_setup_prepare_build(...)
%   mask_and_offaxis_setup_and_check_validity.mask_setup_check_and_report(...)
%   mask_and_offaxis_setup_and_check_validity.mask_setup_launch_weighted_angle_report(...)

methods(Static)

    function [r_2, r_inner, r_outer, ...
              k0_vac, n_ref_kcut, k0_ref_med, k_min_med, ...
              k_nyx, k_nyy, k_ny, kcut_phys, kcut_ny, kcut, ramp, ...
              kcut_w, ramp_w, ...
              run_warn_state, setup_physics_rewrite_report] = ...
        mask_setup_prepare_build( ...
            simple_masks_flag, x, y, x2_d, y2_d, kx, ky, kperp, ...
            spatial_inner_frac, mask_pad_x, mask_pad_y, mask_pad_w, ...
            kperp_alpha, kperp_nyquist_frac, kperp_ramp_frac, ...
            lambda_fund, lambda_window, omega_window, c, propagation_medium_name, ...
            run_warn_state, setup_physics_rewrite_report)
    % Section 2 mask-setup owner for cerupp.m.
    % Resolve the real-space mask geometry, the transverse-k cutoff, and
    % the spectral support that build_masks(...) later turns into mask
    % arrays.
    % This stage also performs the built-in Sellmeier-range soft audit that
    % feeds run_warn_state before the mask-build plan is returned.
    % Change the mask controls in cerupp.m to steer this helper.

    % First check that the selected built-in medium family is being used
    % in a wavelength range that its current Sellmeier/placeholder path
    % expects.
    lambda_fund_um = lambda_fund / 1e-6;
    if strcmpi(propagation_medium_name, 'AIR')
        % cerupp.m owns the built-in near-800-nm Air placeholder hard stop.
        % This helper only soft-warns on the Ciddor dry-air validity range
        % so there is one fundamental-wavelength hard-stop owner.
        if (lambda_fund_um < 0.23) || (lambda_fund_um > 1.69)
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', ...
                'setup_air_sellmeier_nominal_range_soft', ...
                'CerUPP:DriverSellmeierAirRange', ...
                ['Resolved medium.name=Air normally expects lambda_fund within the Ciddor dry-air ', ...
                 'validity/clamp interval (~0.23-1.69 um); got %.6g um. Continuing with the built-in fit-edge clamp ', ...
                 'inside Sellmeier_Air(lambda).'], ...
                lambda_fund_um);
        end
    else
        if (lambda_fund_um < 0.4) || (lambda_fund_um > 5.0)
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', ...
                'setup_yag_sellmeier_nominal_range_soft', ...
                'CerUPP:DriverSellmeierYAGRange', ...
                ['lambda_fund=%.6g um is outside YAG Sellmeier nominal validity (~0.4-5.0 um). ', ...
                 'Continuing with the built-in fit-edge clamp inside Sellmeier_YAG(lambda).'], ...
                lambda_fund_um);
        end
    end

    % Build the fundamental and sampled medium wavenumbers used for
    % physical transverse-k review diagnostics. This helper assumes
    % lambda_window/omega_window already describe the nonzero-support band
    % that will be used for the frequency-dependent k-cut plan.
    k0_vac = 2*pi / lambda_fund;
    if strcmpi(propagation_medium_name, 'AIR')
        n_ref_kcut = Sellmeier_Air(lambda_fund);
        n_band_kcut = Sellmeier_Air(lambda_window);
        kcut_sellmeier_name = 'Sellmeier_Air';
    else
        n_ref_kcut = Sellmeier_YAG(lambda_fund);
        n_band_kcut = Sellmeier_YAG(lambda_window);
        kcut_sellmeier_name = 'Sellmeier_YAG';
    end
    if ~(isscalar(n_ref_kcut) && isfinite(n_ref_kcut) && isreal(n_ref_kcut) && (n_ref_kcut > 0))
        error('CerUPP:InvalidSellmeierForKcut', ...
            ['%s(lambda_fund) must be finite, real, and > 0 for k-cut setup. ', ...
             'Got %s at lambda_fund=%g m.'], ...
            kcut_sellmeier_name, mat2str(n_ref_kcut), lambda_fund);
    end

    k0_ref_med = n_ref_kcut * k0_vac;
    k_band_med = (n_band_kcut(:) .* omega_window(:)) / c;
    if isempty(k_band_med)
        error('CerUPP:Mask:EmptyOmegaPassbandForKcut', ...
            ['mask_setup_prepare_build requires a nonempty pretrimmed omega band ', ...
             'when it resolves the frequency-dependent transverse-k cutoff.']);
    end
    if any(~isfinite(k_band_med)) || any(~isreal(k_band_med)) || ...
            any(k_band_med <= 0)
        error('CerUPP:InvalidBandWavenumberForKcut', ...
            ['Computed band wavenumber n(omega)*omega/c must be finite, real, and > 0 on ', ...
             'the omega slices used to build the frequency-dependent k-cut. ', ...
             'Check Sellmeier model and omega_window.']);
    end
    k_min_med = min(k_band_med);

    % The runtime transverse-k passband is the rectangular sampled-grid
    % Nyquist gate. kcut_phys, kcut_w, and ramp_w are physical-review
    % diagnostics based on the medium wavenumber and kperp_alpha; they are
    % not applied filters.
    k_nyx = max(abs(kx));
    k_nyy = max(abs(ky));
    k_rect_gate_x = kperp_nyquist_frac * k_nyx;
    k_rect_gate_y = kperp_nyquist_frac * k_nyy;
    k_ny = min(k_nyx, k_nyy);
    kcut_phys = kperp_alpha * k_min_med;
    kcut_ny = kperp_nyquist_frac * k_ny;
    kcut_w = kperp_alpha * k_band_med;
    kcut = min(kcut_w);
    if ~(isfinite(kcut) && isreal(kcut) && (kcut > 0))
        error('CerUPP:InvalidKCutoff', ...
            ['kcut must be finite, real, and > 0. Got kcut=%s, ', ...
             'kcut_phys=%s, diagnostic_kcut_ny=%s.'], ...
            mat2str(kcut), mat2str(kcut_phys), mat2str(kcut_ny));
    end

    if any(~isfinite(kcut_w)) || any(~isreal(kcut_w)) || any(kcut_w <= 0)
        error('CerUPP:InvalidKCutoffVector', ...
            ['Every sampled omega slice must produce a finite real transverse-k cutoff > 0. ', ...
             'Check kperp_alpha, Sellmeier data, and omega_window.']);
    end

    % Check whether the retained transverse-k region reaches the exact
    % forward-wave cone edge k_perp = n(omega)*omega/c. The propagation
    % operator there is still the forward-envelope k_perp-series
    % approximation, so this is a model-accuracy caution, not a setup
    % refusal.
    cone_edge_warn_tol = 1e-6;
    [kx_2, ky_2] = ndgrid(kx, ky);
    rect_nyquist_gate = ...
        (abs(kx_2) < k_rect_gate_x) & ...
        (abs(ky_2) < k_rect_gate_y);
    retained_kperp_max_w = zeros(size(kcut_w));
    cone_edge_ratio_w = zeros(size(kcut_w));
    for iw = 1:numel(kcut_w)
        retained_mask_i = rect_nyquist_gate;
        if any(retained_mask_i(:))
            retained_kperp_max_w(iw) = max(double(kperp(retained_mask_i)));
        end
        cone_edge_ratio_w(iw) = retained_kperp_max_w(iw) / ...
            max(double(k_band_med(iw)), eps);
    end
    cone_edge_warn_mask = cone_edge_ratio_w >= (1 - cone_edge_warn_tol);
    if any(cone_edge_warn_mask)
        [cone_edge_ratio_max, idx_warn] = max(cone_edge_ratio_w);
        lambda_warn_nm = double(lambda_window(idx_warn)) * 1e9;
        retained_k_warn = retained_kperp_max_w(idx_warn);
        k_medium_warn = double(k_band_med(idx_warn));
        if cone_edge_ratio_max > (1 + cone_edge_warn_tol)
            cone_phrase = 'reaches or crosses';
        else
            cone_phrase = 'reaches the edge of';
        end
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'setup_kperp_cone_edge_fee_review', ...
            'CerUPP:Mask:KPerpConeEdgeFEEReview', ...
            ['The runtime rectangular transverse-k support %s the exact forward-wave cone on at least one retained ', ...
             'omega slice (worst ratio k_perp,max/k = %.6f at lambda ~= %.3f nm, kept k_perp,max = %.6g ', ...
             '1/m, medium k = %.6g 1/m, kperp_alpha review value = %.6g). In basic terms, the grid admits nearly ', ...
             'side-running or beyond-cone Fourier content that the built-in forward-envelope / k_perp-expanded ', ...
             'operator is not meant to propagate accurately all the way to that exact cone edge. Continuing ', ...
             'because this is a soft warning only; reduce the sampled transverse window, increase the transverse ', ...
             'resolution, or inspect the generated high-k energy before interpreting the result physically.'], ...
            cone_phrase, cone_edge_ratio_max, lambda_warn_nm, ...
            retained_k_warn, k_medium_warn, kperp_alpha);
    end

    ramp_w = kperp_ramp_frac * kcut_w;
    ramp = kperp_ramp_frac * kcut;
    if any(~isfinite(ramp_w)) || any(~isreal(ramp_w)) || any(ramp_w < 0)
        error('CerUPP:InvalidKRampWidth', ...
            ['Computed ramp width must be finite, real, and >= 0 on every sampled omega ', ...
             'slice. Check kperp_ramp_frac.']);
    end
    if any(ramp_w > kcut_w)
        error('CerUPP:InvalidKRampWidth', ...
            ['Computed ramp width must satisfy ramp <= kcut on every sampled omega slice. ', ...
             'Choose kperp_ramp_frac <= 1 to keep the taper inside the passband.']);
    end

    % Return the radial geometry later used by the real-space mask.
    r_2 = sqrt(x2_d.^2 + y2_d.^2);
    r_box = min(max(abs(x)), max(abs(y)));
    r_inner = spatial_inner_frac * r_box;
    r_outer = r_box;
    lambda_vec = lambda_window(:);
    if isempty(lambda_vec)
        error('CerUPP:DriverEmptyLambdaWindow', ...
            'lambda_window must be nonempty.');
    end
    if any(~isfinite(lambda_vec)) || any(~isreal(lambda_vec)) || any(lambda_vec <= 0)
        error('CerUPP:DriverInvalidLambdaWindow', ...
            'lambda_window must contain only finite positive real values.');
    end

    % The simple hard-radial path still needs at least one interior sampled
    % cell in both transverse directions before build_masks(...) can form
    % the radial real-space support.
    surviving_x_cells = max(numel(x) - 2*mask_pad_x, 0);
    surviving_y_cells = max(numel(y) - 2*mask_pad_y, 0);
    if simple_masks_flag && ((2*mask_pad_x) >= numel(x) || (2*mask_pad_y) >= numel(y))
        error('CerUPP:Mask:EmptySimpleMaskInterior', ...
            ['Simple-mask setup leaves no surviving interior cells after the requested ', ...
             'real-space edge padding (mask_pad_x=%d, mask_pad_y=%d, num_x_pts=%d, ', ...
             'num_y_pts=%d, surviving_x_cells=%d, surviving_y_cells=%d).'], ...
            mask_pad_x, mask_pad_y, numel(x), numel(y), ...
            surviving_x_cells, surviving_y_cells);
    end
    end


    function [dkx_offset, dky_offset, dkx_offset_beam2, dky_offset_beam2, ...
              n_ratio_diag_xy, run_warn_state] = ...
        mask_setup_check_and_report( ...
            x, y, kx, ky, delta_x, delta_y, ...
            x_offset, y_offset, x_offset_beam2, y_offset_beam2, ...
            i_laser_peak, i_laser_peak_beam2, ...
            dkx_offset_angle, dky_offset_angle, dkx_offset_angle_beam2, dky_offset_angle_beam2, ...
            n_ref_diag_fund, n_omega_fund_xy, ...
            kcut, ramp, k_ny, kperp_nyquist_frac, k0_vac, n_ref_kcut, k_min_med, ...
            mask_f, mask_f_w, mask_xy, mask_f_xy, r_2, r_inner, r_outer, ...
            kperp, k_nyx, k_nyy, kcut_phys, kcut_ny, ...
            omega_window, omega_ref, omega_fund, lambda_fund, ...
            lambda_grid_min_nm, lambda_grid_max_nm, lambda_edge_min_nm, lambda_edge_max_nm, ...
            delta_omega, delta_f, omega_n_impl, delta_omega_p, oversamp_pulse, cadence_cfg, ...
            dz_setup_diagnostic_msg, mask_2_d, core_radius, simple_masks_flag, ...
            mask_pad_x, mask_pad_y, mask_pad_w, c, run_warn_state)
    % Section 2D off-axis launch setup and setup-only diagnostics owner for cerupp.m.
    % Convert the launch-center and projected-tilt knobs into the
    % beam-1 / beam-2 transverse spectral offsets, then print the setup-only
    % mask/passband diagnostics and build n_ratio_diag_xy.
    % This stage only needs the local refractive-index sample at each
    % requested launch center when projected-angle -> k conversion is
    % active, so off-grid launch centers only hard-stop on that path.
    % Change the launch and mask controls in cerupp.m to steer this helper.

    % Find the nearest sampled launch centers, but refuse to use those
    % samples only when an off-grid beam also needs projected-angle ->
    % transverse-k conversion.
    [~, ix_launch1] = min(abs(x - x_offset));
    [~, iy_launch1] = min(abs(y - y_offset));
    [~, ix_launch_beam2] = min(abs(x - x_offset_beam2));
    [~, iy_launch_beam2] = min(abs(y - y_offset_beam2));
    x_min = min(x);
    x_max = max(x);
    y_min = min(y);
    y_max = max(y);
    launch1_outside_grid = ~isfinite(x_offset) || ~isfinite(y_offset) || ...
        (x_offset < x_min) || (x_offset > x_max) || ...
        (y_offset < y_min) || (y_offset > y_max);
    launch_beam2_outside_grid = ~isfinite(x_offset_beam2) || ~isfinite(y_offset_beam2) || ...
        (x_offset_beam2 < x_min) || (x_offset_beam2 > x_max) || ...
        (y_offset_beam2 < y_min) || (y_offset_beam2 > y_max);
    launch1_active = isfinite(i_laser_peak) && (i_laser_peak > 0);
    launch_beam2_active = isfinite(i_laser_peak_beam2) && (i_laser_peak_beam2 > 0);
    launch1_needs_tilt_conversion = launch1_active && ...
        ((dkx_offset_angle ~= 0) || (dky_offset_angle ~= 0));
    launch_beam2_needs_tilt_conversion = launch_beam2_active && ...
        ((dkx_offset_angle_beam2 ~= 0) || (dky_offset_angle_beam2 ~= 0));
    if launch1_needs_tilt_conversion && launch1_outside_grid
        error('CerUPP:LaunchCenterOutsideGrid', ...
            ['Beam 1 launch center (x_offset=%.3e m, y_offset=%.3e m) lies outside/invalid for grid bounds ', ...
             'x=[%.3e, %.3e] m, y=[%.3e, %.3e] m. Refusing to fallback to the nearest-grid refractive index ', ...
             'sample for projected-angle->k tilt conversion.'], ...
            x_offset, y_offset, x_min, x_max, y_min, y_max);
    end
    if launch_beam2_needs_tilt_conversion && launch_beam2_outside_grid
        error('CerUPP:LaunchCenterOutsideGrid', ...
            ['Beam 2 launch center (x_offset_beam2=%.3e m, y_offset_beam2=%.3e m) lies outside/invalid for grid bounds ', ...
             'x=[%.3e, %.3e] m, y=[%.3e, %.3e] m. Refusing to fallback to the nearest-grid refractive index ', ...
             'sample for projected-angle->k tilt conversion.'], ...
            x_offset_beam2, y_offset_beam2, x_min, x_max, y_min, y_max);
    end

    % Build the refractive-index ratio map used by setup diagnostics. The
    % exact projected-angle -> transverse-k conversion below only samples
    % the local launch-center index on the beams that actually request it.
    n_ref_diag = real(n_ref_diag_fund);
    n_ratio_diag_xy = real(n_omega_fund_xy) ./ cast(n_ref_diag, 'like', real(n_omega_fund_xy(1)));
    propagation_support.assert_valid_diag_weight_map_local( ...
        n_ratio_diag_xy, 'n_ratio_diag_xy', 'initial diagnostic weight-map build');

    k0_vac = 2*pi / lambda_fund;
    k_rect_gate_x = kperp_nyquist_frac * k_nyx;
    k_rect_gate_y = kperp_nyquist_frac * k_nyy;
    pre_guard_launch_taper_start = max(kcut - ramp, 0);
    rep_flat_thresh = 0.99;
    [mask_f_xy_current, omega_diag_idx, active_kcut, active_kflat] = ...
        mask_and_offaxis_setup_and_check_validity.resolve_final_mask_support_local( ...
            mask_f, mask_f_w, kperp, omega_window, omega_fund, ...
            rep_flat_thresh);
    launch_kcut_warn = double(kcut);
    if isfinite(active_kcut) && (active_kcut > 0)
        launch_kcut_warn = active_kcut;
    end
    launch_taper_start = pre_guard_launch_taper_start;
    if ~simple_masks_flag
        if isfinite(active_kflat)
            launch_taper_start = max(min(active_kflat, launch_kcut_warn), 0);
        else
            launch_taper_start = 0;
        end
    end
    paraxial_review_angle_deg = 3.0;
    forward_launch_angle_tol = 1e-12;

    % Convert each beam's projected x/y angles into a forward-propagating
    % transverse spectral offset, then check the applied rectangular gate
    % plus the worst-case radial support summaries.
    if launch1_needs_tilt_conversion
        n_launch1 = n_omega_fund_xy(ix_launch1, iy_launch1);
        k_launch1 = k0_vac * double(n_launch1);
        alpha_x1 = double(dkx_offset_angle);
        alpha_y1 = double(dky_offset_angle);
        if (abs(alpha_x1) >= ((pi / 2) - forward_launch_angle_tol)) || ...
                (abs(alpha_y1) >= ((pi / 2) - forward_launch_angle_tol))
            error('CerUPP:InvalidLaunchProjectedAngle', ...
                ['Beam 1 projected launch angles must stay inside the forward-pointing range ', ...
                 '|alpha_x|, |alpha_y| < pi/2. Got dkx_offset_angle=%.12g rad and ', ...
                 'dky_offset_angle=%.12g rad.'], ...
                alpha_x1, alpha_y1);
        end
        tan_ax1 = tan(alpha_x1);
        tan_ay1 = tan(alpha_y1);
        if ~isfinite(tan_ax1) || ~isfinite(tan_ay1)
            error('CerUPP:InvalidLaunchProjectedAngle', ...
                ['Beam 1 projected launch angles must keep tan(alpha_x) and tan(alpha_y) finite ', ...
                 'so the exact forward-launch conversion remains well-defined. ', ...
                 'Got dkx_offset_angle=%.12g rad and dky_offset_angle=%.12g rad.'], ...
                alpha_x1, alpha_y1);
        end
        kz_launch1 = k_launch1 / sqrt(1 + tan_ax1^2 + tan_ay1^2);
        if ~isfinite(kz_launch1) || (kz_launch1 <= 0)
            error('CerUPP:InvalidLaunchProjectedAngle', ...
                ['Beam 1 projected launch angles must define a forward (+z) launch. ', ...
                 'Exact conversion produced kz=%.12g 1/m from k=%.12g 1/m, ', ...
                 'tan(alpha_x)=%.12g, tan(alpha_y)=%.12g.'], ...
                kz_launch1, k_launch1, tan_ax1, tan_ay1);
        end
        dkx_offset = kz_launch1 * tan_ax1;
        dky_offset = kz_launch1 * tan_ay1;
        kperp_launch1 = hypot(dkx_offset, dky_offset);
        if ~isfinite(kperp_launch1) || ~isreal(kperp_launch1)
            error('CerUPP:InvalidLaunchTiltSupport', ...
                'Beam 1 requested tilt produced a non-finite transverse launch wavenumber.');
        end
        if (abs(dkx_offset) >= k_rect_gate_x) || (abs(dky_offset) >= k_rect_gate_y)
            error('CerUPP:LaunchTiltExceedsNyquist', ...
                ['Beam 1 requested transverse launch wavenumber components (dkx, dky)=(%.12g, %.12g) 1/m ', ...
                 'must stay strictly inside the applied rectangular transverse-k gate ', ...
                 '(|kx|, |ky|) < (%.12g, %.12g) 1/m built from kperp_nyquist_frac=%.12g ', ...
                 'and the sampled FFT-grid Nyquist limits. Refusing a launch that the ', ...
                 'step-1 mask would clip immediately.'], ...
                dkx_offset, dky_offset, double(k_rect_gate_x), double(k_rect_gate_y), ...
                double(kperp_nyquist_frac));
        end
        if kperp_launch1 >= kcut
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', ...
                'beam1_launch_tilt_exceeds_worstcase_cutoff', ...
                'CerUPP:LaunchTiltExceedsPassband', ...
                ['Beam 1 requested transverse launch wavenumber k_perp=%.12g 1/m equals/exceeds the ', ...
                 'diagnostic physical review cutoff kcut=%.12g 1/m. The runtime mask does not remove ', ...
                 'this launch for that reason; only the rectangular transverse Nyquist gate and frequency-edge ', ...
                 'guard are enforced. Review whether the launch remains within the intended forward-envelope regime.'], ...
                kperp_launch1, kcut);
        end
        launch_angle1_deg = atan2(kperp_launch1, kz_launch1) * 180 / pi;
        if launch_angle1_deg > paraxial_review_angle_deg
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', ...
                'beam1_large_launch_tilt_paraxial_review', ...
                'CerUPP:LargeLaunchTiltParaxialReview', ...
                ['Beam 1 combined projected launch angle %.6g deg exceeds the configured ', ...
                 'paraxial_review_angle_deg review threshold of %.6g deg. Review whether this ', ...
                 'off-axis launch stays within the forward-envelope assumptions of the code.'], ...
                launch_angle1_deg, paraxial_review_angle_deg);
        end
    else
        dkx_offset = 0.0;
        dky_offset = 0.0;
        if launch1_active && launch1_outside_grid
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', ...
                'beam1_zero_tilt_launch_center_outside_grid', ...
                'CerUPP:LaunchCenterOutsideGridZeroTilt', ...
                ['Beam 1 launch center (x_offset=%.3e m, y_offset=%.3e m) lies outside the sampled ', ...
                 'x/y box, but the projected launch angles are zero so setup skips the local ', ...
                 'refractive-index tilt conversion and the IC builder evaluates the usual ', ...
                 'zero-tilt field on the sampled x/y grid, so any portion outside that box ', ...
                 'is absent from the launched field.'], ...
                x_offset, y_offset);
        end
    end

    % Repeat the same exact projected-angle conversion and support checks
    % for the optional second beam.
    if launch_beam2_needs_tilt_conversion
        n_launch_beam2 = n_omega_fund_xy(ix_launch_beam2, iy_launch_beam2);
        k_launch_beam2 = k0_vac * double(n_launch_beam2);
        alpha_x_beam2 = double(dkx_offset_angle_beam2);
        alpha_y_beam2 = double(dky_offset_angle_beam2);
        if (abs(alpha_x_beam2) >= ((pi / 2) - forward_launch_angle_tol)) || ...
                (abs(alpha_y_beam2) >= ((pi / 2) - forward_launch_angle_tol))
            error('CerUPP:InvalidLaunchProjectedAngle', ...
                ['Beam 2 projected launch angles must stay inside the forward-pointing range ', ...
                 '|alpha_x|, |alpha_y| < pi/2. Got dkx_offset_angle_beam2=%.12g rad and ', ...
                 'dky_offset_angle_beam2=%.12g rad.'], ...
                alpha_x_beam2, alpha_y_beam2);
        end
        tan_ax_beam2 = tan(alpha_x_beam2);
        tan_ay_beam2 = tan(alpha_y_beam2);
        if ~isfinite(tan_ax_beam2) || ~isfinite(tan_ay_beam2)
            error('CerUPP:InvalidLaunchProjectedAngle', ...
                ['Beam 2 projected launch angles must keep tan(alpha_x) and tan(alpha_y) finite ', ...
                 'so the exact forward-launch conversion remains well-defined. ', ...
                 'Got dkx_offset_angle_beam2=%.12g rad and dky_offset_angle_beam2=%.12g rad.'], ...
                alpha_x_beam2, alpha_y_beam2);
        end
        kz_launch_beam2 = k_launch_beam2 / sqrt(1 + tan_ax_beam2^2 + tan_ay_beam2^2);
        if ~isfinite(kz_launch_beam2) || (kz_launch_beam2 <= 0)
            error('CerUPP:InvalidLaunchProjectedAngle', ...
                ['Beam 2 projected launch angles must define a forward (+z) launch. ', ...
                 'Exact conversion produced kz=%.12g 1/m from k=%.12g 1/m, ', ...
                 'tan(alpha_x)=%.12g, tan(alpha_y)=%.12g.'], ...
                kz_launch_beam2, k_launch_beam2, tan_ax_beam2, tan_ay_beam2);
        end
        dkx_offset_beam2 = kz_launch_beam2 * tan_ax_beam2;
        dky_offset_beam2 = kz_launch_beam2 * tan_ay_beam2;
        kperp_launch_beam2 = hypot(dkx_offset_beam2, dky_offset_beam2);
        if ~isfinite(kperp_launch_beam2) || ~isreal(kperp_launch_beam2)
            error('CerUPP:InvalidLaunchTiltSupport', ...
                'Beam 2 requested tilt produced a non-finite transverse launch wavenumber.');
        end
        if (abs(dkx_offset_beam2) >= k_rect_gate_x) || (abs(dky_offset_beam2) >= k_rect_gate_y)
            error('CerUPP:LaunchTiltExceedsNyquist', ...
                ['Beam 2 requested transverse launch wavenumber components (dkx, dky)=(%.12g, %.12g) 1/m ', ...
                 'must stay strictly inside the applied rectangular transverse-k gate ', ...
                 '(|kx|, |ky|) < (%.12g, %.12g) 1/m built from kperp_nyquist_frac=%.12g ', ...
                 'and the sampled FFT-grid Nyquist limits. Refusing a launch that the ', ...
                 'step-1 mask would clip immediately.'], ...
                dkx_offset_beam2, dky_offset_beam2, double(k_rect_gate_x), ...
                double(k_rect_gate_y), double(kperp_nyquist_frac));
        end
        if kperp_launch_beam2 >= kcut
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', ...
                'beam2_launch_tilt_exceeds_worstcase_cutoff', ...
                'CerUPP:LaunchTiltExceedsPassband', ...
                ['Beam 2 requested transverse launch wavenumber k_perp=%.12g 1/m equals/exceeds the ', ...
                 'diagnostic physical review cutoff kcut=%.12g 1/m. The runtime mask does not remove ', ...
                 'this launch for that reason; only the rectangular transverse Nyquist gate and frequency-edge ', ...
                 'guard are enforced. Review whether the launch remains within the intended forward-envelope regime.'], ...
                kperp_launch_beam2, kcut);
        end
        launch_angle_beam2_deg = atan2(kperp_launch_beam2, kz_launch_beam2) * 180 / pi;
        if launch_angle_beam2_deg > paraxial_review_angle_deg
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', ...
                'beam2_large_launch_tilt_paraxial_review', ...
                'CerUPP:LargeLaunchTiltParaxialReview', ...
                ['Beam 2 combined projected launch angle %.6g deg exceeds the configured ', ...
                 'paraxial_review_angle_deg review threshold of %.6g deg. Review whether this ', ...
                 'off-axis launch stays within the forward-envelope assumptions of the code.'], ...
                launch_angle_beam2_deg, paraxial_review_angle_deg);
        end
    else
        dkx_offset_beam2 = 0.0;
        dky_offset_beam2 = 0.0;
        if launch_beam2_active && launch_beam2_outside_grid
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', ...
                'beam2_zero_tilt_launch_center_outside_grid', ...
                'CerUPP:LaunchCenterOutsideGridZeroTilt', ...
                ['Beam 2 launch center (x_offset_beam2=%.3e m, y_offset_beam2=%.3e m) lies outside ', ...
                 'the sampled x/y box, but the projected launch angles are zero so setup skips ', ...
                 'the local refractive-index tilt conversion and the IC builder evaluates the ', ...
                 'usual zero-tilt field on the sampled x/y grid, so any portion outside that ', ...
                 'box is absent from the launched field.'], ...
                x_offset_beam2, y_offset_beam2);
        end
    end

    % With the launch centers and tilt offsets settled, print the
    % setup-time summary of the sampled spectrum, the already-frozen
    % cache/cadence preview, and the current mask plan.
    fprintf('\n================== SETUP VALIDATION & DIAGNOSTICS (PRE-PROPAGATION) ==================\n');
    fprintf('%s\n', dz_setup_diagnostic_msg);
    fprintf('Sampled wavelength window from omega_window: [%.2f, %.2f] nm\n', ...
        lambda_grid_min_nm, lambda_grid_max_nm);
    fprintf('Expected wavelength edges from Nyquist bounds: [%.2f, %.2f] nm\n', ...
        lambda_edge_min_nm, lambda_edge_max_nm);
    fprintf('Frequency spacing: %.3e rad/s (%.3e Hz)\n', delta_omega, delta_f);
    fprintf(['Time-grid Nyquist omega_N = %.6e rad/s; ', ...
             'Gaussian pulse Delta_omega_FWHM ~= %.6e rad/s; ', ...
             'bandwidth oversampling omega_N/Delta_omega_FWHM ~= %.1f\n'], ...
        omega_n_impl, delta_omega_p, oversamp_pulse);
    driver_setup_support.print_runtime_cadence_summary_local(cadence_cfg);

    fprintf('================== MASK DIAGNOSTICS ==================\n');
    fprintf('Diagnostic printout for mask settings (real-space mask, transverse-k mask, spectral guard band, and core mask_2_d).\n');
    fprintf('Units: x,y printed in um; k in 1/m; omega in rad/s; lambda in nm.\n\n');
    rep_slice_has_passband = ~isempty(mask_f_xy_current) && ...
        any(mask_f_xy_current(:) > 0);
    if ~rep_slice_has_passband
        lambda_diag_nm = (2*pi*c / omega_window(omega_diag_idx)) * 1e9;
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'mask_diag_empty_representative_slice', ...
            'CerUPP:MaskDiagnostics:EmptyRepresentativePassband', ...
            ['The representative nearest-omega_fund sampled mask slice after the omega guard has no passing ', ...
             'region (omega_diag_idx=%d, lambda_diag=%.3f nm). Continuing because the full 3-D omega ', ...
             'passband is checked separately.'], ...
            omega_diag_idx, lambda_diag_nm);
    end

    if ~logical(simple_masks_flag)

        % For smooth masks, report the nearly flat region, the
        % 0.50-amplitude / 25%-intensity region, and the strongly
        % suppressed edge in both real space and transverse-k.
        thr_flat = rep_flat_thresh;
        thr_half = 0.50;

        sel_flat = r_2(mask_xy >= thr_flat);
        if isempty(sel_flat)
            r_flat_max = NaN;
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', 'mask_diag_empty_flat', ...
                'CerUPP:MaskDiagnostics:EmptyRealMaskThreshold', ...
                'mask_xy has no points with mask >= %.2f; reporting NaN for flat-region radius diagnostic.', ...
                thr_flat);
        else
            r_flat_max = max(sel_flat);
        end

        sel_half = r_2(mask_xy >= thr_half);
        if isempty(sel_half)
            r_half_max = NaN;
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', 'mask_diag_empty_half', ...
                'CerUPP:MaskDiagnostics:EmptyRealMaskThreshold', ...
                ['mask_xy has no points with mask >= %.2f; reporting NaN for the ', ...
                 '25%%-intensity radius diagnostic (mask amplitude threshold).'], ...
                thr_half);
        else
            r_half_max = max(sel_half);
        end
        x_half_span = max(abs(x));
        y_half_span = max(abs(y));
        r_box = min(x_half_span, y_half_span);
        spatial_inner_frac_report = r_inner / max(r_box, eps);

        fprintf('Real-space absorber:\n');
        fprintf('  x/y half-spans                  = (%.3f, %.3f) um\n', ...
            1e6*x_half_span, 1e6*y_half_span);
        fprintf('  Inscribed radial half-span (R_box) = %.3f um\n', 1e6*r_box);
        fprintf('  Inner flat region (mask >= %.2f) = %.3f um\n', thr_flat, 1e6*r_flat_max);
        fprintf('  25%%-intensity radius           = %.3f um (mask amplitude >= %.2f)\n', ...
            1e6*r_half_max, thr_half);
        fprintf('  Taper parameters: spatial_inner_frac = %.3f, R_inner = %.3f um, R_outer = %.3f um\n', ...
            spatial_inner_frac_report, 1e6*r_inner, 1e6*r_outer);

        fprintf(['\nk-space setup scalars (worst case over the sampled omega bins ', ...
                 'used to build the mask):\n']);
        fprintf('  kNyquist x,y  = (%.3e, %.3e) 1/m\n', k_nyx, k_nyy);
        fprintf('  diagnostic radial kNyquist (kNy) = %.3e 1/m\n', k_ny);
        fprintf('  diagnostic physical review cutoff (kcut_phys) = %.3e 1/m [k_min = %.3e 1/m]\n', ...
            kcut_phys, k_min_med);
        fprintf('  carrier medium k (k_fund)     = %.3e 1/m [n_core(lambda_fund)=%.4f]\n', ...
            n_ref_kcut * k0_vac, n_ref_kcut);
        fprintf('  rectangular Nyquist gate uses |kx| < %.3e and |ky| < %.3e 1/m\n', ...
            k_rect_gate_x, k_rect_gate_y);
        fprintf('  diagnostic inscribed-circle Nyquist summary (kcut_ny)= %.3e 1/m\n', kcut_ny);
        fprintf(['  kept-band diagnostic physical cutoff summary ', ...
                 '(kcut=min(kcut_w on eventual nonzero omega support)) = %.3e 1/m\n'], ...
            kcut);
        fprintf(['  diagnostic review-shoulder width summary ', ...
                 '(ramp=kperp_ramp_frac*kcut) = %.3e 1/m\n'], ...
            ramp);
        if isfinite(active_kcut)
            fprintf('  final active-band transverse Nyquist support edge (kept omega slices only) = %.3e 1/m\n', ...
                active_kcut);
        end
        if isfinite(active_kflat)
            fprintf(['  final active-band near-flat support ceiling ', ...
                     '(combined k/omega mask >= %.2f) = %.3e 1/m\n'], ...
                thr_flat, active_kflat);
        end
        fprintf(['\nRepresentative nearest-omega_fund sampled slice after the ', ...
                 'omega guard:\n']);
        if ~rep_slice_has_passband
            fprintf(['  The representative slice has no surviving passband after the omega guard. ', ...
                     'Threshold-based k diagnostics below report NaN where needed.\n']);
        end

        sel_k_flat = kperp(mask_f_xy_current >= thr_flat);
        if isempty(sel_k_flat)
            k_flat_max = NaN;
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', 'mask_diag_empty_k_flat', ...
                'CerUPP:MaskDiagnostics:EmptyKMaskThreshold', ...
                ['The rebuilt representative Fourier-mask slice has no points with mask >= %.2f; ', ...
                 'reporting NaN for the flat-region k diagnostic.'], ...
                thr_flat);
        else
            k_flat_max = max(sel_k_flat);
        end

        sel_k_half = kperp(mask_f_xy_current >= thr_half);
        if isempty(sel_k_half)
            k_half_max = NaN;
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', 'mask_diag_empty_k_half', ...
                'CerUPP:MaskDiagnostics:EmptyKMaskThreshold', ...
                ['The rebuilt representative Fourier-mask slice has no points with mask >= %.2f; ', ...
                 'reporting NaN for the 25%%-intensity k diagnostic (mask amplitude threshold).'], ...
                thr_half);
        else
            k_half_max = max(sel_k_half);
        end

        na_flat_vac = min(max(k_flat_max / max(k0_vac, eps), 0), 1);
        na_half_vac = min(max(k_half_max / max(k0_vac, eps), 0), 1);
        theta_flat = asin(na_flat_vac);
        theta_half = asin(na_half_vac);

        fprintf(['  k where mask_f_xy >= %.2f : k_flat_max = %.3e 1/m, ', ...
                 'theta_flat_vac  = %.3f deg\n'], ...
            thr_flat, k_flat_max, theta_flat*180/pi);
        fprintf(['  k where mask_f_xy >= %.2f : k_half_max = %.3e 1/m, ', ...
                 'theta_amp_half_vac = %.3f deg\n'], ...
            thr_half, k_half_max, theta_half*180/pi);

        fourier_mask_support_thresh = 1e-3;
        k_suppressed = kperp(mask_f_xy_current < fourier_mask_support_thresh);
        if ~isempty(k_suppressed)
            k_supp_min = min(k_suppressed);
            k_supp_max = max(k_suppressed);
            na_supp_min_vac = min(max(k_supp_min / max(k0_vac, eps), 0), 1);
            na_supp_max_vac = min(max(k_supp_max / max(k0_vac, eps), 0), 1);
            theta_supp_min = asin(na_supp_min_vac);
            theta_supp_max = asin(na_supp_max_vac);
            fprintf('  Strongly suppressed region (mask_f_xy < %.1e):\n', fourier_mask_support_thresh);
            fprintf('    k in [%.3e, %.3e] 1/m    [%.3f, %.3f] deg vacuum-equivalent\n', ...
                k_supp_min, k_supp_max, theta_supp_min*180/pi, theta_supp_max*180/pi);
        else
            fprintf(['  No sampled k points with rebuilt representative Fourier-mask amplitude < %.1e ', ...
                     'on the representative slice.\n'], ...
                fourier_mask_support_thresh);
        end
    else

        % In simple-mask mode, report the hard radial aperture and the same
        % nearest-omega_fund representative transverse-k slice returned by
        % build_masks(...).
        r_hard = min(abs([x(mask_pad_x+1), x(end-mask_pad_x), ...
                          y(mask_pad_y+1), y(end-mask_pad_y)]));
        frac_r_core = mean(r_2(:) <= r_hard);
        fprintf('Hard radial masks enabled (simple_masks_flag = true).\n');

        fprintf('\nReal-space hard radial mask:\n');
        fprintf('  Full x-span: [%.3f, %.3f] um (dx = %.3f um per cell)\n', ...
            1e6*x_min, 1e6*x_max, 1e6*delta_x);
        fprintf('  Full y-span: [%.3f, %.3f] um (dy = %.3f um per cell)\n', ...
            1e6*y_min, 1e6*y_max, 1e6*delta_y);
        fprintf('  Hard aperture radius (mask = 1): %.3f um (%.1f%% of grid cells)\n', ...
            1e6*r_hard, 100*frac_r_core);
        fprintf('  Guard-pad inputs: mask_pad_x = %d, mask_pad_y = %d\n', ...
            mask_pad_x, mask_pad_y);

        fprintf(['\nk-space rectangular Nyquist mask at the representative nearest-omega_fund ', ...
                 'sampled slice after the omega guard:\n']);
        [~, omega_diag_idx] = min(abs(omega_window - omega_fund));
        lambda_diag_nm = (2*pi*c / omega_window(omega_diag_idx)) * 1e9;
        if ~rep_slice_has_passband
            k_pass_max = NaN;
            theta_pass = NaN;
            fprintf('  Representative slice lambda ~= %.2f nm\n', lambda_diag_nm);
            fprintf('  Passing k radius (mask_f = 1): NaN 1/m\n');
            fprintf('  Approx. vacuum-equivalent passband half-angle: theta_vac,max = NaN deg\n');
            fprintf(['  The representative nearest-omega_fund slice has no passing region after the ', ...
                     'omega guard, so this setup diagnostic reports NaN while the full spectral-passband ', ...
                     'check remains authoritative.\n']);
        elseif ~isfinite(lambda_fund) || (lambda_fund <= 0)
            diagnostic_message = 'lambda_fund must be finite and > 0 when computing diagnostic k0_vac.';
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', ...
                'setup_invalid_lambda_fund_diag_skip', ...
                 'CerUPP:InvalidLambdaFundForK0DiagSkip', ...
                '%s Skipping small-angle diagnostic printout.', diagnostic_message);
        else
            k_pass = kperp(mask_f_xy_current > 0.5);
            k_pass_max = max(k_pass);
            na_pass_vac = min(max(k_pass_max / max(k0_vac, eps), 0), 1);
            theta_pass = asin(na_pass_vac);
            fprintf('  Representative slice lambda ~= %.2f nm\n', lambda_diag_nm);
            fprintf('  Passing k radius (mask_f = 1): %.3e 1/m\n', k_pass_max);
            fprintf('  Approx. vacuum-equivalent passband half-angle: theta_vac,max = %.3f deg\n', ...
                theta_pass*180/pi);
        end

        fprintf(['  This simple path reports the current nearest-omega_fund representative ', ...
                 'slice rebuilt from the final mask stack, with no cosine taper.\n']);
        fprintf(['  kperp_ramp_frac is ignored when simple_masks_flag=true because the ', ...
                 'propagated transverse-k mask is the rectangular Nyquist gate.\n']);
    end

    % The omega-only guard band acts independently of the transverse masks,
    % so report its outer nonzero-support and flat-interior slices
    % separately.
    fprintf('\nSpectral guard-band (omega/lambda) from mask_pad_w = %d:\n', mask_pad_w);
    mask_f_w_vec = reshape(mask_f_w, [], 1);
    % The omega guard in mask_f_w is the spectral passband the stepper
    % actually keeps. A setup hard stop should only reject bins that the
    % guard removes completely, not bins with a smaller nonzero weight.
    idx_pass = find(mask_f_w_vec > 0);
    idx_supp = find(mask_f_w_vec <= 0);
    if isempty(idx_pass)
        error('CerUPP:Mask:EmptySpectralPassband', ...
            'mask_pad_w=%d eliminated all omega bins (n=%d).', ...
            mask_pad_w, numel(omega_window));
    end
    omega_pass_lo = min(omega_window(idx_pass));
    omega_pass_hi = max(omega_window(idx_pass));
    lambda_pass_lo = 2*pi*c ./ omega_pass_hi;
    lambda_pass_hi = 2*pi*c ./ omega_pass_lo;
    [~, omega_fund_idx] = min(abs(omega_window - omega_fund));
    omega_fund_nearest = omega_window(omega_fund_idx);
    omega_fund_bin_pass = mask_f_w_vec(omega_fund_idx) > 0;
    if (omega_fund < omega_pass_lo) || (omega_fund > omega_pass_hi) || ~omega_fund_bin_pass
        error('CerUPP:Mask:OmegaFundOutsideGuardedPassband', ...
            ['The omega-only guard keeps omega_window=[%.6e, %.6e] rad/s, but ', ...
             'omega_fund=%.6e rad/s is not represented inside that kept passband. ', ...
             'Nearest sampled bin is omega_window(%d)=%.6e rad/s with mask_f_w=%g. ', ...
             'Reduce mask_pad_w or widen the simulated omega window so the guarded ', ...
             'passband keeps omega_fund.'], ...
            omega_pass_lo, omega_pass_hi, omega_fund, omega_fund_idx, ...
            omega_fund_nearest, double(mask_f_w_vec(omega_fund_idx)));
    end
    flat_guard_tol = 1e-12;
    idx_flat = find(mask_f_w_vec >= (1 - flat_guard_tol));
    if isempty(idx_flat)
        omega_flat_lo = NaN;
        omega_flat_hi = NaN;
        lambda_flat_lo = NaN;
        lambda_flat_hi = NaN;
        omega_fund_bin_flat = false;
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'setup_mask_no_unit_weight_omega_plateau', ...
            'CerUPP:Mask:EmptySpectralFlatPassbandSoft', ...
            ['mask_pad_w=%d leaves no unit-weight interior in mask_f_w. ', ...
             'Continuing because the omega guard still keeps a nonzero propagated ', ...
             'passband; setup reports the flat interior as absent instead of ', ...
             'stopping the run.'], ...
            mask_pad_w);
    else
        omega_flat_lo = min(omega_window(idx_flat));
        omega_flat_hi = max(omega_window(idx_flat));
        omega_fund_bin_flat = mask_f_w_vec(omega_fund_idx) >= (1 - flat_guard_tol);
        lambda_flat_lo = 2*pi*c ./ omega_flat_hi;
        lambda_flat_hi = 2*pi*c ./ omega_flat_lo;
    end
    fprintf('  Nonzero-support omega-window: [%.3e, %.3e] rad/s\n', ...
        omega_pass_lo, omega_pass_hi);
    fprintf('  Nonzero-support lambda-window: [%.2f, %.2f] nm\n', ...
        lambda_pass_lo*1e9, lambda_pass_hi*1e9);
    if isempty(idx_flat)
        fprintf('  Flat omega-window: none (no unit-weight interior in mask_f_w)\n');
        fprintf('  Flat lambda-window: none (no unit-weight interior in mask_f_w)\n');
    else
        fprintf('  Flat omega-window: [%.3e, %.3e] rad/s\n', ...
            omega_flat_lo, omega_flat_hi);
        fprintf('  Flat lambda-window: [%.2f, %.2f] nm\n', ...
            lambda_flat_lo*1e9, lambda_flat_hi*1e9);
    end
    if ~isempty(idx_flat) && ~omega_fund_bin_flat
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'setup_mask_carrier_on_omega_guard_shoulder', ...
            'CerUPP:Mask:OmegaFundInsideGuardShoulderSoft', ...
            ['The omega-only guard keeps omega_fund=%.6e rad/s inside the nonzero ', ...
             'support, but its nearest sampled bin omega_window(%d)=%.6e rad/s sits ', ...
             'on the smooth guard edge band with mask_f_w=%g instead of the flat ', ...
             'interior [%.6e, %.6e] rad/s. Continuing with that edge-band-weighted ', ...
             'carrier bin.'], ...
            omega_fund, omega_fund_idx, omega_fund_nearest, ...
            double(mask_f_w_vec(omega_fund_idx)), omega_flat_lo, omega_flat_hi);
    end
    if ~isempty(idx_supp)
        omega_supp = omega_window(idx_supp);
        omega_supp_lo = omega_supp(omega_supp < omega_ref);
        omega_supp_hi = omega_supp(omega_supp > omega_ref);
        if ~isempty(omega_supp_lo)
            lambda_supp_lo = 2*pi*c ./ omega_supp_lo;
            fprintf('  Suppressed low-omega guard band:   [%.2f, %.2f] nm (%d slices)\n', ...
                min(lambda_supp_lo)*1e9, max(lambda_supp_lo)*1e9, numel(omega_supp_lo));
        end
        if ~isempty(omega_supp_hi)
            lambda_supp_hi = 2*pi*c ./ omega_supp_hi;
            fprintf('  Suppressed high-omega guard band:  [%.2f, %.2f] nm (%d slices)\n', ...
                min(lambda_supp_hi)*1e9, max(lambda_supp_hi)*1e9, numel(omega_supp_hi));
        end
    else
        fprintf('  No spectral guard-band active (mask_pad_w = 0).\n');
    end
    fprintf('\nNonlinear/core mask mask_2_d (x,y):\n');
    inside_frac = mean(mask_2_d(:) > 0.5);
    fprintf('  Fraction of transverse grid cells with mask_2_d > 0.5: %.3f\n', inside_frac);
    fprintf('  Nominal core_radius        = %.3f um\n', 1e6*core_radius);
    fprintf('=================================================\n\n');

    % Report the outer admitted k-edge from the built mask geometry before
    % the launch field exists. Section 4A later adds the launch-weighted
    % companion summary from the actual launched field, and only that
    % later report owns the high-NA soft warning.
    kcut_summary = double(kcut);
    if isfinite(active_kcut) && (active_kcut > 0)
        kcut_summary = active_kcut;
    end
    kflat_summary = NaN;
    if isfinite(active_kflat) && (active_kflat > 0)
        kflat_summary = active_kflat;
    end
    na_cut_vac = min(max(kcut_summary / max(k0_vac, eps), 0), 1);
    na_cut_med = min(max(kcut_summary / max(n_ref_kcut * k0_vac, eps), 0), 1);
    na_eff_worst = min(max(kcut_summary / max(k_min_med, eps), 0), 1);
    eps_div = na_eff_worst.^2;
    fprintf(['Setup k-filter aperture summary: NA_vac(outer nonzero-support) = %.3f ', ...
             '(theta_vac,max = %.3f deg), '], ...
        na_cut_vac, asin(na_cut_vac)*180/pi);
    fprintf(['NA_med(outer nonzero-support,fund) = %.3f, ', ...
             'NA_eff,max(outer nonzero-support) = %.3f, ', ...
             'NA_eff,max^2 = %.4f (n_core = %.4f)\n'], ...
        na_cut_med, na_eff_worst, eps_div, n_ref_kcut);
    if isfinite(kflat_summary)
        na_flat_vac = min(max(kflat_summary / max(k0_vac, eps), 0), 1);
        na_flat_med = min(max(kflat_summary / max(n_ref_kcut * k0_vac, eps), 0), 1);
        na_eff_flat = min(max(kflat_summary / max(k_min_med, eps), 0), 1);
        fprintf(['  Near-flat full-mask support: NA_vac(joint k/omega flat zone) = %.3f, ', ...
                 'NA_med(joint k/omega flat zone,fund) = %.3f, ', ...
                 'NA_eff,max(joint k/omega flat zone) = %.3f\n'], ...
            na_flat_vac, na_flat_med, na_eff_flat);
    end
    end


    function run_warn_state = mask_setup_launch_weighted_angle_report( ...
        A_F, k_passband_mask, omega_passband_mask, kperp, ...
        k_band_med, kcut, k_min_med, run_warn_state)
    % Section 4A launch-angle summary for the actual launched field.
    % Revisit the same high-angle geometry after A_F exists so setup can
    % report where the launched weight actually sits, not just where the
    % built k-edge lies.
    % In the usual Section 4A call path, A_F is already the post-launch
    % runtime field after binary k/omega cleanup and the real-space
    % absorber.

    % Skip cleanly if the launch field or geometry arrays were never built.
    if isempty(A_F) || isempty(kperp) || isempty(k_band_med)
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'setup_launch_weighted_angle_summary_skipped', ...
            'CerUPP:SetupHighNA:LaunchWeightedAngleSummarySkipped', ...
            'launch-spectrum weighted angle summary skipped because one or more setup arrays were empty.');
        return;
    end

    if ~isequal(size(A_F, 1), size(kperp, 1)) || ~isequal(size(A_F, 2), size(kperp, 2)) || ...
            (size(A_F, 3) ~= numel(k_band_med))
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'setup_launch_weighted_angle_summary_shape_mismatch', ...
            'CerUPP:SetupHighNA:LaunchWeightedAngleShapeMismatch', ...
            ['launch-spectrum weighted angle summary skipped because A_F/kperp/k_band_med ', ...
             'did not have the expected compatible shapes.']);
        return;
    end
    if ~isempty(omega_passband_mask) && ...
            (numel(omega_passband_mask) ~= numel(k_band_med))
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'setup_launch_weighted_angle_summary_omega_mask_shape_mismatch', ...
            'CerUPP:SetupHighNA:LaunchWeightedAngleOmegaMaskShapeMismatch', ...
            ['launch-spectrum weighted angle summary skipped because the omega-edge mask ', ...
             'did not have one entry per spectral bin.']);
        return;
    end

    % Use the actual built spectral reference-medium state that the run
    % already carries instead of rebuilding a family-level Sellmeier curve
    % just for this summary.
    k_band_med = double(k_band_med(:));
    kperp_abs = double(kperp);
    high_na_threshold = 0.03;
    high_na_fraction_warn_threshold = 0.03;
    total_weight = 0;
    weighted_na_sq_sum = 0;
    high_na_weight = 0;
    launch_support_nonzero_na_max = 0;
    launch_support_occupied_na_max = 0;
    active_support_na_max = 0;
    masked_launch_weight_peak = 0;
    nonfinite_weight_count = 0;
    launch_weight_rel_tol = 1e-12;
    mask_is_2d = ~isempty(k_passband_mask) && ...
        isequal(size(k_passband_mask), size(A_F(:, :, 1)));
    mask_is_3d = ~isempty(k_passband_mask) && isequal(size(k_passband_mask), size(A_F));
    use_mask = mask_is_2d || mask_is_3d;
    mask_w = ones(1, numel(k_band_med));
    if ~isempty(omega_passband_mask)
        mask_w = reshape(abs(double(omega_passband_mask)).^2, 1, []);
    end

    % Accumulate wavelength-by-wavelength launch weight inside the active
    % passband so the final summary reflects the actual initial spectrum.
    for iw = 1:numel(k_band_med)
        k_med_i = k_band_med(iw);
        if ~(isfinite(k_med_i) && (k_med_i > 0))
            continue;
        end

        A_slice = A_F(:, :, iw);
        w_slice = double(real(A_slice .* conj(A_slice)));
        support_mask = true(size(kperp_abs));
        if use_mask
            if mask_is_3d
                k_mask_slice = k_passband_mask(:, :, iw);
            else
                k_mask_slice = k_passband_mask;
            end
            w_slice = w_slice .* abs(double(k_mask_slice)).^2;
            support_mask = abs(double(k_mask_slice)) > 0;
        end
        if mask_w(iw) <= 0
            support_mask(:) = false;
        end
        w_slice = w_slice .* mask_w(iw);
        nonfinite_weight_count = nonfinite_weight_count + nnz(~isfinite(w_slice(:)));
        finite_w_slice = w_slice(isfinite(w_slice));
        if ~isempty(finite_w_slice)
            masked_launch_weight_peak = max(masked_launch_weight_peak, ...
                max(finite_w_slice(:)));
        end

        na_map = min(kperp_abs / k_med_i, 1);
        if any(support_mask(:))
            active_support_na_max = max(active_support_na_max, ...
                max(na_map(support_mask)));
        end
        if ~any(w_slice(:))
            continue;
        end
        total_weight = total_weight + sum(w_slice(:));
        weighted_na_sq_sum = weighted_na_sq_sum + sum(sum(w_slice .* (na_map.^2)));
        positive_launch_mask = (w_slice > 0);
        if any(positive_launch_mask(:))
            launch_support_nonzero_na_max = max(launch_support_nonzero_na_max, ...
                max(na_map(positive_launch_mask)));
        end
        selected_weight = w_slice(na_map > high_na_threshold);
        high_na_weight = high_na_weight + sum(selected_weight(:));
    end

    if ~isfinite(total_weight)
        error('CerUPP:SetupHighNA:NonfiniteMaskedLaunchSpectrum', ...
            ['The built initial spectrum produced a nonfinite masked launch ', ...
             'weight before the launch-angle summary (nonfinite masked-weight count=%d). ', ...
             'Refusing to continue from a corrupted masked launch spectrum.'], ...
            nonfinite_weight_count);
    end
    if total_weight <= 0
        error('CerUPP:SetupHighNA:EmptyMaskedLaunchSpectrum', ...
            ['The built initial spectrum has no surviving launch content after the active ', ...
             'transverse-k mask and omega guard are applied. Refusing to continue from an ', ...
             'empty masked launch spectrum.']);
    end

    launch_weight_floor = launch_weight_rel_tol * masked_launch_weight_peak;
    if isfinite(launch_weight_floor) && (launch_weight_floor > 0)
        for iw = 1:numel(k_band_med)
            k_med_i = k_band_med(iw);
            if ~(isfinite(k_med_i) && (k_med_i > 0))
                continue;
            end

            A_slice = A_F(:, :, iw);
            w_slice = double(real(A_slice .* conj(A_slice)));
            if use_mask
                if mask_is_3d
                    k_mask_slice = k_passband_mask(:, :, iw);
                else
                    k_mask_slice = k_passband_mask;
                end
                w_slice = w_slice .* abs(double(k_mask_slice)).^2;
            end
            w_slice = w_slice .* mask_w(iw);
            occupied_launch_mask = isfinite(w_slice) & (w_slice >= launch_weight_floor);
            if any(occupied_launch_mask(:))
                na_map = min(kperp_abs / k_med_i, 1);
                launch_support_occupied_na_max = max(launch_support_occupied_na_max, ...
                    max(na_map(occupied_launch_mask)));
            end
        end
    end

    % Report the weighted RMS angle, a thresholded occupied-launch edge,
    % the surviving nonzero launch tail, and the outer kept support so the
    % summary distinguishes meaningful launch weight from tiny tails.
    na_eff_support_max = min(max(double(active_support_na_max), 0), 1);
    na_eff_rms_init = sqrt(max(weighted_na_sq_sum / total_weight, 0));
    high_na_energy_frac = min(max(high_na_weight / total_weight, 0), 1);
    na_eff_launch_nonzero_max = min(max(double(launch_support_nonzero_na_max), 0), 1);
    na_eff_launch_occupied_max = min(max(double(launch_support_occupied_na_max), 0), 1);
    fprintf(['Launch-spectrum weighted angle summary: NA_eff,rms(init) = %.4f, ', ...
             'energy fraction with NA_eff > %.2f = %.4g\n'], ...
        na_eff_rms_init, high_na_threshold, high_na_energy_frac);
    fprintf(['  masked-launch occupied NA_eff,max = %.4f ', ...
             '(occupied means masked weight >= %.1e of the masked-launch peak), ', ...
             'masked-launch nonzero-tail NA_eff,max = %.4f, ', ...
             'outer nonzero-support NA_eff,max = %.4f\n'], ...
        na_eff_launch_occupied_max, launch_weight_rel_tol, ...
        na_eff_launch_nonzero_max, na_eff_support_max);
    if high_na_energy_frac > high_na_fraction_warn_threshold
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'setup_launch_weighted_high_na', ...
            'CerUPP:SetupHighNA:LaunchWeightedHighNA', ...
            ['The masked initial launch spectrum places an energy fraction %.4g above ', ...
             'NA_eff > %.2f. This is a launch-weighted high-angle warning, so a nontrivial ', ...
             'part of the initial spectrum is entering a regime where the forward-envelope ', ...
             'assumptions may need review. Check k-filter sensitivity and ', ...
             'angle-resolved outputs if this is intentional.'], ...
            high_na_energy_frac, high_na_threshold);
    end
    end

    function [mask_f_xy_current, omega_diag_idx, active_kcut, active_kflat] = ...
            resolve_final_mask_support_local( ...
                mask_f, mask_f_w, kperp, omega_window, omega_fund, ...
                flat_thresh)
    % Rebuild the representative Fourier-mask slice from the final mask
    % stack and summarize both the outer nonzero-support and near-flat
    % transverse-k support after the omega guard has already been applied.
    % The near-flat ceiling is based on the combined transverse-k and
    % omega-mask amplitude, not on mask_f alone.

    mask_f_xy_current = [];
    omega_diag_idx = [];
    active_kcut = NaN;
    active_kflat = NaN;
    if isempty(mask_f) || (ndims(mask_f) < 3) || isempty(omega_window)
        return;
    end

    nw_mask = size(mask_f, 3);
    mask_f_w_vec = ones(nw_mask, 1);
    if ~isempty(mask_f_w)
        mask_f_w_vec = reshape(double(mask_f_w), [], 1);
        nw_mask = min(nw_mask, numel(mask_f_w_vec));
    end
    omega_window_vec = double(omega_window(:));
    nw_common = min(nw_mask, numel(omega_window_vec));
    if nw_common <= 0
        return;
    end

    mask_f = mask_f(:, :, 1:nw_common);
    mask_f_w_vec = mask_f_w_vec(1:nw_common);
    omega_window_vec = omega_window_vec(1:nw_common);
    [~, omega_diag_idx] = min(abs(omega_window_vec - double(omega_fund)));
    mask_f_xy_current = double(mask_f(:, :, omega_diag_idx)) .* ...
        mask_f_w_vec(omega_diag_idx);

    active_idx = find(mask_f_w_vec > 0);
    for iactive = 1:numel(active_idx)
        iw = active_idx(iactive);
        mask_slice = double(mask_f(:, :, iw));
        mask_w_i = mask_f_w_vec(iw);
        pass_mask = mask_slice > 0;
        if any(pass_mask(:))
            kcut_i = max(double(kperp(pass_mask)));
            if ~isfinite(active_kcut)
                active_kcut = kcut_i;
            else
                active_kcut = min(active_kcut, kcut_i);
            end
        end
        flat_mask = (mask_slice .* mask_w_i) >= flat_thresh;
        if any(flat_mask(:))
            kflat_i = max(double(kperp(flat_mask)));
            if ~isfinite(active_kflat)
                active_kflat = kflat_i;
            else
                active_kflat = min(active_kflat, kflat_i);
            end
        end
    end

    if isfinite(active_kcut) && ...
            (~isfinite(active_kflat) || (active_kflat > active_kcut))
        active_kflat = active_kcut;
    end
    end

    function keep_mask = resolve_zero_support_omega_keep_mask_local(mask_pad_w, nw)
    % Rebuild the exact nonzero-support omega bins implied by mask_pad_w.
    % Smooth and simple omega guards share the same exact-zero outer bins;
    % only the interior amplitudes differ.

    keep_mask_ctr = false(1, 1, nw);
    edge_w = min(mask_pad_w, nw);
    if (2 * edge_w) < nw
        keep_mask_ctr(1, 1, edge_w+1:end-edge_w) = true;
    end
    keep_mask = reshape(ifftshift(keep_mask_ctr, 3), [], 1);
    end

end
end
