function varargout = cerupp_section2a_startup_handoff(varargin)
% Driver-only Section 2A helper for cerupp.m.
% In the usual no-input mode this helper reads the current cerupp.m
% workspace, settles the Section 2A startup/medium handoff, and
% assigns the resulting variables back into the driver workspace.
% To change the run or physics inputs, edit the visible Section 1 knobs in
% cerupp.m instead of editing this helper.

    if nargin == 0
        caller_field_names = { ...
            'setup_freeze_guard', ...
            'frozen_cfg_raw_startup_setup', ...
            'perf_cfg', ...
            'output_cfg', ...
            'runtime_setup', ...
            'run_warn_state', ...
            'plot_warn_flag', ...
            'diagnostics_flag', ...
            'track_energy_flag', ...
            'show_plasma_stiffness_diagnostic_flag', ...
            'plasma_stiffness_diagnostic_stride', ...
            'progress_print_stride', ...
            'reuse_linear_guiding_operator_cache_flag', ...
            'enable_advance_step_substep_timing_flag', ...
            'advance_step_substep_timing_sample_count', ...
            'enable_memory_monitor_flag', ...
            'memmon_abort_gb', ...
            'memmon_abort_on_exceed', ...
            'memmon_first_n_steps', ...
            'memmon_stride', ...
            'memmon_projection_stride_steps', ...
            'enable_wallclock_timeout_abort_flag', ...
            'wallclock_expected_timeout_hours', ...
            'wallclock_projection_min_steps', ...
            'fluence_use_parseval', ...
            'show_plots_flag', ...
            'show_3d_diagnostic_plots_flag', ...
            'make_initial_plots_flag', ...
            'save_outputs_as_fig_flag', ...
            'save_outputs_as_png_flag', ...
            'run_postprocessing_flag', ...
            'store_reduced_spectral_z_diagnostics_flag', ...
            'z_3d_slice', ...
            'store_phase_map_flag', ...
            'store_spectral_fluence_flag', ...
            'store_full_spectrum_flag', ...
            'diagnostic_store_stride_steps', ...
            'intermediate_saves_flag', ...
            'checkpoint_stride_steps', ...
            'a_s_rho_snapshot_checkpoint_stride_steps', ...
            'checkpoint_full_save_flag', ...
            'checkpoint_unique_files_flag', ...
            'checkpoint_diag_reassembly_flag', ...
            'save_final_full_output_flag', ...
            'fullsave_collect_core_history_flag', ...
            'save_final_restart_checkpoint_flag', ...
            'save_end_snapshot_flag', ...
            'write_current_run_pointer_flag', ...
            'write_latest_successful_run_id_flag', ...
            'write_run_status_flag', ...
            'enable_console_output_log_flag', ...
            'show_additional_dev_plots', ...
            'enable_drho_xz_diagnostics', ...
            'output_root', ...
            'run_tag', ...
            'append_timestamp_to_run_id', ...
            'archive_existing_run_output_root', ...
            'auto_timestamp_on_run_output_collision', ...
            'quick_debug_mode_flag', ...
            'enable_setup_freeze_guard_flag', ...
            'lambda_fund', ...
            'core_radius', ...
            'n2_kerr', ...
            'n2_kerr_disable_tol', ...
            'selected_builtin_medium_family', ...
            'n2_air_placeholder_threshold', ...
            'keldysh_lut_i_roi_min', ...
            'keldysh_electron_effective_mass_over_me', ...
            'keldysh_hole_effective_mass_over_me', ...
            'ui', ...
            'keldysh_gap', ...
            'keldysh_matched_depletion', ...
            'rho_nt', ...
            'k_power_vec', ...
            'sigma_k_vec', ...
            'tau_c', ...
            'alpha_recombine', ...
            'plasma_m_over_me', ...
            'air_placeholder_ui', ...
            'air_placeholder_rho_nt', ...
            'air_placeholder_k_power', ...
            'air_placeholder_sigma_k', ...
            'distance_to_propagate', ...
            'stepsize', ...
            't_window', ...
            'n', ...
            'lambda_ref', ...
            'mask_pad_w', ...
            'mask_pad_x', ...
            'mask_pad_y', ...
            'spatial_inner_frac', ...
            'kperp_alpha', ...
            'kperp_ramp_frac', ...
            'kperp_nyquist_frac', ...
            'mask_loss_warn_frac', ...
            'comp_window_x_width', ...
            'num_x_pts', ...
            'comp_window_y_width', ...
            'num_y_pts', ...
            'n_recompute_tol', ...
            'n2_recompute_tol', ...
            'plasma_flag', ...
            'nl_absorption_flag', ...
            'keldysh_enabled', ...
            'keldysh_use_interference_corrected_rate_flag', ...
            'keldysh_display_k', ...
            'plasma_ofi_use_remaining_neutral_factor_flag', ...
            'nla_use_remaining_neutral_factor_flag', ...
            'keldysh_lookup_csv_name', ...
            'allow_keldysh_cache_reuse_without_match', ...
            'nla_use_ofi_rate_law_flag', ...
            'use_nlse_flag', ...
            'z_dependent_medium_flag', ...
            'allow_z_dependent_keldysh', ...
            'ion_routine_flag', ...
            'fee_z_rk2_flag', ...
            'plasma_z_rk2_flag', ...
            'nla_z_rk2_flag', ...
            'plasma_evolve_t_rk2_flag', ...
            'use_exact_avalanche_exp_update_flag', ...
            'keldysh_lut_n_global', ...
            'keldysh_lut_n_roi', ...
            'keldysh_lut_i_global_min', ...
            'keldysh_zero_rate_below', ...
            'keldysh_lut_i_global_max', ...
            'keldysh_lut_i_roi_max', ...
            'rho_plasma_cap', ...
            'rho_neutral_supply', ...
            'simple_masks_flag', ...
            'nonparaxial_diffraction_order', ...
            'i_fil_cutoff', ...
            'i_fil_cutoff_vis', ...
            'rho_fil_cutoff', ...
            'me'};
        cfg = struct();
        for ii = 1:numel(caller_field_names)
            field_name = caller_field_names{ii};
            try
                cfg.(field_name) = evalin('caller', field_name);
            catch err
                if strcmp(err.identifier, 'MATLAB:UndefinedFunction') || ...
                        strcmp(err.identifier, 'MATLAB:UndefinedVariable')
                    error('CerUPP:MissingSection1FCallerField', ...
                        ['cerupp_section2a_startup_handoff expected caller variable ''%s'' ', ...
                         'to exist before the Section 2A helper call.'], ...
                        field_name);
                end
                rethrow(err);
            end
        end

        section2a_state = build_section2a_state_local(cfg);
        output_field_names = fieldnames(section2a_state);
        for ii = 1:numel(output_field_names)
            field_name = output_field_names{ii};
            assignin('caller', field_name, section2a_state.(field_name));
        end
        if nargout > 0
            varargout{1} = section2a_state;
        end
        return;
    end

    if (nargin ~= 1) || ~isstruct(varargin{1}) || ~isscalar(varargin{1})
        error('CerUPP:InvalidSection1FSetupCfg', ...
            'cerupp_section2a_startup_handoff accepts either no inputs or one scalar cfg struct.');
    end

    section2a_state = build_section2a_state_local(varargin{1});
    if nargout > 1
        error('CerUPP:InvalidSection1FSetupOutputCount', ...
            'cerupp_section2a_startup_handoff returns at most one output struct.');
    end
    if nargout == 1
        varargout{1} = section2a_state;
    end
end

function section2a_state = build_section2a_state_local(cfg)
    raw_medium_inputs = driver_setup_support.build_raw_medium_inputs_local(cfg);
    raw_medium_setup = driver_setup_support.build_raw_medium_setup_local( ...
        raw_medium_inputs);
    raw_rho_plasma_cap = cfg.rho_plasma_cap;
    raw_rho_neutral_supply = cfg.rho_neutral_supply;
    keldysh_display_k_requested_raw = cfg.keldysh_display_k;
    keldysh_lookup_csv_name_requested_raw = cfg.keldysh_lookup_csv_name;
    keldysh_lut_i_roi_min_requested_raw = cfg.keldysh_lut_i_roi_min;
    computational_setup_surface = ...
        driver_setup_support.build_computational_setup_surface_local(struct( ...
            'distance_to_propagate', cfg.distance_to_propagate, ...
            'stepsize', cfg.stepsize, ...
            't_window', cfg.t_window, ...
            'n', cfg.n, ...
            'lambda_ref', cfg.lambda_ref, ...
            'mask_pad_w', cfg.mask_pad_w, ...
            'mask_pad_x', cfg.mask_pad_x, ...
            'mask_pad_y', cfg.mask_pad_y, ...
            'spatial_inner_frac', cfg.spatial_inner_frac, ...
            'kperp_alpha', cfg.kperp_alpha, ...
            'kperp_ramp_frac', cfg.kperp_ramp_frac, ...
            'kperp_nyquist_frac', cfg.kperp_nyquist_frac, ...
            'mask_loss_warn_frac', cfg.mask_loss_warn_frac, ...
            'comp_window_x_width', cfg.comp_window_x_width, ...
            'num_x_pts', cfg.num_x_pts, ...
            'comp_window_y_width', cfg.comp_window_y_width, ...
            'num_y_pts', cfg.num_y_pts, ...
            'n_recompute_tol', cfg.n_recompute_tol, ...
            'n2_recompute_tol', cfg.n2_recompute_tol));
    raw_section2_inputs = project_cfg_fields_local(cfg, { ...
        'plasma_flag', 'nl_absorption_flag', 'keldysh_enabled', ...
        'keldysh_use_interference_corrected_rate_flag', ...
        'keldysh_display_k', 'plasma_ofi_use_remaining_neutral_factor_flag', ...
        'nla_use_remaining_neutral_factor_flag', ...
        'keldysh_lookup_csv_name', ...
        'allow_keldysh_cache_reuse_without_match', ...
        'nla_use_ofi_rate_law_flag', 'use_nlse_flag', ...
        'z_dependent_medium_flag', 'allow_z_dependent_keldysh', ...
        'ion_routine_flag', 'fee_z_rk2_flag', 'plasma_z_rk2_flag', ...
        'nla_z_rk2_flag', 'plasma_evolve_t_rk2_flag', ...
        'use_exact_avalanche_exp_update_flag', 'keldysh_lut_n_global', ...
        'keldysh_lut_n_roi', 'keldysh_lut_i_global_min', ...
        'keldysh_zero_rate_below', 'keldysh_lut_i_global_max', ...
        'keldysh_lut_i_roi_max', 'rho_plasma_cap', ...
        'rho_neutral_supply', 'simple_masks_flag', ...
        'nonparaxial_diffraction_order', 'i_fil_cutoff', ...
        'i_fil_cutoff_vis', 'rho_fil_cutoff', 'diagnostics_flag', ...
        'checkpoint_diag_reassembly_flag', 'enable_drho_xz_diagnostics', ...
        'reuse_linear_guiding_operator_cache_flag', ...
        'diagnostic_store_stride_steps', 'checkpoint_stride_steps', ...
        'a_s_rho_snapshot_checkpoint_stride_steps', ...
        'memmon_projection_stride_steps'}, ...
        'cerupp_section2a_startup_handoff.raw_section2_inputs');
    frozen_cfg_raw_section2_setup = ...
        driver_setup_support.build_raw_section2_setup_local(struct( ...
        'raw_section2_inputs', raw_section2_inputs, ...
        'raw_medium_setup', raw_medium_setup, ...
        'computational_setup_surface', computational_setup_surface));

    startup_context = 'cerupp_section2a_startup_handoff.startup_cfg';
    runtime_setup = struct_utils.req_struct_field(cfg, 'runtime_setup', startup_context);
    startup_cfg = project_cfg_fields_local(cfg, { ...
        'setup_freeze_guard', ...
        'frozen_cfg_raw_startup_setup', ...
        'perf_cfg', ...
        'output_cfg', ...
        'plot_warn_flag', ...
        'diagnostics_flag', ...
        'track_energy_flag', ...
        'show_plasma_stiffness_diagnostic_flag', ...
        'plasma_stiffness_diagnostic_stride', ...
        'progress_print_stride', ...
        'reuse_linear_guiding_operator_cache_flag', ...
        'enable_advance_step_substep_timing_flag', ...
        'advance_step_substep_timing_sample_count', ...
        'enable_memory_monitor_flag', ...
        'memmon_abort_gb', ...
        'memmon_abort_on_exceed', ...
        'memmon_first_n_steps', ...
        'memmon_stride', ...
        'memmon_projection_stride_steps', ...
        'enable_wallclock_timeout_abort_flag', ...
        'wallclock_expected_timeout_hours', ...
        'wallclock_projection_min_steps', ...
        'fluence_use_parseval', ...
        'show_plots_flag', ...
        'show_3d_diagnostic_plots_flag', ...
        'make_initial_plots_flag', ...
        'save_outputs_as_fig_flag', ...
        'save_outputs_as_png_flag', ...
        'run_postprocessing_flag', ...
        'store_reduced_spectral_z_diagnostics_flag', ...
        'z_3d_slice', ...
        'store_phase_map_flag', ...
        'store_spectral_fluence_flag', ...
        'store_full_spectrum_flag', ...
        'diagnostic_store_stride_steps', ...
        'intermediate_saves_flag', ...
        'checkpoint_stride_steps', ...
        'a_s_rho_snapshot_checkpoint_stride_steps', ...
        'checkpoint_full_save_flag', ...
        'checkpoint_unique_files_flag', ...
        'checkpoint_diag_reassembly_flag', ...
        'save_final_full_output_flag', ...
        'fullsave_collect_core_history_flag', ...
        'save_final_restart_checkpoint_flag', ...
        'save_end_snapshot_flag', ...
        'write_current_run_pointer_flag', ...
        'write_latest_successful_run_id_flag', ...
        'write_run_status_flag', ...
        'enable_console_output_log_flag', ...
        'show_additional_dev_plots', ...
        'enable_drho_xz_diagnostics', ...
        'output_root', ...
        'run_tag', ...
        'append_timestamp_to_run_id', ...
        'archive_existing_run_output_root', ...
        'auto_timestamp_on_run_output_collision', ...
        'quick_debug_mode_flag'}, ...
        startup_context);
    startup_cfg.outdir = struct_utils.req_struct_field( ...
        runtime_setup, 'outdir', startup_context);

    [setup_freeze_guard, frozen_cfg_raw_startup_setup, ...
        startup_perf_cfg, output_cfg, cadence_cfg, plot_settings, ...
        fluence_use_parseval_requested, fluence_use_parseval, ...
        fluence_method_name_requested, fluence_method_name] = ...
        driver_setup_support.build_section1f_startup_state_local(startup_cfg);

    setup_freeze_guard = user_setup_guard.capture_surface( ...
        setup_freeze_guard, 'raw_section2_setup', ...
        ['Freeze block 2/4 (Section 2 raw setup) before the Section 2A medium/plasma handoff, ', ...
         'the first Keldysh setup/LUT build, and the later Section-2 selected builders read them'], ...
        frozen_cfg_raw_section2_setup);

    frozen_setup_only_plot_controls = struct( ...
        'plot_warn_flag', cfg.plot_warn_flag, ...
        'show_plots_flag', cfg.show_plots_flag, ...
        'show_3d_diagnostic_plots_flag', ...
            cfg.show_3d_diagnostic_plots_flag, ...
        'make_initial_plots_flag', cfg.make_initial_plots_flag, ...
        'save_outputs_as_fig_flag', cfg.save_outputs_as_fig_flag, ...
        'save_outputs_as_png_flag', cfg.save_outputs_as_png_flag);
    setup_freeze_guard = user_setup_guard.capture_surface( ...
        setup_freeze_guard, 'setup_only_plot_controls', ...
        ['Freeze block 3A/4 (plot/export controls reused by the ', ...
         'runtime/postprocess plot policy) before Section 2A builds ', ...
         'plot_settings.initial and the setup-time Keldysh/initial-plot ', ...
         'path reads them'], ...
        frozen_setup_only_plot_controls);

    handoff_context = 'cerupp_section2a_startup_handoff.handoff_cfg';
    handoff_cfg = project_cfg_fields_local(cfg, { ...
        'run_warn_state', ...
        'plasma_flag', ...
        'keldysh_enabled', ...
        'keldysh_use_interference_corrected_rate_flag', ...
        'plasma_ofi_use_remaining_neutral_factor_flag', ...
        'nla_use_remaining_neutral_factor_flag', ...
        'rho_plasma_cap', ...
        'rho_neutral_supply', ...
        'nl_absorption_flag', ...
        'nla_use_ofi_rate_law_flag', ...
        'use_exact_avalanche_exp_update_flag', ...
        'me', ...
        'keldysh_display_k', ...
        'keldysh_lookup_csv_name', ...
        'allow_z_dependent_keldysh', ...
        'ion_routine_flag', ...
        'use_nlse_flag', ...
        'plasma_evolve_t_rk2_flag', ...
        'keldysh_lut_n_global', ...
        'keldysh_lut_n_roi', ...
        'nonparaxial_diffraction_order', ...
        'quick_debug_mode_flag', ...
        'enable_setup_freeze_guard_flag', ...
        'runtime_setup'}, ...
        handoff_context);
    handoff_cfg.raw_medium_setup = raw_medium_setup;
    handoff_cfg.perf_cfg = startup_perf_cfg;
    handoff_cfg.output_cfg = output_cfg;
    handoff_cfg.fluence_use_parseval_requested = fluence_use_parseval_requested;
    handoff_cfg.fluence_use_parseval = fluence_use_parseval;
    handoff_cfg.fluence_method_name_requested = fluence_method_name_requested;
    handoff_cfg.fluence_method_name = fluence_method_name;

    [setup_physics_state, setup_output_state, setup_runtime_state, ...
        run_warn_state, selected_builtin_medium_family, ...
        n2_kerr, kerr_enabled_flag, default_rho_density_interpretation] = ...
        driver_setup_support.build_section1f_handoff_bundles_local(handoff_cfg);

    [medium_setup_state, plasma_setup_state, run_control_state] = ...
        driver_setup_support.build_section1f_runtime_setup_state( ...
            setup_physics_state, setup_output_state, setup_runtime_state);

    [medium_cfg, medium_cfg_defaults, medium_param_knobs_applied, medium_spec, ...
        propagation_medium_name, medium_kind] = struct_utils.unpack_struct_fields( ...
        medium_setup_state, ...
        {'medium_cfg', 'medium_cfg_defaults', 'medium_param_knobs_applied', ...
         'medium_spec', 'propagation_medium_name', 'medium_kind'}, ...
        'cerupp_section2a_startup_handoff.medium_setup_state');

    [frozen_cfg_ui, frozen_cfg_keldysh_gap_j, frozen_cfg_keldysh_matched_depletion_j, ...
        frozen_cfg_ofi_k_orders, frozen_cfg_sigma_k_vec, ...
        frozen_cfg_rho_nt_m3, frozen_cfg_rho_nt_keldysh_norm_m3, ...
        frozen_cfg_neutral_reservoir_m3, rho_plasma_cap, ...
        rho_neutral_supply, ...
        plasma_runtime_cfg, plasma_stiffness_diagnostic, ...
        frozen_cfg_tau_c, frozen_cfg_alpha_recombine, ...
        setup_physics_rewrite_report, keldysh_enabled, ...
        keldysh_use_interference_corrected_rate_flag, ...
        keldysh_display_k, plasma_ofi_use_remaining_neutral_factor_flag, ...
        nla_use_remaining_neutral_factor_flag, resolved_nla_setup_closure, ...
        keldysh_convention_autoselect_used, ...
        resolved_keldysh_convention_desc, keldysh_mred_over_me, ...
        keldysh_mred_kg, plasma_m_over_me, ...
        m_plasma_kg, keldysh_lookup_csv_name] = struct_utils.unpack_struct_fields( ...
        plasma_setup_state, ...
        {'frozen_cfg_ui', 'frozen_cfg_keldysh_gap_j', ...
         'frozen_cfg_keldysh_matched_depletion_j', 'frozen_cfg_ofi_k_orders', ...
         'frozen_cfg_sigma_k_vec', 'frozen_cfg_rho_nt_m3', ...
         'frozen_cfg_rho_nt_keldysh_norm_m3', 'frozen_cfg_neutral_reservoir_m3', ...
         'rho_plasma_cap', 'rho_neutral_supply', ...
         'plasma_runtime_cfg', 'plasma_stiffness_diagnostic', ...
         'frozen_cfg_tau_c', 'frozen_cfg_alpha_recombine', ...
         'setup_physics_rewrite_report', 'keldysh_enabled', ...
         'keldysh_use_interference_corrected_rate_flag', ...
         'keldysh_display_k', 'plasma_ofi_use_remaining_neutral_factor_flag', ...
         'nla_use_remaining_neutral_factor_flag', 'resolved_nla_setup_closure', ...
         'keldysh_convention_autoselect_used', ...
         'resolved_keldysh_convention_desc', 'keldysh_mred_over_me', ...
         'keldysh_mred_kg', 'plasma_m_over_me', 'm_plasma_kg', ...
         'keldysh_lookup_csv_name'}, ...
        'cerupp_section2a_startup_handoff.plasma_setup_state');

    [run_warn_state, ion_routine_flag, ion_routine_flag_requested, ...
        use_nlse_flag, use_nlse_flag_requested, ...
        nonparaxial_diffraction_order, nonparaxial_diffraction_order_requested, ...
        phase_diagnostic_flag, strict_stage_finite_scan_flag, run_meta, ...
        perf_cfg] = struct_utils.unpack_struct_fields( ...
        run_control_state, ...
        {'run_warn_state', 'ion_routine_flag', 'ion_routine_flag_requested', ...
         'use_nlse_flag', 'use_nlse_flag_requested', ...
         'nonparaxial_diffraction_order', ...
         'nonparaxial_diffraction_order_requested', 'phase_diagnostic_flag', ...
         'strict_stage_finite_scan_flag', 'run_meta', 'perf_cfg'}, ...
        'cerupp_section2a_startup_handoff.run_control_state');

    frozen_section2_computational = struct_utils.req_struct_field( ...
        frozen_cfg_raw_section2_setup, 'computational', ...
        'cerupp_section2a_startup_handoff.frozen_cfg_raw_section2_setup');
    frozen_section2_medium_selector = struct_utils.req_struct_field( ...
        frozen_cfg_raw_section2_setup, 'medium_selector', ...
        'cerupp_section2a_startup_handoff.frozen_cfg_raw_section2_setup');

    section2a_state = struct( ...
        'distance_to_propagate', frozen_section2_computational.distance_to_propagate, ...
        'stepsize', frozen_section2_computational.stepsize, ...
        't_window', frozen_section2_computational.t_window, ...
        'n', frozen_section2_computational.n, ...
        'lambda_ref', frozen_section2_computational.lambda_ref, ...
        'mask_pad_w', frozen_section2_computational.mask_pad_w, ...
        'mask_pad_x', frozen_section2_computational.mask_pad_x, ...
        'mask_pad_y', frozen_section2_computational.mask_pad_y, ...
        'spatial_inner_frac', frozen_section2_computational.spatial_inner_frac, ...
        'kperp_alpha', frozen_section2_computational.kperp_alpha, ...
        'kperp_ramp_frac', frozen_section2_computational.kperp_ramp_frac, ...
        'kperp_nyquist_frac', frozen_section2_computational.kperp_nyquist_frac, ...
        'mask_loss_warn_frac', frozen_section2_computational.mask_loss_warn_frac, ...
        'comp_window_x_width', frozen_section2_computational.comp_window_x_width, ...
        'num_x_pts', frozen_section2_computational.num_x_pts, ...
        'comp_window_y_width', frozen_section2_computational.comp_window_y_width, ...
        'num_y_pts', frozen_section2_computational.num_y_pts, ...
        'n_recompute_tol', frozen_section2_computational.n_recompute_tol, ...
        'n2_recompute_tol', frozen_section2_computational.n2_recompute_tol, ...
        'lambda_fund', frozen_section2_medium_selector.lambda_fund, ...
        'core_radius', frozen_section2_medium_selector.core_radius, ...
        'show_plots_flag', cfg.show_plots_flag, ...
        'make_initial_plots_flag', cfg.make_initial_plots_flag, ...
        'save_outputs_as_fig_flag', cfg.save_outputs_as_fig_flag, ...
        'save_outputs_as_png_flag', cfg.save_outputs_as_png_flag, ...
        'show_3d_diagnostic_plots_flag', cfg.show_3d_diagnostic_plots_flag, ...
        'show_additional_dev_plots', cfg.show_additional_dev_plots, ...
        'diagnostic_store_stride_steps', cfg.diagnostic_store_stride_steps, ...
        'checkpoint_stride_steps', cfg.checkpoint_stride_steps, ...
        'a_s_rho_snapshot_checkpoint_stride_steps', ...
            cfg.a_s_rho_snapshot_checkpoint_stride_steps, ...
        'z_3d_slice', cfg.z_3d_slice, ...
        'setup_freeze_guard', setup_freeze_guard, ...
        'frozen_cfg_raw_startup_setup', frozen_cfg_raw_startup_setup, ...
        'raw_medium_setup', raw_medium_setup, ...
        'computational_setup_surface', computational_setup_surface, ...
        'frozen_cfg_raw_section2_setup', frozen_cfg_raw_section2_setup, ...
        'output_cfg', output_cfg, ...
        'cadence_cfg', cadence_cfg, ...
        'plot_settings', plot_settings, ...
        'fluence_use_parseval_requested', fluence_use_parseval_requested, ...
        'fluence_use_parseval', fluence_use_parseval, ...
        'fluence_method_name_requested', fluence_method_name_requested, ...
        'fluence_method_name', fluence_method_name, ...
        'selected_builtin_medium_family', ...
            frozen_section2_medium_selector.selected_builtin_medium_family, ...
        'n2_air_placeholder_threshold', ...
            frozen_section2_medium_selector.n2_air_placeholder_threshold, ...
        'raw_rho_plasma_cap', raw_rho_plasma_cap, ...
        'raw_rho_neutral_supply', raw_rho_neutral_supply, ...
        'keldysh_display_k_requested_raw', ...
            keldysh_display_k_requested_raw, ...
        'keldysh_lookup_csv_name_requested_raw', ...
            keldysh_lookup_csv_name_requested_raw, ...
        'keldysh_lut_i_roi_min_requested_raw', ...
            keldysh_lut_i_roi_min_requested_raw, ...
        'air_placeholder_branch_active', ...
            struct_utils.req_struct_field(setup_physics_state, ...
                'air_placeholder_branch_active', ...
                'cerupp_section2a_startup_handoff.setup_physics_state'), ...
        'n2_kerr', frozen_section2_medium_selector.n2_kerr, ...
        'n2_kerr_disable_tol', frozen_section2_medium_selector.n2_kerr_disable_tol, ...
        'keldysh_lut_i_roi_min', frozen_section2_medium_selector.keldysh_lut_i_roi_min, ...
        'kerr_enabled_flag', kerr_enabled_flag, ...
        'default_rho_density_interpretation', ...
            default_rho_density_interpretation, ...
        'medium_cfg', medium_cfg, ...
        'medium_cfg_defaults', medium_cfg_defaults, ...
        'medium_param_knobs_applied', medium_param_knobs_applied, ...
        'medium_spec', medium_spec, ...
        'propagation_medium_name', propagation_medium_name, ...
        'medium_kind', medium_kind, ...
        'frozen_cfg_ui', frozen_cfg_ui, ...
        'frozen_cfg_keldysh_gap_j', frozen_cfg_keldysh_gap_j, ...
        'frozen_cfg_keldysh_matched_depletion_j', ...
            frozen_cfg_keldysh_matched_depletion_j, ...
        'frozen_cfg_ofi_k_orders', frozen_cfg_ofi_k_orders, ...
        'frozen_cfg_sigma_k_vec', frozen_cfg_sigma_k_vec, ...
        'frozen_cfg_rho_nt_m3', frozen_cfg_rho_nt_m3, ...
        'frozen_cfg_rho_nt_keldysh_norm_m3', ...
            frozen_cfg_rho_nt_keldysh_norm_m3, ...
        'frozen_cfg_neutral_reservoir_m3', frozen_cfg_neutral_reservoir_m3, ...
        'rho_plasma_cap', rho_plasma_cap, ...
        'rho_neutral_supply', rho_neutral_supply, ...
        'plasma_runtime_cfg', plasma_runtime_cfg, ...
        'plasma_stiffness_diagnostic', plasma_stiffness_diagnostic, ...
        'frozen_cfg_tau_c', frozen_cfg_tau_c, ...
        'frozen_cfg_alpha_recombine', frozen_cfg_alpha_recombine, ...
        'setup_physics_rewrite_report', setup_physics_rewrite_report, ...
        'keldysh_enabled', keldysh_enabled, ...
        'keldysh_use_interference_corrected_rate_flag', ...
            keldysh_use_interference_corrected_rate_flag, ...
        'keldysh_display_k', keldysh_display_k, ...
        'plasma_ofi_use_remaining_neutral_factor_flag', ...
            plasma_ofi_use_remaining_neutral_factor_flag, ...
        'nla_use_remaining_neutral_factor_flag', ...
            nla_use_remaining_neutral_factor_flag, ...
        'resolved_nla_setup_closure', resolved_nla_setup_closure, ...
        'keldysh_convention_autoselect_used', ...
            keldysh_convention_autoselect_used, ...
        'resolved_keldysh_convention_desc', ...
            resolved_keldysh_convention_desc, ...
        'keldysh_mred_over_me', keldysh_mred_over_me, ...
        'keldysh_mred_kg', keldysh_mred_kg, ...
        'plasma_m_over_me', plasma_m_over_me, ...
        'm_plasma_kg', m_plasma_kg, ...
        'keldysh_lookup_csv_name', keldysh_lookup_csv_name, ...
        'run_warn_state', run_warn_state, ...
        'ion_routine_flag', ion_routine_flag, ...
        'ion_routine_flag_requested', ion_routine_flag_requested, ...
        'use_nlse_flag', use_nlse_flag, ...
        'use_nlse_flag_requested', use_nlse_flag_requested, ...
        'nonparaxial_diffraction_order', nonparaxial_diffraction_order, ...
        'nonparaxial_diffraction_order_requested', ...
            nonparaxial_diffraction_order_requested, ...
        'phase_diagnostic_flag', phase_diagnostic_flag, ...
        'strict_stage_finite_scan_flag', strict_stage_finite_scan_flag, ...
        'run_meta', run_meta, ...
        'perf_cfg', perf_cfg);
end

function projected_cfg = project_cfg_fields_local(cfg, field_names, context_name)
    projected_cfg = struct();
    for ii = 1:numel(field_names)
        field_name = field_names{ii};
        projected_cfg.(field_name) = struct_utils.req_struct_field( ...
            cfg, field_name, context_name);
    end
end
