function varargout = cerupp_section5f_finalize_outputs(varargin)
% Driver-only Section 5F helper for cerupp.m.
% In the usual no-input mode this helper reads the current cerupp.m
% workspace, finalizes the post-propagation output state, and assigns the
% resulting Section 5F variables back into the driver workspace.

    if nargin == 0
        caller_field_names = caller_field_names_local();
        cfg = struct();
        for ii = 1:numel(caller_field_names)
            field_name = caller_field_names{ii};
            try
                cfg.(field_name) = evalin('caller', field_name);
            catch err
                if strcmp(err.identifier, 'MATLAB:UndefinedFunction') || ...
                        strcmp(err.identifier, 'MATLAB:UndefinedVariable')
                    error('CerUPP:MissingSection5FCallerField', ...
                        ['cerupp_section5f_finalize_outputs expected caller variable ''%s'' ', ...
                         'to exist before the Section 5F helper call.'], ...
                        field_name);
                end
                rethrow(err);
            end
        end
        section5f_state = build_section5f_state_local(cfg);
        output_field_names = fieldnames(section5f_state);
        for ii = 1:numel(output_field_names)
            field_name = output_field_names{ii};
            assignin('caller', field_name, section5f_state.(field_name));
        end
        if nargout > 0
            varargout{1} = section5f_state;
        end
        return;
    end

    if (nargin ~= 1) || ~isstruct(varargin{1}) || ~isscalar(varargin{1})
        error('CerUPP:InvalidSection5FCfg', ...
            'cerupp_section5f_finalize_outputs accepts either no inputs or one scalar cfg struct.');
    end

    section5f_state = build_section5f_state_local(varargin{1});
    if nargout > 1
        error('CerUPP:InvalidSection5FOutputCount', ...
            'cerupp_section5f_finalize_outputs returns at most one output struct.');
    end
    if nargout == 1
        varargout{1} = section5f_state;
    end
end

function caller_field_names = caller_field_names_local()
    caller_field_names = { ...
        'perf_cfg', ...
        'A_S', ...
        'A_F', ...
        'A_SSF', ...
        'rho', ...
        'rhs_plasma', ...
        'step_diag', ...
        'peak_naninfo', ...
        'save_idx', ...
        'num_storage_steps', ...
        'output_plan', ...
        'completed_z_steps', ...
        'final_z_curr', ...
        'final_z_pre_step', ...
        'final_z_post_step', ...
        'final_dz', ...
        'post_step_runtime_state', ...
        'sampled_step_timing_target', ...
        't_prop', ...
        'checkpoint_vars_full', ...
        'checkpoint_diag_reassembly_flag', ...
        'track_keldysh_effective_nla_diag_flag', ...
        'energy', ...
        'energy_launch', ...
        'plasma_flag', ...
        'plasma_runtime_cfg', ...
        'nla_runtime_cfg', ...
        'run_meta', ...
        'runtime_setup', ...
        'rebuild_policy', ...
        'any_medium_rebuild_applied', ...
        'warning_ledgers', ...
        'driver_extension_inputs', ...
        'custom_checkpoint_restart_fields', ...
        'terminal_store_matches_accepted_state', ...
        'terminal_store_contract_reason', ...
        'diag_state', ...
        'grid_state', ...
        'medium_state', ...
        'output_state', ...
        'run_warn_state'};
end

function section5f_state = build_section5f_state_local(cfg)
    postprop_timing_summary_flag = ...
        cfg.perf_cfg.enable_advance_step_substep_timing_flag;
    final_accepted_state = restart_pipeline_utils.build_accepted_state_from_live( ...
        cfg.A_S, cfg.A_F, cfg.A_SSF, cfg.rho);
    final_step_reassembly_state = ...
        restart_pipeline_utils.build_step_reassembly_state_from_live( ...
            cfg.rhs_plasma, cfg.step_diag);
    final_a_s_state_finite = ~isempty(cfg.A_S) && all(isfinite(cfg.A_S(:)));
    final_a_f_state_finite = ~isempty(cfg.A_F) && all(isfinite(cfg.A_F(:)));
    final_rho_state_finite = true;
    final_rho_state_shape_ok = true;
    if cfg.plasma_flag
        final_rho_state_finite = ...
            ~isempty(cfg.rho) && all(isfinite(cfg.rho(:)));
        final_rho_state_shape_ok = ...
            isequal(size(cfg.rho), size(cfg.A_S));
    end
    end_snapshot_publication_allowed = final_a_s_state_finite;
    end_snapshot_blocked_reason = '';
    if ~end_snapshot_publication_allowed
        end_snapshot_blocked_reason = 'nonfinite_terminal_a_s_state';
    end

    postprop_finalize_source = struct( ...
        'peak_naninfo', cfg.peak_naninfo, ...
        'save_idx', cfg.save_idx, ...
        'num_storage_steps', cfg.num_storage_steps, ...
        'store_beamcenter_history_flag', ...
            logical(cfg.output_plan.resolved.history.store_beamcenter_history_flag.effective), ...
        'num_zsteps', cfg.completed_z_steps, ...
        'z_curr', cfg.final_z_curr, ...
        'z_pre_step_m', cfg.final_z_pre_step, ...
        'z_post_step_m', cfg.final_z_post_step, ...
        'dz', cfg.final_dz, ...
        'post_step_runtime_state', cfg.post_step_runtime_state, ...
        'sampled_step_timing_target', cfg.sampled_step_timing_target, ...
        'enable_advance_step_substep_timing_flag', postprop_timing_summary_flag, ...
        't_prop', cfg.t_prop, ...
        'output_cfg', cfg.output_plan.request, ...
        'checkpoint_vars_full', {cfg.checkpoint_vars_full}, ...
        'checkpoint_diag_reassembly_flag', ...
            cfg.checkpoint_diag_reassembly_flag, ...
        'track_energy_flag', cfg.perf_cfg.track_energy_flag, ...
        'include_keldysh_effective_nla_diag_flag', ...
            cfg.track_keldysh_effective_nla_diag_flag, ...
        'energy', cfg.energy, ...
        'energy_launch', cfg.energy_launch, ...
        'plasma_runtime_cfg', cfg.plasma_runtime_cfg, ...
        'nla_runtime_cfg', cfg.nla_runtime_cfg, ...
        'run_meta', cfg.run_meta, ...
        'run_output_root', cfg.runtime_setup.run_output_root, ...
        'z_dependent_medium_effective', ...
            cfg.rebuild_policy.z_dependent_medium_effective, ...
        'any_medium_rebuild_applied', cfg.any_medium_rebuild_applied, ...
        'plasma_softwarn_state', cfg.warning_ledgers.plasma, ...
        'driver_extension_inputs', cfg.driver_extension_inputs, ...
        'custom_checkpoint_restart_fields', ...
            cfg.custom_checkpoint_restart_fields, ...
        'terminal_store_matches_accepted_state', ...
            cfg.terminal_store_matches_accepted_state, ...
        'terminal_store_contract_reason', ...
            cfg.terminal_store_contract_reason, ...
        'end_snapshot_publication_allowed', ...
            end_snapshot_publication_allowed, ...
        'end_snapshot_blocked_reason', end_snapshot_blocked_reason);

    terminal_output_publication_allowed = ...
        final_a_s_state_finite && final_a_f_state_finite && ...
        final_rho_state_finite && final_rho_state_shape_ok;
    terminal_propagated_state = build_terminal_propagated_state_local( ...
        final_a_s_state_finite, final_a_f_state_finite, ...
        final_rho_state_finite, final_rho_state_shape_ok, cfg.plasma_flag);
    run_end_state = struct( ...
        'finalization', struct( ...
            'requested', false, ...
            'attempted', false, ...
            'ok', true, ...
            'scaffold_ok', true, ...
            'skipped_reason', '', ...
            'error_id', '', ...
            'error_message', ''), ...
        'postprocess', struct( ...
            'requested', logical(cfg.output_plan.resolved.effective.run_postprocessing_flag), ...
            'attempted', false, ...
            'phase_ok', true, ...
            'requested_outputs_complete', true, ...
            'ok', true, ...
            'result', 'succeeded', ...
            'requested_outputs_skipped_reason', '', ...
            'new_output_io_failure_count', 0, ...
            'family_failure_count', 0, ...
            'family_skip_count', 0, ...
            'family_blocking_skip_count', 0, ...
            'family_ledger', struct(), ...
            'error_id', '', ...
            'error_message', '', ...
            'skipped_reason', ''), ...
        'terminal_store_contract', struct( ...
            'matches_accepted_state', cfg.terminal_store_matches_accepted_state, ...
            'reason', cfg.terminal_store_contract_reason), ...
        'terminal_propagated_state', terminal_propagated_state, ...
        'intermediate', struct(), ...
        'final_outputs', struct(), ...
        'reporting', struct());

    requested_broad_terminal_publication = ...
        run_end_state.postprocess.requested || ...
        cfg.output_plan.request.save_final_restart_checkpoint_flag || ...
        cfg.output_plan.request.save_final_full_output_flag;
    need_postprop_finalize_state = ...
        terminal_output_publication_allowed && ...
        requested_broad_terminal_publication;
    run_end_state.finalization.requested = requested_broad_terminal_publication;
    run_warn_state = cfg.run_warn_state;
    if requested_broad_terminal_publication && ~terminal_output_publication_allowed
        run_end_state.finalization.ok = false;
        run_end_state.finalization.skipped_reason = 'invalid_terminal_state';
        run_end_state.finalization.error_id = 'CerUPP:InvalidTerminalState';
        run_end_state.finalization.error_message = ...
            ['Skipping ordinary terminal restart/fullsave writes ', ...
             'and Section 6A because final A_S, A_F, and/or rho was missing, ', ...
             'nonfinite, or shape-mismatched before the final end-of-run save/write phase.'];
        if run_end_state.postprocess.requested
            run_end_state.postprocess.requested_outputs_complete = false;
            run_end_state.postprocess.requested_outputs_skipped_reason = ...
                'invalid_terminal_state';
        end
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'end', ...
            'invalid_terminal_state_blocks_publication', ...
            'CerUPP:InvalidTerminalStateBlocksPublication', ...
            ['Final A_S, A_F, and/or rho was missing, nonfinite, or shape-mismatched ', ...
             'at the end of propagation. Skipping ordinary terminal restart/fullsave ', ...
             'writes and Section 6A.']);
    end

    postprocess_runtime_state = struct();
    postprocess_diag_state = cfg.diag_state;
    postprocess_summary_state = struct();
    postprocess_final_state = struct();
    final_restart_attempted_postprop = false;
    final_restart_save_ok = ...
        ~cfg.output_plan.request.save_final_restart_checkpoint_flag;
    final_restart_write_state = ...
        restart_pipeline_utils.build_empty_final_restart_write_state( ...
            cfg.output_plan.request.save_final_restart_checkpoint_flag);
    final_restart_fallback_error_id = '';
    final_restart_fallback_error_message = '';
    end_snapshot_write_state = ...
        restart_pipeline_utils.build_empty_end_snapshot_write_state( ...
            cfg.output_plan.request.save_end_snapshot_flag);
    end_snapshot_attempted_postprop = false;
    end_snapshot_save_ok = end_snapshot_write_state.ok;
    final_fullsave_build_cfg = [];

    if need_postprop_finalize_state
        run_end_state.finalization.attempted = true;
        try
            [postprocess_runtime_state, postprocess_diag_state, ...
                postprocess_summary_state, final_restart_save_ok, ...
                final_restart_write_state, ...
                end_snapshot_write_state, final_fullsave_build_cfg, ...
                run_warn_state] = ...
                restart_pipeline_utils.finalize_postprop_run_outputs_from_live( ...
                    cfg.grid_state, cfg.medium_state, cfg.output_state, ...
                    struct('postprop_finalize_source', postprop_finalize_source), ...
                    final_accepted_state, final_step_reassembly_state, ...
                    cfg.diag_state, [], struct(), run_warn_state);
            final_restart_attempted_postprop = logical( ...
                cfg.output_plan.request.save_final_restart_checkpoint_flag);
            end_snapshot_attempted_postprop = end_snapshot_write_state.attempted;
            end_snapshot_save_ok = end_snapshot_write_state.ok;
            timing = postprocess_runtime_state.timing;
            plasma_runtime_cfg = postprocess_runtime_state.plasma_runtime_cfg;
            run_meta = postprocess_runtime_state.run_meta;
        catch me_postprop_finalize
            run_end_state.finalization.ok = false;
            run_end_state.finalization.scaffold_ok = false;
            run_end_state.finalization.skipped_reason = ...
                'postprop_finalization_failed';
            run_end_state.finalization.error_id = ...
                me_postprop_finalize.identifier;
            run_end_state.finalization.error_message = ...
                me_postprop_finalize.message;
            final_fullsave_build_cfg = [];
            run_warn_state = run_warn_state_utils.emit_phase_summary( ...
                run_warn_state, 'after_prop', 'propagation', true);
            postprop_reporting_cfg = ...
                propagation_support.normalize_postprop_phase_inputs( ...
                    struct( ...
                        'grid_state', cfg.grid_state, ...
                        'medium_state', cfg.medium_state, ...
                        'output_state', cfg.output_state, ...
                        'runtime_state', ...
                            struct('postprop_finalize_source', ...
                                postprop_finalize_source), ...
                        'accepted_state', final_accepted_state, ...
                        'step_reassembly_state', final_step_reassembly_state, ...
                        'diag_state', cfg.diag_state, ...
                        'postprop_diag_state', [], ...
                        'summary_state', struct()));
            postprop_reporting_cfg.postprop_finalize_source = ...
                postprop_finalize_source;
            postprop_reporting_cfg = ...
                restart_pipeline_utils.expand_postprop_finalize_source_local( ...
                    postprop_reporting_cfg);
            timing = ...
                propagation_support.build_runtime_checkpoint_summary_from_samples_local( ...
                    postprop_reporting_cfg);
            postprocess_diag_state = struct();
            postprocess_summary_state = struct();
            postprocess_runtime_state = struct();
            plasma_runtime_cfg = cfg.plasma_runtime_cfg;
            run_meta = cfg.run_meta;
            final_restart_attempted_postprop = false;
            final_restart_save_ok = ...
                ~cfg.output_plan.request.save_final_restart_checkpoint_flag;
            if cfg.output_plan.request.save_end_snapshot_flag
                end_snapshot_write_state = ...
                    restart_pipeline_utils.build_empty_end_snapshot_write_state(true);
                end_snapshot_write_state.ok = false;
                end_snapshot_write_state.blocked_reason = ...
                    'postprop_finalization_failed';
                end_snapshot_write_state.error_id = ...
                    me_postprop_finalize.identifier;
                end_snapshot_write_state.error_message = ...
                    me_postprop_finalize.message;
            else
                end_snapshot_write_state.ok = true;
            end
            end_snapshot_attempted_postprop = false;
            end_snapshot_save_ok = end_snapshot_write_state.ok;
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'end', ...
                'postprop_finalization_failed', ...
                'CerUPP:PostpropFinalizationFailed', ...
                ['Post-propagation finalization failed after propagation completed. ', ...
                 'Skipping the dependent Section 6A and terminal post-finalization ', ...
                 'save paths, and continuing with the remaining end-of-run ', ...
                 'status path. ', ...
                 'Error: %s (%s)'], ...
                me_postprop_finalize.message, ...
                me_postprop_finalize.identifier);
        end
    else
        run_end_state.finalization.scaffold_ok = ...
            run_end_state.finalization.ok;
        postprop_reporting_cfg = ...
            propagation_support.normalize_postprop_phase_inputs( ...
                struct( ...
                    'grid_state', cfg.grid_state, ...
                    'medium_state', cfg.medium_state, ...
                    'output_state', cfg.output_state, ...
                    'runtime_state', ...
                        struct('postprop_finalize_source', ...
                            postprop_finalize_source), ...
                    'accepted_state', final_accepted_state, ...
                    'step_reassembly_state', final_step_reassembly_state, ...
                    'diag_state', cfg.diag_state, ...
                    'postprop_diag_state', [], ...
                    'summary_state', struct()));
        postprop_reporting_cfg.postprop_finalize_source = ...
            postprop_finalize_source;
        postprop_reporting_cfg = ...
            restart_pipeline_utils.expand_postprop_finalize_source_local( ...
                postprop_reporting_cfg);
        if isempty(run_end_state.finalization.skipped_reason)
            run_end_state.finalization.skipped_reason = 'not_needed';
        end
        timing = ...
            propagation_support.build_runtime_checkpoint_summary_from_samples_local( ...
                postprop_reporting_cfg);
        plasma_runtime_cfg = cfg.plasma_runtime_cfg;
        run_meta = cfg.run_meta;
        run_warn_state = run_warn_state_utils.emit_phase_summary( ...
            run_warn_state, 'after_prop', 'propagation', true);
    end

    if cfg.output_plan.request.save_end_snapshot_flag && ...
            run_end_state.finalization.ok && ~end_snapshot_attempted_postprop
        end_snapshot_runtime_cfg = ...
            propagation_support.normalize_postprop_phase_inputs( ...
                struct( ...
                    'grid_state', cfg.grid_state, ...
                    'medium_state', cfg.medium_state, ...
                    'output_state', cfg.output_state, ...
                    'runtime_state', ...
                        struct('postprop_finalize_source', ...
                            postprop_finalize_source), ...
                    'accepted_state', final_accepted_state, ...
                    'step_reassembly_state', final_step_reassembly_state, ...
                    'diag_state', cfg.diag_state, ...
                    'postprop_diag_state', postprocess_diag_state, ...
                    'summary_state', struct()));
        end_snapshot_runtime_cfg.postprop_finalize_source = ...
            postprop_finalize_source;
        end_snapshot_runtime_cfg = ...
            restart_pipeline_utils.expand_postprop_finalize_source_local( ...
                end_snapshot_runtime_cfg);
        try
            [end_snapshot_write_state, run_warn_state] = ...
                restart_pipeline_utils.finalize_end_snapshot_local( ...
                    end_snapshot_runtime_cfg, postprocess_diag_state, ...
                    run_meta, run_warn_state);
        catch me_end_snapshot_only
            end_snapshot_write_state = ...
                restart_pipeline_utils.build_failed_end_snapshot_write_state( ...
                    true, 'end_snapshot_failed', ...
                    'CerUPP:EndSnapshotBuildFailed', ...
                    me_end_snapshot_only.message);
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'end', ...
                'end_snapshot_build_failed', ...
                'CerUPP:EndSnapshotBuildFailed', ...
                ['Could not prepare the optional end snapshot after propagation ', ...
                 'finished. Skipping that save path and continuing with the ', ...
                 'final status pass. Error: %s'], ...
                me_end_snapshot_only.message);
        end
        end_snapshot_attempted_postprop = end_snapshot_write_state.attempted;
        end_snapshot_save_ok = end_snapshot_write_state.ok;
    end

    if isstruct(postprocess_runtime_state) && ...
            ~isempty(fieldnames(postprocess_runtime_state)) && ...
            isstruct(postprocess_summary_state) && ...
            ~isempty(fieldnames(postprocess_summary_state))
        postprocess_final_state = struct( ...
            'runtime', postprocess_runtime_state, ...
            'summary', postprocess_summary_state);
    end

    final_full_save_ok = ...
        ~cfg.output_plan.request.save_final_full_output_flag || ...
        ~isempty(final_fullsave_build_cfg);

    section5f_state = struct( ...
        'timing', timing, ...
        'plasma_runtime_cfg', plasma_runtime_cfg, ...
        'run_meta', run_meta, ...
        'final_a_s_state_finite', final_a_s_state_finite, ...
        'final_a_f_state_finite', final_a_f_state_finite, ...
        'final_rho_state_finite', final_rho_state_finite, ...
        'final_rho_state_shape_ok', final_rho_state_shape_ok, ...
        'terminal_propagated_state', terminal_propagated_state, ...
        'terminal_output_publication_allowed', ...
            terminal_output_publication_allowed, ...
        'run_end_state', run_end_state, ...
        'postprocess_runtime_state', postprocess_runtime_state, ...
        'postprocess_diag_state', postprocess_diag_state, ...
        'postprocess_summary_state', postprocess_summary_state, ...
        'postprocess_final_state', postprocess_final_state, ...
        'final_restart_attempted_postprop', ...
            final_restart_attempted_postprop, ...
        'final_restart_save_ok', final_restart_save_ok, ...
        'final_restart_write_state', final_restart_write_state, ...
        'final_restart_fallback_error_id', ...
            final_restart_fallback_error_id, ...
        'final_restart_fallback_error_message', ...
            final_restart_fallback_error_message, ...
        'end_snapshot_write_state', end_snapshot_write_state, ...
        'end_snapshot_attempted_postprop', ...
            end_snapshot_attempted_postprop, ...
        'end_snapshot_save_ok', end_snapshot_save_ok, ...
        'final_fullsave_build_cfg', final_fullsave_build_cfg, ...
        'final_full_save_ok', final_full_save_ok, ...
        'run_warn_state', run_warn_state);
end

function terminal_state = build_terminal_propagated_state_local( ...
        final_a_s_state_finite, final_a_f_state_finite, ...
        final_rho_state_finite, final_rho_state_shape_ok, plasma_flag)
    a_s_ok = logical(final_a_s_state_finite);
    a_f_ok = logical(final_a_f_state_finite);
    rho_finite_ok = (~logical(plasma_flag)) || logical(final_rho_state_finite);
    rho_shape_ok = (~logical(plasma_flag)) || logical(final_rho_state_shape_ok);
    rho_ok = rho_finite_ok && rho_shape_ok;
    terminal_ok = a_s_ok && a_f_ok && rho_ok;
    failure_tags = {};
    if ~a_s_ok
        failure_tags{end + 1} = 'final_a_s_missing_or_nonfinite';
    end
    if ~a_f_ok
        failure_tags{end + 1} = 'final_a_f_missing_or_nonfinite';
    end
    if ~rho_finite_ok
        failure_tags{end + 1} = 'final_rho_missing_or_nonfinite';
    end
    if ~rho_shape_ok
        failure_tags{end + 1} = 'final_rho_shape_mismatch';
    end
    if terminal_ok
        failure_class = 'none';
        severity = 'none';
    else
        failure_class = 'bad_propagated_state';
        severity = 'fatal';
    end
    terminal_state = struct( ...
        'ok', terminal_ok, ...
        'success', terminal_ok, ...
        'failure_class', failure_class, ...
        'severity', severity, ...
        'a_s_ok', a_s_ok, ...
        'a_f_ok', a_f_ok, ...
        'rho_ok', rho_ok, ...
        'rho_finite_ok', rho_finite_ok, ...
        'rho_shape_ok', rho_shape_ok, ...
        'failure_tags', {failure_tags});
end
