classdef medium_model
%MEDIUM_MODEL Owns the internal medium-family/material-property resolution.
% cerupp.m owns the internal built-in medium-family default, the explicit
% built-in medium_cfg defaults, the near-zero Kerr-disable exception, and
% the built-in Air placeholder constants together with the built-in YAG
% material defaults.
% This file keeps the medium_cfg parsing, validation, and report-note
% machinery together with the medium-property resolver.
% Called mainly from driver_setup_support.m.

    methods (Static)
        function require_known_cfg_fields(source_struct)
        % Reject unknown/removed cfg fields before the medium-model resolver proceeds.

            medium_model_require_known_fields_local(source_struct, 'cfg');
        end

        function parsed_cfg = parse_medium_cfg(source_struct)
        % Parse the validated medium_cfg field family with shared setup validators.

            parsed_cfg = medium_model_parse_medium_cfg_local(source_struct);
        end

        function [medium_spec, run_warn_state] = resolve_medium_model_spec( ...
                medium_cfg, run_warn_state, require_finite_tau_c_flag, ...
                selected_builtin_medium_family, built_in_air_placeholder_defaults)
        % Resolve validated medium_cfg into the explicit medium-property spec.

            if nargin < 1 || isempty(medium_cfg)
                medium_cfg = struct();
            end
            if ~isstruct(medium_cfg)
                error('CerUPP:InvalidMediumConfig', ...
                    'medium_cfg must be a struct; got %s.', class(medium_cfg));
            end
            if nargin < 2 || ~isstruct(run_warn_state)
                run_warn_state = struct();
            end
            if nargin < 3 || isempty(require_finite_tau_c_flag)
                require_finite_tau_c_flag = true;
            end
            if nargin < 4 || isempty(selected_builtin_medium_family)
                error('CerUPP:InvalidMediumConfig', ...
                    'resolve_medium_model_spec requires the driver-derived built-in medium family.');
            end
            require_finite_tau_c_flag = struct_utils.normalize_bool_scalar( ...
                require_finite_tau_c_flag, ...
                'require_finite_tau_c_flag', ...
                'CerUPP:InvalidMediumConfig');
            run_warn_state = struct_utils.ensure_warned_keys_map(run_warn_state);
            selected_builtin_medium_family = upper(strtrim(char(string(selected_builtin_medium_family))));
            if ~ismember(selected_builtin_medium_family, {'YAG', 'AIR'})
                error('CerUPP:InvalidMediumConfig', ...
                    'selected_builtin_medium_family must be ''YAG'' or ''AIR''; got ''%s''.', ...
                    selected_builtin_medium_family);
            end
            if nargin < 5 || ~isstruct(built_in_air_placeholder_defaults)
                error('CerUPP:InvalidMediumConfig', ...
                    'built_in_air_placeholder_defaults must be the driver-owned Air placeholder defaults struct.');
            end

            medium_model.require_known_cfg_fields(medium_cfg);

            medium_name = struct_utils.opt_struct_field(medium_cfg, 'name', '');
            if isstring(medium_name) && isscalar(medium_name)
                medium_name = char(medium_name);
            end
            if ~ischar(medium_name)
                error('CerUPP:InvalidMediumConfig', ...
                    'medium_cfg.name must be char/string; got %s.', class(medium_name));
            end
            medium_name = upper(strtrim(medium_name));
            if isempty(medium_name)
                error('CerUPP:InvalidMediumConfig', ...
                    'medium_cfg.name must be explicitly provided (''YAG'' or ''Air'').');
            end
            if ~strcmp(selected_builtin_medium_family, medium_name)
                error('CerUPP:InvalidMediumConfig', ...
                    ['The driver-derived built-in medium family is ''%s'', but medium_cfg.name resolved to ''%s''. ', ...
                     'Keep selected_builtin_medium_family and medium_cfg.name aligned.'], ...
                    selected_builtin_medium_family, ...
                    medium_name);
            end

            air_placeholder_defaults_overridden = false;
            air_placeholder_label = 'built-in Air placeholder path';

            parsed_cfg = medium_model.parse_medium_cfg(medium_cfg);
            ui_j = parsed_cfg.ui_j;
            keldysh_gap_j = parsed_cfg.keldysh_gap_j;
            keldysh_matched_depletion_j = parsed_cfg.keldysh_matched_depletion_j;
            rho_nt_m3 = parsed_cfg.rho_nt_m3;
            rho_nt_keldysh_norm_m3 = parsed_cfg.rho_nt_keldysh_norm_m3;
            k_power_vec = parsed_cfg.k_power_vec;
            sigma_k_vec = parsed_cfg.sigma_k_vec;
            tau_c = parsed_cfg.tau_c;
            alpha_recombine_m3_per_s = parsed_cfg.alpha_recombine_m3_per_s;
            keldysh_electron_effective_mass_over_me_solid = ...
                parsed_cfg.keldysh_electron_effective_mass_over_me_solid;
            keldysh_hole_effective_mass_over_me_solid = ...
                parsed_cfg.keldysh_hole_effective_mass_over_me_solid;
            keldysh_mred_over_me_solid = parsed_cfg.keldysh_mred_over_me_solid;
            plasma_m_over_me = parsed_cfg.plasma_m_over_me;
            plasma_mass_model = parsed_cfg.plasma_mass_model;
            rho_density_interpretation = parsed_cfg.rho_density_interpretation;
            split_threshold_phenomenology_active = ...
                medium_model_values_differ_local(ui_j, keldysh_gap_j) || ...
                medium_model_values_differ_local(ui_j, keldysh_matched_depletion_j) || ...
                medium_model_values_differ_local(keldysh_gap_j, keldysh_matched_depletion_j);
            threshold_energy_contract = 'locked_single_threshold';
            if split_threshold_phenomenology_active
                threshold_energy_contract = 'independent_threshold_inputs';
                qe_abs = 1.602176634e-19;
                run_warn_state = medium_model_emit_setup_warning_local( ...
                    run_warn_state, ...
                    'setup_split_threshold_phenomenology', ...
                    'CerUPP:MediumConfig:SplitThresholdPhenomenology', ...
                    ['Ui_pair=%.4f eV, Keldysh_Eg_eff=%.4f eV, and Udep_matched=%.4f eV differ. ', ...
                     'These are three separate user knobs used in different places in the plasma/NLA model. ', ...
                     'Keep them equal unless you intentionally want different values.'], ...
                    double(ui_j) / qe_abs, double(keldysh_gap_j) / qe_abs, ...
                    double(keldysh_matched_depletion_j) / qe_abs);
            end
            keldysh_convention_autoselect_used = true;
            switch medium_name
                case 'YAG'
                    % When both host pair masses are present, they are the
                    % authoritative owner of the live Keldysh reduced mass.
                    % This public surface no longer accepts a separate
                    % scalar reduced-mass override.

                    pair_mass_mred_over_me = medium_model_solid_reduced_mass_over_me_local( ...
                        keldysh_electron_effective_mass_over_me_solid, ...
                        keldysh_hole_effective_mass_over_me_solid);
                    if isfinite(pair_mass_mred_over_me)
                        keldysh_mred_over_me_solid = double(pair_mass_mred_over_me);
                    elseif ~isfinite(double(keldysh_mred_over_me_solid))
                        error('CerUPP:InvalidMediumConfig', ...
                            ['Provide both solid host pair masses ', ...
                             '(medium_cfg.keldysh_electron_effective_mass_over_me_solid and ', ...
                             'medium_cfg.keldysh_hole_effective_mass_over_me_solid) for the YAG ', ...
                             'Keldysh path.']);
                    end
                case 'AIR'
                    air_defaults = built_in_air_placeholder_defaults;
                    air_placeholder_defaults_overridden = medium_model_air_placeholder_defaults_overridden_local( ...
                        parsed_cfg, air_defaults);
                    if air_placeholder_defaults_overridden
                        air_placeholder_label = 'built-in Air placeholder path (defaults overridden)';
                        run_warn_state = medium_model_emit_setup_warning_local( ...
                            run_warn_state, ...
                            'setup_air_placeholder_defaults_overridden', ...
                            'CerUPP:MediumConfig:AirPlaceholderDefaultsOverridden', ...
                            ['medium.name=Air uses the built-in Air placeholder path plus one default static-MPI placeholder set here. ', ...
                             'One or more active placeholder fields (Ui, rho_nt, K, sigma_K, tau_c, alpha_recombine, plasma_m_over_me) differ ', ...
                             'from the default values, ', ...
                             'so runtime reporting will mark this as "%s".'], ...
                            air_placeholder_label);
                    else
                        run_warn_state = medium_model_emit_setup_warning_local( ...
                            run_warn_state, ...
                            'setup_air_placeholder_model', ...
                            'CerUPP:MediumConfig:AirPlaceholderModel', ...
                            ['medium.name=Air uses one default static-MPI placeholder set on the built-in Air placeholder path here ', ...
                             '(single-rho reservoir model, not a resolved gas-ionization or pure-gas density model).']);
                    end
                otherwise
                    error('CerUPP:InvalidMediumConfig', ...
                        'Unsupported medium_cfg.name="%s". Supported values: ''YAG'', ''Air''.', medium_name);
            end

            medium_spec = struct( ...
                'name', char(medium_name), ...
                'air_placeholder_label', char(air_placeholder_label), ...
                'air_placeholder_defaults_overridden', logical(air_placeholder_defaults_overridden), ...
                'ui_j', double(ui_j), ...
                'keldysh_gap_j', double(keldysh_gap_j), ...
                'keldysh_matched_depletion_j', double(keldysh_matched_depletion_j), ...
                'split_threshold_phenomenology_active', logical(split_threshold_phenomenology_active), ...
                'threshold_energy_contract', char(threshold_energy_contract), ...
                'rho_nt_m3', double(rho_nt_m3), ...
                'rho_nt_keldysh_norm_m3', double(rho_nt_keldysh_norm_m3), ...
                'k_power_vec', reshape(double(k_power_vec), 1, []), ...
                'sigma_k_vec', reshape(double(sigma_k_vec), 1, []), ...
                'tau_c', double(tau_c), ...
                'alpha_recombine_m3_per_s', double(alpha_recombine_m3_per_s), ...
                'keldysh_convention_autoselect_used', logical(keldysh_convention_autoselect_used), ...
                'keldysh_electron_effective_mass_over_me_solid', ...
                    double(keldysh_electron_effective_mass_over_me_solid), ...
                'keldysh_hole_effective_mass_over_me_solid', ...
                    double(keldysh_hole_effective_mass_over_me_solid), ...
                'keldysh_mred_over_me_solid', double(keldysh_mred_over_me_solid), ...
                'plasma_m_over_me', double(plasma_m_over_me), ...
                'plasma_mass_model', char(plasma_mass_model), ...
                'rho_density_interpretation', char(rho_density_interpretation));
        end

        function varargout = build_effective_medium_report_specs(varargin)
            [varargout{1:nargout}] = medium_model_build_effective_medium_report_specs_local(varargin{:});
        end
    end
end

function run_warn_state = medium_model_emit_setup_warning_local( ...
        run_warn_state, warn_key, canon_id, msg_fmt, varargin)
% Emit one deduplicated setup-phase warning through the shared warning ledger owner.

    run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
        run_warn_state, run_warn_state_utils.phase_setup(), warn_key, canon_id, msg_fmt, varargin{:});
end

function report_specs = medium_model_build_effective_medium_report_specs_local(medium_spec)
% Build the medium report notes so one helper controls the built-in Air placeholder wording.

    report_specs = {};
    medium_name = upper(strtrim(char(string(struct_utils.opt_struct_field(medium_spec, 'name', '')))));
    if ~strcmp(medium_name, 'AIR')
        return;
    end

    air_placeholder_label = char(string(struct_utils.opt_struct_field( ...
        medium_spec, 'air_placeholder_label', 'built-in Air placeholder path')));
    air_placeholder_defaults_overridden = logical(struct_utils.opt_struct_field( ...
        medium_spec, 'air_placeholder_defaults_overridden', false));

    report_specs = {
        ['Air mode here retargets the optical propagation path to the ', ...
         'built-in Air placeholder path (homogeneous Sellmeier_Air optical path and zero guiding residual; Kerr support follows the configured nonlinear support mask).\n'], {};
        ['NOTE: medium=Air uses one default static-MPI placeholder set for Ui/rho_nt/K/sigma_K ', ...
         'in this version, not a resolved gas-ionization or pure-gas density model.\n'], {}
    };
    if air_placeholder_defaults_overridden
        report_specs(end+1, :) = { ...
            ['The active Air placeholder/source/transport fields ', ...
             '(Ui/rho_nt/K/sigma_K/tau_c/alpha_recombine/plasma_m_over_me) ', ...
             'were overridden from the built-in %s defaults.\n'], ...
            {air_placeholder_label}};
    end
end

function overridden = medium_model_air_placeholder_defaults_overridden_local(parsed_cfg, air_defaults)
% Detect whether active Air ionization placeholders differ from built-in generic defaults.

    overridden = false;
    compare_fields = {'ui_j', 'rho_nt_m3', 'k_power_vec', 'sigma_k_vec', ...
        'tau_c', 'alpha_recombine_m3_per_s', 'plasma_m_over_me'};
    for ii = 1:numel(compare_fields)
        field_name = compare_fields{ii};
        if medium_model_values_differ_local(parsed_cfg.(field_name), air_defaults.(field_name))
            overridden = true;
            return;
        end
    end
end

function differs = medium_model_values_differ_local(actual_value, default_value)
% Relative-tolerance comparison used for Air placeholder-default reporting.

    actual_value = double(actual_value(:));
    default_value = double(default_value(:));
    if numel(actual_value) ~= numel(default_value)
        differs = true;
        return;
    end
    if any(~isfinite(actual_value)) || any(~isfinite(default_value))
        differs = ~isequaln(actual_value, default_value);
        return;
    end
    rel_tol = struct_utils.cerupp_numeric_threshold('rel_tol_tight');
    scale = max([abs(actual_value), abs(default_value), repmat(realmin('double'), size(actual_value))], [], 2);
    differs = any(abs(actual_value - default_value) > rel_tol .* scale);
end

function label_txt = medium_model_default_plasma_mass_model_local(medium_name)
% Return the built-in label naming the current Keldysh/Drude mass convention.

    medium_name = upper(strtrim(char(string(medium_name))));
    switch medium_name
        case 'AIR'
            label_txt = 'Air placeholder bare-electron Drude surrogate';
        case 'YAG'
            label_txt = 'host-pair Keldysh + bare-electron Drude surrogate';
        otherwise
            label_txt = 'single-mass Drude surrogate';
    end
end

function label_txt = medium_model_default_rho_density_interpretation_local(medium_name)
% Return the built-in rho interpretation label used by setup and saved metadata.

    medium_name = upper(strtrim(char(string(medium_name))));
    switch medium_name
        case 'AIR'
            label_txt = 'free-electron density (placeholder single-mass Drude surrogate)';
        otherwise
            label_txt = 'free-electron density (single-mass Drude surrogate)';
    end
end

function mred_over_me = medium_model_solid_reduced_mass_over_me_local( ...
        electron_mass_over_me, hole_mass_over_me)
% Derive the solid-state reduced mass directly from the host pair masses.
% The live formula is m_red = (m_e* m_h*) / (m_e* + m_h*).

    mred_over_me = NaN;
    electron_mass_over_me = double(electron_mass_over_me);
    hole_mass_over_me = double(hole_mass_over_me);
    if ~isfinite(electron_mass_over_me) || ~isfinite(hole_mass_over_me)
        return;
    end
    mred_over_me = ...
        (electron_mass_over_me * hole_mass_over_me) / ...
        (electron_mass_over_me + hole_mass_over_me);
end

function medium_model_require_known_fields_local(source_struct, mode_tag)
% Reject unknown/removed fields on the cfg surface before numeric validation.

    if nargin < 1 || ~isstruct(source_struct)
        return;
    end
    mode_tag = lower(strtrim(char(string(mode_tag))));
    if ~strcmp(mode_tag, 'cfg')
        error('CerUPP:InvalidMediumConfig', ...
            'Unknown medium field-parse mode "%s".', mode_tag);
    end

    if isfield(source_struct, 'keldysh_mred_over_me_solid')
        error('CerUPP:MediumCfgRemovedField', ...
            ['medium_cfg.keldysh_mred_over_me_solid is not a supported public input here. ', ...
             'The live YAG Keldysh reduced mass is derived as m_red = (m_e* m_h*) / (m_e* + m_h*) ', ...
             'from medium_cfg.keldysh_electron_effective_mass_over_me_solid and medium_cfg.', ...
             'keldysh_hole_effective_mass_over_me_solid; edit those pair masses instead.']);
    end
    if isfield(source_struct, 'allow_split_threshold_phenomenology')
        error('CerUPP:MediumCfgRemovedField', ...
            ['medium_cfg.allow_split_threshold_phenomenology is no longer a live setup flag here. ', ...
             'There is no separate mode flag for unequal threshold-energy inputs. ', ...
             'CerUPP uses medium_cfg.ui_j, medium_cfg.keldysh_gap_j, and ', ...
             'medium_cfg.keldysh_matched_depletion_j directly and warns when they differ.']);
    end
    if isfield(source_struct, 'rho_nt_keldysh_norm_m3')
        error('CerUPP:MediumCfgRemovedField', ...
            ['medium_cfg.rho_nt_keldysh_norm_m3 is no longer a public medium input here. ', ...
             'The public medium path ties that normalization to medium_cfg.rho_nt_m3, ', ...
             'so change medium_cfg.rho_nt_m3 when you want to change the public normalization density.']);
    end
    allowed_fields = medium_model_known_fields_local();
    unknown_fields = setdiff(fieldnames(source_struct).', allowed_fields);
    if ~isempty(unknown_fields)
        error('CerUPP:MediumCfgUnknownField', ...
            'Unknown medium_cfg field(s): %s', strjoin(unknown_fields, ', '));
    end
end

function parsed_cfg = medium_model_parse_medium_cfg_local(source_struct)
% Parse the validated cfg field family with explicit defaults and validators.

    medium_model_require_known_fields_local(source_struct, 'cfg');
    medium_name_for_defaults = upper(strtrim(char(string(struct_utils.opt_struct_field( ...
        source_struct, 'name', 'YAG')))));
    parsed_cfg = struct( ...
        'ui_j', medium_model_validate_medium_scalar_local( ...
            struct_utils.opt_struct_field(source_struct, 'ui_j', NaN), ...
            'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.ui_j must be a finite real scalar > 0 [J].', ...
            0, false, false), ...
        'keldysh_gap_j', medium_model_validate_medium_scalar_local( ...
            struct_utils.opt_struct_field(source_struct, 'keldysh_gap_j', ...
                struct_utils.opt_struct_field(source_struct, 'ui_j', NaN)), ...
            'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.keldysh_gap_j must be a finite real scalar > 0 [J].', ...
            0, false, false), ...
        'keldysh_matched_depletion_j', medium_model_validate_medium_scalar_local( ...
            struct_utils.opt_struct_field(source_struct, 'keldysh_matched_depletion_j', ...
                struct_utils.opt_struct_field(source_struct, 'ui_j', NaN)), ...
            'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.keldysh_matched_depletion_j must be a finite real scalar > 0 [J].', ...
            0, false, false), ...
        'rho_nt_m3', medium_model_validate_medium_scalar_local( ...
            struct_utils.opt_struct_field(source_struct, 'rho_nt_m3', NaN), ...
            'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.rho_nt_m3 must be a finite real scalar > 0 [m^-3].', ...
            0, false, false), ...
        'k_power_vec', medium_model_validate_medium_row_vector_min_local( ...
            struct_utils.opt_struct_field(source_struct, 'k_power_vec', []), ...
            0, 'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.k_power_vec must be a finite nonnegative numeric vector.'), ...
        'sigma_k_vec', medium_model_validate_medium_row_vector_min_local( ...
            struct_utils.opt_struct_field(source_struct, 'sigma_k_vec', []), ...
            0, 'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.sigma_k_vec must be a finite nonnegative numeric vector.'), ...
        'tau_c', medium_model_validate_medium_scalar_local( ...
            struct_utils.opt_struct_field(source_struct, 'tau_c', NaN), ...
            'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.tau_c must be a finite real scalar >= 0 [s] when explicitly provided.', ...
            0, true, true), ...
        'alpha_recombine_m3_per_s', medium_model_validate_medium_scalar_local( ...
            struct_utils.opt_struct_field(source_struct, 'alpha_recombine_m3_per_s', NaN), ...
            'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.alpha_recombine_m3_per_s must be a finite real scalar >= 0 [m^3/s].', ...
            0, true, false), ...
        'keldysh_electron_effective_mass_over_me_solid', medium_model_validate_medium_scalar_local( ...
            struct_utils.opt_struct_field(source_struct, 'keldysh_electron_effective_mass_over_me_solid', NaN), ...
            'CerUPP:InvalidMediumConfig', ...
            ['medium_cfg.keldysh_electron_effective_mass_over_me_solid must be a finite real scalar > 0 ', ...
             'when explicitly provided.'], ...
            0, false, true), ...
        'keldysh_hole_effective_mass_over_me_solid', medium_model_validate_medium_scalar_local( ...
            struct_utils.opt_struct_field(source_struct, 'keldysh_hole_effective_mass_over_me_solid', NaN), ...
            'CerUPP:InvalidMediumConfig', ...
            ['medium_cfg.keldysh_hole_effective_mass_over_me_solid must be a finite real scalar > 0 ', ...
             'when explicitly provided.'], ...
            0, false, true), ...
        'keldysh_mred_over_me_solid', NaN, ...
        'plasma_m_over_me', medium_model_validate_medium_scalar_local( ...
            struct_utils.opt_struct_field(source_struct, 'plasma_m_over_me', NaN), ...
            'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.plasma_m_over_me must be a finite real scalar > 0.', ...
            0, false, false), ...
        'plasma_mass_model', medium_model_validate_medium_text_local( ...
            struct_utils.opt_struct_field(source_struct, 'plasma_mass_model', ...
                medium_model_default_plasma_mass_model_local(medium_name_for_defaults)), ...
            'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.plasma_mass_model must be a nonempty char/string scalar.'), ...
        'rho_density_interpretation', medium_model_validate_medium_text_local( ...
            struct_utils.opt_struct_field(source_struct, 'rho_density_interpretation', ...
                medium_model_default_rho_density_interpretation_local(medium_name_for_defaults)), ...
            'CerUPP:InvalidMediumConfig', ...
            'medium_cfg.rho_density_interpretation must be a nonempty char/string scalar.'));
    if numel(parsed_cfg.k_power_vec) ~= numel(parsed_cfg.sigma_k_vec)
        error('CerUPP:InvalidMediumConfig', ...
            'medium_cfg.k_power_vec and medium_cfg.sigma_k_vec must have equal lengths.');
    end
    % Keep the public medium surface tied to rho_nt_m3 even though deeper
    % runtime and plotting code still carries the paired field name.
    parsed_cfg.rho_nt_keldysh_norm_m3 = parsed_cfg.rho_nt_m3;
end

function allowed_fields = medium_model_known_fields_local()
% Canonical allow-list for medium_cfg.

    allowed_fields = { ...
        'name', 'ui_j', 'keldysh_gap_j', 'keldysh_matched_depletion_j', ...
        'rho_nt_m3', ...
        'k_power_vec', 'sigma_k_vec', 'tau_c', ...
        'alpha_recombine_m3_per_s', ...
        'keldysh_electron_effective_mass_over_me_solid', ...
        'keldysh_hole_effective_mass_over_me_solid', ...
        'plasma_m_over_me', ...
        'plasma_mass_model', 'rho_density_interpretation'};
end

function v = medium_model_validate_medium_scalar_local( ...
        value_in, err_id, err_msg, lower_bound, allow_equal_lower_bound, allow_nan)
% Validate scalar medium parameters with shared lower-bound and NaN policy.

    if nargin < 4 || isempty(lower_bound)
        lower_bound = 0;
    end
    if nargin < 5 || isempty(allow_equal_lower_bound)
        allow_equal_lower_bound = false;
    end
    if nargin < 6 || isempty(allow_nan)
        allow_nan = false;
    end
    v = double(value_in);
    if ~isscalar(v) || ~isreal(v)
        error(err_id, '%s', err_msg);
    end
    if isnan(v)
        if allow_nan
            return;
        end
        error(err_id, '%s', err_msg);
    end
    violates_lower_bound = (v < lower_bound) || ...
        (~allow_equal_lower_bound && (v == lower_bound));
    if ~isfinite(v) || violates_lower_bound
        error(err_id, '%s', err_msg);
    end
end

function value_out = medium_model_validate_medium_text_local(value_in, err_id, err_msg)
% Validate one nonempty char/string scalar medium label field.

    if isstring(value_in)
        if ~isscalar(value_in)
            error(err_id, '%s', err_msg);
        end
        value_out = char(value_in);
    elseif ischar(value_in)
        if ~isrow(value_in)
            error(err_id, '%s', err_msg);
        end
        value_out = value_in;
    else
        error(err_id, '%s', err_msg);
    end
    value_out = strtrim(char(value_out));
    if isempty(value_out)
        error(err_id, '%s', err_msg);
    end
end

function v = medium_model_validate_medium_row_vector_min_local(value_in, min_value, err_id, err_msg)
% Validate a finite row-vector medium parameter with a minimum entry bound.
% Keep [] legal here so dynamic-Keldysh paths can leave static OFI
% coefficient vectors unset until a later static branch actually needs them.

    v = reshape(double(value_in), 1, []);
    if isempty(v)
        return;
    end
    if ~isreal(v) || any(~isfinite(v(:))) || any(v(:) < min_value)
        error(err_id, '%s', err_msg);
    end
end
