classdef run_output_utils
%RUN_OUTPUT_UTILS Startup run-output path and status/pointer lifecycle helpers.
% Purpose:
% - Own run-output collision policy, path resolution, and startup mkdir/status
%   side effects separately from checkpoint/fullsave payload policy.
% - Keep artifact-path ownership and run-status opening close to the output
%   tree startup contract used by driver setup.

    methods (Static)
        function names = artifact_names()
        % Canonical run-status and pointer filenames for the run-output tree.

            names = struct( ...
                'run_status_name', 'run_status.json', ...
                'current_run_pointer_name', 'current_run_id.txt', ...
                'latest_successful_run_pointer_name', 'latest_successful_run_id.txt', ...
                'latest_propagation_complete_run_pointer_name', ...
                    'latest_propagation_complete_run_id.txt', ...
                'latest_fully_packaged_run_pointer_name', ...
                    'latest_fully_packaged_run_id.txt');
        end

        function policy = default_run_output_startup_policy()
        % Visible startup defaults for run-output collision handling.

            policy = struct( ...
                'append_timestamp_to_run_id', false, ...
                'archive_existing_run_output_root', false, ...
                'auto_timestamp_on_run_output_collision', true);
        end

        function [run_output_ctx, run_warn_state] = resolve_run_output_paths(cfg, run_warn_state)
        % Resolve startup artifact paths and emit setup-stage run-output reporting.

            [cfg, run_warn_state] = run_output_utils.normalize_policy_inputs_local(cfg, run_warn_state);
            output_root = struct_utils.opt_struct_field(cfg, 'output_root', '');
            driver_root = struct_utils.opt_struct_field(cfg, 'driver_root', '');
            run_tag = struct_utils.opt_struct_field(cfg, 'run_tag', 'default');
            startup_policy_in = struct_utils.opt_struct_field(cfg, 'output_startup_policy', struct());
            output_root_resolved = run_output_utils.resolve_output_root_local(output_root, driver_root);
            [run_tag, run_warn_state] = run_output_utils.sanitize_run_tag_local(run_tag, run_warn_state);
            startup_policy = run_output_utils.normalize_run_output_startup_policy_local(startup_policy_in);
            [artifact_paths, startup_action, auto_timestamped_run_output_root, run_warn_state] = ...
                run_output_utils.resolve_run_output_artifact_paths_local( ...
                    output_root_resolved, run_tag, startup_policy, run_warn_state);
            [run_warn_state, ~] = run_warn_state_utils.emit_info_with_phase( ...
                run_warn_state, run_warn_state_utils.phase_setup(), 'resolved_run_output_root', ...
                'Resolved run_output_root: %s', artifact_paths.run_output_root);

            run_output_ctx = struct( ...
                'output_root_resolved', output_root_resolved, ...
                'output_startup_policy', startup_policy, ...
                'append_timestamp_to_run_id', logical(startup_policy.append_timestamp_to_run_id), ...
                'archive_existing_run_output_root', logical(startup_policy.archive_existing_run_output_root), ...
                'auto_timestamp_on_run_output_collision', logical(startup_policy.auto_timestamp_on_run_output_collision), ...
                'auto_timestamped_run_output_root', logical(auto_timestamped_run_output_root), ...
                'startup_action', char(string(startup_action)), ...
                'artifact_paths', artifact_paths);
        end

        function [run_status_ctx, run_warn_state] = initialize_run_output_artifacts(cfg, run_warn_state)
        % Perform startup mkdir/status/pointer side effects.

            [cfg, run_warn_state] = run_output_utils.normalize_policy_inputs_local(cfg, run_warn_state);
            run_output_ctx = struct_utils.req_struct_field( ...
                cfg, 'run_output_ctx', 'run_output_utils.initialize_run_output_artifacts');
            output_cfg = struct_utils.opt_struct_field(cfg, 'output_cfg', struct());
            run_status_ctx = struct_utils.opt_struct_field(cfg, 'run_status_ctx', struct());
            restart_compat_version = double(struct_utils.opt_struct_field( ...
                cfg, 'restart_compat_version', NaN));
            release_version = char(string(struct_utils.opt_struct_field( ...
                cfg, 'release_version', '')));
            curr_cerupp_version = char(string(struct_utils.opt_struct_field( ...
                cfg, 'curr_cerupp_version', '')));
            if ~isstruct(output_cfg)
                error('run_output_utils:InvalidOutputCfg', ...
                    'cfg.output_cfg must be a struct or [].');
            end
            if ~isstruct(run_status_ctx)
                run_status_ctx = struct();
            end
            if ~(isstruct(run_output_ctx) && isscalar(run_output_ctx))
                error('run_output_utils:InvalidRunOutputCtx', ...
                    'cfg.run_output_ctx must be a scalar struct.');
            end

            artifact_paths = struct_utils.req_struct_field( ...
                run_output_ctx, 'artifact_paths', ...
                'run_output_utils.initialize_run_output_artifacts');
            startup_action = char(string(struct_utils.req_struct_field( ...
                run_output_ctx, 'startup_action', ...
                'run_output_utils.initialize_run_output_artifacts')));

            run_output_utils.ensure_target_dir_ready_local(artifact_paths.run_bucket);
            [run_warn_state, archive_path] = run_output_utils.materialize_run_output_root_local( ...
                artifact_paths.run_bucket, artifact_paths.run_output_root, artifact_paths.run_id, ...
                startup_action, run_warn_state);
            if strcmp(startup_action, 'archive_existing_run_output_root')
                run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                    run_warn_state, run_warn_state_utils.phase_setup(), ...
                    'setup_run_id_archived_existing_output', ...
                    'CerUPP:RunIdExistsArchived', ...
                    ['run_output_root already existed for run_id="%s". ' ...
                     'Renamed previous run directory to "%s" and created a fresh run directory.'], ...
                    artifact_paths.run_id, archive_path);
            end

            need_plot_output_root = logical(struct_utils.opt_struct_field( ...
                output_cfg, 'save_outputs_as_fig', false)) || ...
                logical(struct_utils.opt_struct_field(output_cfg, 'save_outputs_as_png', false));
            need_csv_output_root = logical(struct_utils.opt_struct_field( ...
                output_cfg, 'export_csv_debug_flag', false));
            need_checkpoint_output_root = logical(struct_utils.opt_struct_field( ...
                output_cfg, 'intermediate_saves', false)) || ...
                logical(struct_utils.opt_struct_field(output_cfg, 'save_final_restart_checkpoint_flag', false)) || ...
                logical(struct_utils.opt_struct_field(output_cfg, 'checkpoint_full_save_flag', false));
            if need_plot_output_root && ~exist(artifact_paths.plots.root, 'dir')
                run_output_utils.ensure_target_dir_ready_local(artifact_paths.plots.root);
            end
            if ~exist(artifact_paths.csv.root, 'dir')
                run_output_utils.ensure_target_dir_ready_local(artifact_paths.csv.root);
            end
            if need_checkpoint_output_root && ~exist(artifact_paths.checkpoints.root, 'dir')
                run_output_utils.ensure_target_dir_ready_local(artifact_paths.checkpoints.root);
            end

            run_status_ctx.artifact_paths = artifact_paths;
            run_status_ctx.enabled = logical(struct_utils.opt_struct_field( ...
                output_cfg, 'write_run_status_flag', false));
            run_status_ctx.write_current_pointer = logical(struct_utils.opt_struct_field( ...
                output_cfg, 'write_current_run_pointer_flag', false));
            if run_status_ctx.enabled || run_status_ctx.write_current_pointer
                run_status_ctx.started_at_utc = checkpoint_utils.current_iso_utc_timestamp();
            end
            [run_warn_state, run_status_ctx] = run_output_utils.open_run_attempt_status( ...
                struct( ...
                    'run_status_ctx', run_status_ctx, ...
                    'restart_compat_version', restart_compat_version, ...
                    'release_version', release_version, ...
                    'curr_cerupp_version', curr_cerupp_version, ...
                    'pointer_phase_tag', run_warn_state_utils.phase_setup(), ...
                    'pointer_warn_key', 'setup_current_run_pointer_write_failed', ...
                    'pointer_warn_id', 'CerUPP:RunStatus:CurrentRunPointerWriteFailed', ...
                    'pointer_failure_tag', 'current_run_pointer', ...
                    'status_phase_tag', run_warn_state_utils.phase_setup(), ...
                    'status_warn_key', 'setup_run_status_write_failed', ...
                    'status_warn_id', 'CerUPP:RunStatus:RunStatusSetupWriteFailed', ...
                    'status_failure_tag', 'run_status_setup_write'), ...
                run_warn_state);
        end

        function [run_warn_state, run_status_ctx] = open_run_attempt_status(cfg, run_warn_state)
        % Publish setup-time launch status and current-run pointer.

            [cfg, run_warn_state] = run_output_utils.normalize_policy_inputs_local(cfg, run_warn_state);
            run_status_ctx = struct_utils.opt_struct_field(cfg, 'run_status_ctx', struct());
            if ~isstruct(run_status_ctx)
                run_status_ctx = struct();
                return;
            end
            [run_id, run_output_root] = run_output_utils.resolve_run_status_identity_local( ...
                run_status_ctx);
            restart_compat_version = double(struct_utils.opt_struct_field( ...
                cfg, 'restart_compat_version', NaN));
            release_version = char(string(struct_utils.opt_struct_field(cfg, 'release_version', '')));
            curr_cerupp_version = char(string(struct_utils.opt_struct_field( ...
                cfg, 'curr_cerupp_version', '')));
            phase_specs = run_output_utils.build_run_status_phase_specs_local('setup');
            [run_warn_state, ~] = run_output_utils.apply_current_run_pointer_local( ...
                run_status_ctx, struct( ...
                    'run_id', run_id, ...
                    'phase_tag', struct_utils.opt_struct_field(cfg, 'pointer_phase_tag', phase_specs.pointer_phase_tag), ...
                    'warn_key', struct_utils.opt_struct_field(cfg, 'pointer_warn_key', phase_specs.pointer_warn_key), ...
                    'warn_id', struct_utils.opt_struct_field(cfg, 'pointer_warn_id', phase_specs.pointer_warn_id), ...
                    'failure_tag', struct_utils.opt_struct_field(cfg, 'pointer_failure_tag', phase_specs.pointer_failure_tag)), ...
                'write', run_warn_state);
            status_payload = checkpoint_utils.build_run_status_payload(struct( ...
                'run_id', run_id, ...
                'run_output_root', run_output_root, ...
                'started_at_utc', struct_utils.opt_struct_field(run_status_ctx, 'started_at_utc', ''), ...
                'state_name', 'launched', ...
                'error_id', '', ...
                'error_message', '', ...
                'restart_compat_version', restart_compat_version, ...
                'release_version', release_version, ...
                'curr_cerupp_version', curr_cerupp_version));
            [run_warn_state, ~] = run_output_utils.publish_run_status_payload_local( ...
                run_status_ctx, status_payload, struct( ...
                    'phase_tag', struct_utils.opt_struct_field(cfg, 'status_phase_tag', phase_specs.status_phase_tag), ...
                    'warn_key', struct_utils.opt_struct_field(cfg, 'status_warn_key', phase_specs.status_warn_key), ...
                    'warn_id', struct_utils.opt_struct_field(cfg, 'status_warn_id', phase_specs.status_warn_id), ...
                    'failure_tag', struct_utils.opt_struct_field(cfg, 'status_failure_tag', phase_specs.status_failure_tag)), ...
                run_warn_state);
        end

        function [run_warn_state, run_status_ctx] = update_run_progress_status(cfg, run_warn_state)
        % Publish a nonterminal running status with propagation progress fields.

            [cfg, run_warn_state] = run_output_utils.normalize_policy_inputs_local(cfg, run_warn_state);
            run_status_ctx = struct_utils.opt_struct_field(cfg, 'run_status_ctx', struct());
            if ~isstruct(run_status_ctx)
                run_status_ctx = struct();
                return;
            end
            if ~(isfield(run_status_ctx, 'enabled') && run_status_ctx.enabled)
                return;
            end

            [run_id, run_output_root] = run_output_utils.resolve_run_status_identity_local( ...
                run_status_ctx);
            status_extra_fields = struct_utils.opt_struct_field(cfg, 'status_extra_fields', struct());
            status_payload = checkpoint_utils.build_run_status_payload(struct( ...
                'run_id', run_id, ...
                'run_output_root', run_output_root, ...
                'started_at_utc', struct_utils.opt_struct_field(run_status_ctx, 'started_at_utc', ''), ...
                'state_name', 'running', ...
                'error_id', '', ...
                'error_message', '', ...
                'restart_compat_version', double(struct_utils.opt_struct_field( ...
                    cfg, 'restart_compat_version', NaN)), ...
                'release_version', char(string(struct_utils.opt_struct_field( ...
                    cfg, 'release_version', ''))), ...
                'curr_cerupp_version', char(string(struct_utils.opt_struct_field( ...
                    cfg, 'curr_cerupp_version', '')))));
            status_payload = run_output_utils.merge_status_extra_fields_local( ...
                status_payload, status_extra_fields);
            [run_warn_state, ~] = run_output_utils.publish_run_status_payload_local( ...
                run_status_ctx, status_payload, struct( ...
                    'phase_tag', struct_utils.opt_struct_field(cfg, 'status_phase_tag', 'propagation'), ...
                    'warn_key', struct_utils.opt_struct_field( ...
                        cfg, 'status_warn_key', 'progress_run_status_write_failed'), ...
                    'warn_id', struct_utils.opt_struct_field( ...
                        cfg, 'status_warn_id', 'CerUPP:RunStatus:ProgressRunStatusWriteFailed'), ...
                    'failure_tag', struct_utils.opt_struct_field( ...
                        cfg, 'status_failure_tag', 'run_status_progress_write')), ...
                run_warn_state);
        end

        function [run_warn_state, run_status_ctx] = finalize_run_attempt_status(cfg, run_warn_state)
        % Publish final status and retire the current-run pointer at run end.

            [cfg, run_warn_state] = run_output_utils.normalize_policy_inputs_local(cfg, run_warn_state);
            run_status_ctx = struct_utils.opt_struct_field(cfg, 'run_status_ctx', struct());
            if ~isstruct(run_status_ctx)
                run_status_ctx = struct();
                return;
            end
            attempt_state = char(string(struct_utils.opt_struct_field(cfg, 'attempt_state', 'failed')));
            error_id = char(string(struct_utils.opt_struct_field(cfg, 'error_id', '')));
            error_message = char(string(struct_utils.opt_struct_field(cfg, 'error_message', '')));
            restart_compat_version = double(struct_utils.opt_struct_field(cfg, 'restart_compat_version', NaN));
            release_version = char(string(struct_utils.opt_struct_field(cfg, 'release_version', '')));
            curr_cerupp_version = char(string(struct_utils.opt_struct_field( ...
                cfg, 'curr_cerupp_version', '')));
            status_extra_fields = struct_utils.opt_struct_field(cfg, 'status_extra_fields', struct());
            [run_id, run_output_root] = run_output_utils.resolve_run_status_identity_local( ...
                run_status_ctx);
            status_payload = checkpoint_utils.build_run_status_payload(struct( ...
                'run_id', run_id, ...
                'run_output_root', run_output_root, ...
                'started_at_utc', struct_utils.opt_struct_field(run_status_ctx, 'started_at_utc', ''), ...
                'state_name', attempt_state, ...
                'error_id', error_id, ...
                'error_message', error_message, ...
                'restart_compat_version', restart_compat_version, ...
                'release_version', release_version, ...
                'curr_cerupp_version', curr_cerupp_version));
            status_payload = run_output_utils.merge_status_extra_fields_local( ...
                status_payload, status_extra_fields);
            status_write_attempted = isfield(run_status_ctx, 'enabled') && run_status_ctx.enabled;
            [run_warn_state, status_write_ok] = run_output_utils.publish_run_status_payload_local( ...
                run_status_ctx, status_payload, struct( ...
                    'phase_tag', struct_utils.opt_struct_field(cfg, 'status_phase_tag', run_warn_state_utils.phase_end()), ...
                    'warn_key', struct_utils.opt_struct_field(cfg, 'status_warn_key', 'run_status_write_failed'), ...
                    'warn_id', struct_utils.opt_struct_field(cfg, 'status_warn_id', 'CerUPP:RunStatus:RunStatusWriteFailed'), ...
                    'failure_tag', struct_utils.opt_struct_field(cfg, 'status_failure_tag', 'run_status_final_write')), ...
                run_warn_state);
            status_write_retry_attempted = false;
            status_write_retry_ok = false;
            if logical(status_write_attempted) && ~logical(status_write_ok)
                status_write_retry_attempted = true;
                [run_warn_state, status_write_retry_ok] = ...
                    run_output_utils.publish_run_status_payload_local( ...
                        run_status_ctx, status_payload, struct( ...
                            'phase_tag', struct_utils.opt_struct_field( ...
                                cfg, 'status_phase_tag', run_warn_state_utils.phase_end()), ...
                            'warn_key', struct_utils.opt_struct_field( ...
                                cfg, 'status_warn_key', 'run_status_write_failed'), ...
                            'warn_id', struct_utils.opt_struct_field( ...
                                cfg, 'status_warn_id', 'CerUPP:RunStatus:RunStatusWriteFailed'), ...
                            'failure_tag', struct_utils.opt_struct_field( ...
                                cfg, 'status_failure_tag', 'run_status_final_write')), ...
                        run_warn_state);
                status_write_ok = logical(status_write_retry_ok);
            end
            current_pointer_status = 'skipped';
            [run_warn_state, current_pointer_status] = ...
                run_output_utils.apply_current_run_pointer_local( ...
                    run_status_ctx, struct( ...
                        'phase_tag', struct_utils.opt_struct_field( ...
                            cfg, 'pointer_phase_tag', run_warn_state_utils.phase_end()), ...
                        'warn_key', struct_utils.opt_struct_field( ...
                            cfg, 'pointer_warn_key', 'current_run_pointer_delete_failed'), ...
                        'warn_id', struct_utils.opt_struct_field( ...
                            cfg, 'pointer_warn_id', ...
                            'CerUPP:RunStatus:CurrentRunPointerDeleteFailed'), ...
                        'failure_tag', struct_utils.opt_struct_field( ...
                            cfg, 'pointer_failure_tag', 'current_run_pointer_delete')), ...
                    'delete', run_warn_state);
            current_pointer_delete_ok = any(strcmp(current_pointer_status, ...
                {'skipped', 'absent', 'deleted'}));
            status_write_post_pointer_attempted = false;
            status_write_post_pointer_ok = true;
            if logical(status_write_attempted) && logical(status_write_ok) && ...
                    any(strcmp(attempt_state, {'success', 'succeeded', 'partial_failed'})) && ...
                    ~current_pointer_delete_ok
                status_write_post_pointer_attempted = true;
                status_extra_fields_pointer_cleanup = status_extra_fields;
                status_extra_fields_pointer_cleanup.attempt_reason = ...
                    'normal_exit_with_current_pointer_cleanup_failure';
                status_payload_pointer_cleanup = checkpoint_utils.build_run_status_payload(struct( ...
                    'run_id', run_id, ...
                    'run_output_root', run_output_root, ...
                    'started_at_utc', struct_utils.opt_struct_field(run_status_ctx, 'started_at_utc', ''), ...
                    'state_name', 'partial_failed', ...
                    'error_id', 'CerUPP:RunStatus:CurrentRunPointerDeleteFailed', ...
                    'error_message', 'Could not retire current_run_id.txt at run end.', ...
                    'restart_compat_version', restart_compat_version, ...
                    'release_version', release_version, ...
                    'curr_cerupp_version', curr_cerupp_version));
                status_payload_pointer_cleanup = ...
                    run_output_utils.merge_status_extra_fields_local( ...
                        status_payload_pointer_cleanup, ...
                        status_extra_fields_pointer_cleanup);
                [run_warn_state, status_write_post_pointer_ok] = ...
                    run_output_utils.publish_run_status_payload_local( ...
                        run_status_ctx, status_payload_pointer_cleanup, struct( ...
                            'phase_tag', struct_utils.opt_struct_field( ...
                                cfg, 'status_phase_tag', run_warn_state_utils.phase_end()), ...
                            'warn_key', struct_utils.opt_struct_field( ...
                                cfg, 'status_warn_key', 'run_status_write_failed'), ...
                            'warn_id', struct_utils.opt_struct_field( ...
                                cfg, 'status_warn_id', 'CerUPP:RunStatus:RunStatusWriteFailed'), ...
                            'failure_tag', struct_utils.opt_struct_field( ...
                                cfg, 'status_failure_tag', 'run_status_final_write')), ...
                        run_warn_state);
                status_write_ok = logical(status_write_ok) && ...
                    logical(status_write_post_pointer_ok);
            end
            run_status_ctx.last_finalize_status = struct( ...
                'status_write_attempted', logical(status_write_attempted), ...
                'status_write_retry_attempted', ...
                    logical(status_write_retry_attempted), ...
                'status_write_retry_ok', ...
                    (~logical(status_write_retry_attempted)) || ...
                    logical(status_write_retry_ok), ...
                'status_write_post_pointer_attempted', ...
                    logical(status_write_post_pointer_attempted), ...
                'status_write_post_pointer_ok', ...
                    logical(status_write_post_pointer_ok), ...
                'status_write_ok', ~logical(status_write_attempted) || ...
                    logical(status_write_ok), ...
                'status_write_status', ...
                    run_output_utils.ternary_status_local( ...
                        logical(status_write_attempted), ...
                        logical(status_write_ok)), ...
                'current_pointer_delete_attempted', ...
                    ~strcmp(current_pointer_status, 'skipped'), ...
                'current_pointer_delete_ok', current_pointer_delete_ok, ...
                'current_pointer_delete_status', char(current_pointer_status));
            if ~logical(status_write_attempted) || logical(status_write_ok)
                if isfield(run_status_ctx, 'enabled')
                    run_status_ctx.enabled = false;
                end
                if isfield(run_status_ctx, 'write_current_pointer')
                    run_status_ctx.write_current_pointer = false;
                end
            end
        end

        function [run_warn_state, run_status_ctx] = ...
                republish_final_run_status_after_pointer_writes(cfg, run_warn_state)
        % Refresh final run_status.json after the late latest-pointer writes.

            [cfg, run_warn_state] = run_output_utils.normalize_policy_inputs_local(cfg, run_warn_state);
            run_status_ctx = struct_utils.opt_struct_field(cfg, 'run_status_ctx', struct());
            if ~isstruct(run_status_ctx)
                run_status_ctx = struct();
                return;
            end

            finalize_status = struct_utils.opt_struct_field( ...
                run_status_ctx, 'last_finalize_status', struct());
            if ~(isstruct(finalize_status) && isscalar(finalize_status))
                finalize_status = struct();
            end

            republish_attempted = false;
            republish_ok = true;
            if logical(struct_utils.opt_struct_field( ...
                    finalize_status, 'status_write_attempted', false)) && ...
                    logical(struct_utils.opt_struct_field( ...
                    finalize_status, 'status_write_ok', true))
                republish_attempted = true;
                [run_id, run_output_root] = run_output_utils.resolve_run_status_identity_local( ...
                    run_status_ctx);
                status_payload = checkpoint_utils.build_run_status_payload(struct( ...
                    'run_id', run_id, ...
                    'run_output_root', run_output_root, ...
                    'started_at_utc', struct_utils.opt_struct_field( ...
                        run_status_ctx, 'started_at_utc', ''), ...
                    'state_name', char(string(struct_utils.opt_struct_field( ...
                        cfg, 'attempt_state', 'failed'))), ...
                    'error_id', char(string(struct_utils.opt_struct_field( ...
                        cfg, 'error_id', ''))), ...
                    'error_message', char(string(struct_utils.opt_struct_field( ...
                        cfg, 'error_message', ''))), ...
                    'restart_compat_version', double(struct_utils.opt_struct_field( ...
                        cfg, 'restart_compat_version', NaN)), ...
                    'release_version', char(string(struct_utils.opt_struct_field( ...
                        cfg, 'release_version', ''))), ...
                    'curr_cerupp_version', char(string(struct_utils.opt_struct_field( ...
                        cfg, 'curr_cerupp_version', '')))));
                status_payload = run_output_utils.merge_status_extra_fields_local( ...
                    status_payload, struct_utils.opt_struct_field( ...
                    cfg, 'status_extra_fields', struct()));
                republish_ctx = run_status_ctx;
                republish_ctx.enabled = true;
                [run_warn_state, republish_ok] = ...
                    run_output_utils.publish_run_status_payload_local( ...
                        republish_ctx, status_payload, struct( ...
                            'phase_tag', struct_utils.opt_struct_field( ...
                                cfg, 'status_phase_tag', ...
                                run_warn_state_utils.phase_end()), ...
                            'warn_key', struct_utils.opt_struct_field( ...
                                cfg, 'status_warn_key', ...
                                'run_status_write_failed'), ...
                            'warn_id', struct_utils.opt_struct_field( ...
                                cfg, 'status_warn_id', ...
                                'CerUPP:RunStatus:RunStatusWriteFailed'), ...
                            'failure_tag', struct_utils.opt_struct_field( ...
                                cfg, 'status_failure_tag', ...
                                'run_status_final_write')), ...
                        run_warn_state);
            end

            finalize_status.status_write_post_latest_pointer_attempted = ...
                logical(republish_attempted);
            finalize_status.status_write_post_latest_pointer_ok = logical(republish_ok);
            finalize_status.status_write_ok = logical(struct_utils.opt_struct_field( ...
                finalize_status, 'status_write_ok', true)) && logical(republish_ok);
            finalize_status.status_write_status = ...
                run_output_utils.ternary_status_local( ...
                    logical(struct_utils.opt_struct_field( ...
                        finalize_status, 'status_write_attempted', false)), ...
                    logical(finalize_status.status_write_ok));
            run_status_ctx.last_finalize_status = finalize_status;
        end

        function cfg = build_finalize_run_attempt_status_cfg( ...
                run_status_ctx, restart_compat_version, release_version, ...
                curr_cerupp_version, ...
                attempt_state, error_id, error_message, mode_tag, status_extra_fields)
        % Build the shared end/catch finalize request for run-output status handling.

            if nargin < 1 || ~isstruct(run_status_ctx)
                run_status_ctx = struct();
            end
            if nargin < 2 || isempty(restart_compat_version)
                restart_compat_version = NaN;
            end
            if nargin < 3 || isempty(release_version)
                release_version = '';
            end
            if nargin < 4 || isempty(curr_cerupp_version)
                curr_cerupp_version = '';
            end
            if nargin < 5 || isempty(attempt_state)
                attempt_state = 'failed';
            end
            if nargin < 6 || isempty(error_id)
                error_id = '';
            end
            if nargin < 7 || isempty(error_message)
                error_message = '';
            end
            if nargin < 8 || isempty(mode_tag)
                mode_tag = 'normal_exit';
            end
            if nargin < 9 || isempty(status_extra_fields)
                status_extra_fields = struct();
            end
            phase_specs = run_output_utils.build_run_status_phase_specs_local(mode_tag);
            cfg = struct( ...
                'run_status_ctx', run_status_ctx, ...
                'attempt_state', char(string(attempt_state)), ...
                'error_id', char(string(error_id)), ...
                'error_message', char(string(error_message)), ...
                'status_extra_fields', status_extra_fields, ...
                'restart_compat_version', double(restart_compat_version), ...
                'release_version', char(string(release_version)), ...
                'curr_cerupp_version', char(string(curr_cerupp_version)), ...
                'status_phase_tag', phase_specs.status_phase_tag, ...
                'status_warn_key', phase_specs.status_warn_key, ...
                'status_warn_id', phase_specs.status_warn_id, ...
                'status_failure_tag', phase_specs.status_failure_tag, ...
                'pointer_phase_tag', phase_specs.pointer_phase_tag, ...
                'pointer_warn_key', phase_specs.pointer_warn_key, ...
                'pointer_warn_id', phase_specs.pointer_warn_id, ...
                'pointer_failure_tag', phase_specs.pointer_failure_tag);
        end
    end

    methods (Static, Access = private)
        function [cfg, run_warn_state] = normalize_policy_inputs_local(cfg, run_warn_state)
            if nargin < 1 || isempty(cfg)
                cfg = struct();
            elseif ~(isstruct(cfg) && isscalar(cfg))
                error('run_output_utils:InvalidPolicyCfg', ...
                    'cfg must be a scalar struct or [].');
            end
            if nargin < 2 || isempty(run_warn_state)
                run_warn_state = struct();
            elseif ~(isstruct(run_warn_state) && isscalar(run_warn_state))
                error('run_output_utils:InvalidPolicyWarnState', ...
                    'run_warn_state must be a scalar struct or [].');
            end
        end

        function output_root_resolved = resolve_output_root_local(output_root, driver_root)
            if nargin < 1 || isempty(output_root)
                output_root = '';
            end
            if nargin < 2 || isempty(driver_root)
                driver_root = pwd;
            end
            if isstring(output_root) && isscalar(output_root)
                output_root = char(output_root);
            end
            if ~ischar(output_root)
                error('CerUPP:InvalidOutputRoot', ...
                    'output_root must be a char path or scalar string.');
            end
            output_root = strtrim(output_root);
            if isstring(driver_root) && isscalar(driver_root)
                driver_root = char(driver_root);
            end
            if ~ischar(driver_root)
                error('CerUPP:InvalidDriverRoot', ...
                    'driver_root must be a char path or scalar string.');
            end
            driver_root = strtrim(driver_root);
            if isempty(driver_root)
                driver_root = pwd;
            end

            if isempty(output_root)
                output_root_resolved = driver_root;
            elseif startsWith(output_root, filesep) || ...
                    ~isempty(regexp(output_root, '^[A-Za-z]:[\\/]', 'once'))
                output_root_resolved = output_root;
            else
                output_root_resolved = fullfile(driver_root, output_root);
            end
        end

        function artifact_paths = build_artifact_paths_local(run_bucket, run_output_root, run_id)
            artifact_names = run_output_utils.artifact_names();
            artifact_paths = struct( ...
                'run_id', char(string(run_id)), ...
                'run_bucket', run_bucket, ...
                'run_output_root', run_output_root, ...
                'plots', struct('root', fullfile(run_output_root, 'output_plots')), ...
                'csv', struct('root', fullfile(run_output_root, 'csv_outputs')), ...
                'checkpoints', struct('root', fullfile(run_output_root, 'checkpoints')), ...
                'data', struct('base_stem', fullfile(run_output_root, 'CerUPP_data')), ...
                'status', struct( ...
                    'root', run_output_root, ...
                    'name', artifact_names.run_status_name), ...
                'pointers', struct( ...
                    'current', struct( ...
                        'root', run_output_root, ...
                        'name', artifact_names.current_run_pointer_name), ...
                    'latest_successful', struct( ...
                        'root', run_bucket, ...
                        'name', artifact_names.latest_successful_run_pointer_name), ...
                    'latest_propagation_complete', struct( ...
                        'root', run_bucket, ...
                        'name', ...
                            artifact_names.latest_propagation_complete_run_pointer_name), ...
                    'latest_fully_packaged', struct( ...
                        'root', run_bucket, ...
                        'name', ...
                            artifact_names.latest_fully_packaged_run_pointer_name)));
        end

        function [run_tag, run_warn_state] = sanitize_run_tag_local(run_tag, run_warn_state)
            if isstring(run_tag) && isscalar(run_tag)
                run_tag = char(run_tag);
            end
            run_tag = strtrim(char(run_tag));
            run_tag_raw = run_tag;
            run_tag = regexprep(run_tag, '[^A-Za-z0-9_-]', '_');
            if isempty(run_tag)
                run_tag = 'default';
            end
            if ~strcmp(run_tag, run_tag_raw)
                run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                    run_warn_state, run_warn_state_utils.phase_setup(), ...
                    'setup_run_tag_sanitized', ...
                    'CerUPP:RunTagSanitized', ...
                    'Sanitized run_tag from "%s" to "%s" for filesystem-safe output paths.', ...
                    run_tag_raw, run_tag);
            end
        end

        function startup_policy = normalize_run_output_startup_policy_local(startup_policy_in)
            startup_policy = run_output_utils.default_run_output_startup_policy();
            if nargin < 1 || isempty(startup_policy_in)
                return;
            end
            if ~(isstruct(startup_policy_in) && isscalar(startup_policy_in))
                error('run_output_utils:InvalidOutputStartupPolicy', ...
                    'output_startup_policy must be a scalar struct or [].');
            end
            startup_policy_fields = fieldnames(startup_policy_in);
            allowed_fields = fieldnames(startup_policy);
            unknown_fields = startup_policy_fields(~ismember(startup_policy_fields, allowed_fields));
            if ~isempty(unknown_fields)
                error('run_output_utils:UnknownOutputStartupPolicyField', ...
                    'Unknown output_startup_policy field(s): %s', strjoin(unknown_fields, ', '));
            end
            for field_idx = 1:numel(allowed_fields)
                field_name = allowed_fields{field_idx};
                if isfield(startup_policy_in, field_name) && ~isempty(startup_policy_in.(field_name))
                    startup_policy.(field_name) = struct_utils.normalize_bool_scalar( ...
                        startup_policy_in.(field_name), ...
                        ['output_startup_policy.' field_name], ...
                        'run_output_utils:InvalidOutputStartupPolicyFlag');
                end
            end
        end

        function [artifact_paths, startup_action, auto_timestamped_run_output_root, run_warn_state] = ...
                resolve_run_output_artifact_paths_local(output_root_resolved, run_tag, startup_policy, run_warn_state)
            auto_timestamped_run_output_root = false;
            if startup_policy.append_timestamp_to_run_id
                run_id = sprintf('%s_%s', run_tag, datestr(now, 'yyyymmdd_HHMMSS'));
            else
                run_id = run_tag;
            end
            run_id = regexprep(run_id, '[^A-Za-z0-9_-]', '_');
            run_bucket = fullfile(output_root_resolved, ['run_' run_tag]);
            run_output_root = fullfile(run_bucket, run_id);
            startup_action = 'create_new_run_output_root';
            if exist(run_output_root, 'dir')
                if startup_policy.archive_existing_run_output_root
                    startup_action = 'archive_existing_run_output_root';
                elseif startup_policy.auto_timestamp_on_run_output_collision || ...
                        startup_policy.append_timestamp_to_run_id
                    if startup_policy.append_timestamp_to_run_id
                        [run_id, run_output_root] = ...
                            run_output_utils.find_unique_collision_run_root_from_base_local( ...
                            run_bucket, run_id);
                    else
                        [run_id, run_output_root] = ...
                            run_output_utils.find_unique_collision_run_root_local( ...
                            run_bucket, run_tag);
                    end
                    auto_timestamped_run_output_root = true;
                    startup_action = 'auto_timestamp_new_run_output_root';
                    run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                        run_warn_state, run_warn_state_utils.phase_setup(), ...
                        'setup_run_id_auto_timestamped_existing_output', ...
                        'CerUPP:RunOutput:IdExistsAutoTimestamped', ...
                        ['run_output_root already existed for run_tag="%s". ' ...
                         'Created unique run directory "%s" instead of failing startup.'], ...
                        run_tag, run_output_root);
                else
                    error('CerUPP:RunOutputRootExists', ...
                        ['run_output_root="%s" already exists. Refusing automatic archival by default. ', ...
                         'Set append_timestamp_to_run_id=true for unique output trees or ', ...
                         'archive_existing_run_output_root=true to archive the existing tree explicitly.'], ...
                        run_output_root);
                end
            end
            artifact_paths = run_output_utils.build_artifact_paths_local( ...
                run_bucket, run_output_root, run_id);
        end

        function [run_id, run_output_root] = resolve_run_status_identity_local(run_status_ctx)
            if nargin < 1 || ~isstruct(run_status_ctx)
                run_id = '';
                run_output_root = '';
                return;
            end
            artifact_paths = struct_utils.opt_struct_field(run_status_ctx, 'artifact_paths', struct());
            run_id = char(string(struct_utils.opt_struct_field( ...
                artifact_paths, 'run_id', struct_utils.opt_struct_field(run_status_ctx, 'run_id', ''))));
            run_output_root = char(string(struct_utils.opt_struct_field( ...
                artifact_paths, 'run_output_root', ...
                struct_utils.opt_struct_field(run_status_ctx, 'run_output_root', ''))));
        end

        function artifact_path_ctx = resolve_run_status_artifact_paths_local(run_status_ctx)
            artifact_path_ctx = struct( ...
                'status_root', '', ...
                'status_name', '', ...
                'current_pointer_root', '', ...
                'current_pointer_name', '');
            if nargin < 1 || ~isstruct(run_status_ctx)
                return;
            end
            artifact_paths = struct_utils.opt_struct_field(run_status_ctx, 'artifact_paths', struct());
            artifact_path_ctx.status_root = char(string(struct_utils.opt_struct_field( ...
                struct_utils.opt_struct_field(artifact_paths, 'status', struct()), ...
                'root', struct_utils.opt_struct_field(run_status_ctx, 'status_root', ''))));
            artifact_path_ctx.status_name = char(string(struct_utils.opt_struct_field( ...
                struct_utils.opt_struct_field(artifact_paths, 'status', struct()), ...
                'name', struct_utils.opt_struct_field(run_status_ctx, 'status_name', ''))));
            pointer_current = struct_utils.opt_struct_field( ...
                struct_utils.opt_struct_field(artifact_paths, 'pointers', struct()), ...
                'current', struct());
            artifact_path_ctx.current_pointer_root = char(string(struct_utils.opt_struct_field( ...
                pointer_current, 'root', ...
                struct_utils.opt_struct_field(run_status_ctx, 'current_pointer_root', ''))));
            artifact_path_ctx.current_pointer_name = char(string(struct_utils.opt_struct_field( ...
                pointer_current, 'name', ...
                struct_utils.opt_struct_field(run_status_ctx, 'current_pointer_name', ''))));
        end

        function [run_id, run_output_root] = find_unique_collision_run_root_local(run_bucket, run_tag)
            collision_stamp = datestr(now, 'yyyymmdd_HHMMSS');
            collision_run_id_base = regexprep( ...
                sprintf('%s_%s', run_tag, collision_stamp), '[^A-Za-z0-9_-]', '_');
            [run_id, run_output_root] = ...
                run_output_utils.find_unique_collision_run_root_from_base_local( ...
                run_bucket, collision_run_id_base);
        end

        function [run_id, run_output_root] = ...
                find_unique_collision_run_root_from_base_local( ...
                run_bucket, collision_run_id_base)
            run_id = collision_run_id_base;
            run_output_root = fullfile(run_bucket, run_id);
            collision_idx = 0;
            while exist(run_output_root, 'dir')
                collision_idx = collision_idx + 1;
                run_id = sprintf('%s_%02d', collision_run_id_base, collision_idx);
                run_output_root = fullfile(run_bucket, run_id);
                if collision_idx > 999
                    error('CerUPP:RunIdTimestampCollision', ...
                        ['Could not resolve a unique run directory from base run_id="%s". ', ...
                         'Tried suffixes up to %d.'], ...
                        collision_run_id_base, collision_idx);
                end
            end
        end

        function [run_warn_state, archive_path] = materialize_run_output_root_local( ...
                run_bucket, run_output_root, run_id, startup_action, run_warn_state)
            archive_path = '';
            if ~exist(run_output_root, 'dir')
                run_output_utils.ensure_target_dir_ready_local(run_output_root);
                return;
            end
            switch char(string(startup_action))
                case 'create_new_run_output_root'
                    error('CerUPP:RunOutputRootMaterializeCollision', ...
                        ['run_output_root="%s" appeared after path resolution but before startup initialization. ', ...
                         'Refusing silent reuse.'], ...
                        run_output_root);
                case 'auto_timestamp_new_run_output_root'
                    archive_path = run_output_utils.build_unique_archive_path_local( ...
                        run_bucket, run_id, run_output_root);
                    [ok_move, move_msg, move_msgid] = movefile( ...
                        run_output_root, archive_path);
                    if ~ok_move
                        error('CerUPP:RunIdArchiveFailed', ...
                            ['Failed to archive colliding timestamped run_output_root="%s" to "%s" before startup initialization. ' ...
                             'movefile error (%s): %s'], ...
                            run_output_root, archive_path, move_msgid, move_msg);
                    end
                    run_output_utils.ensure_target_dir_ready_local(run_output_root);
                case 'archive_existing_run_output_root'
                    archive_path = run_output_utils.build_unique_archive_path_local(run_bucket, run_id, run_output_root);
                    [ok_move, move_msg, move_msgid] = movefile(run_output_root, archive_path);
                    if ~ok_move
                        error('CerUPP:RunIdArchiveFailed', ...
                            ['Failed to archive existing run_output_root="%s" to "%s" before starting new run. ' ...
                             'movefile error (%s): %s'], ...
                            run_output_root, archive_path, move_msgid, move_msg);
                    end
                    run_output_utils.ensure_target_dir_ready_local(run_output_root);
                otherwise
                    error('run_output_utils:UnknownRunOutputStartupAction', ...
                        'Unknown run-output startup_action "%s".', startup_action);
            end
        end

        function archive_path = build_unique_archive_path_local(run_bucket, run_id, run_output_root)
            archive_stamp = datestr(now, 'yyyymmdd_HHMMSS');
            archive_try = fullfile(run_bucket, sprintf('%s_old_pre_%s', run_id, archive_stamp));
            archive_idx = 0;
            while exist(archive_try, 'dir')
                archive_idx = archive_idx + 1;
                archive_try = fullfile(run_bucket, ...
                    sprintf('%s_old_pre_%s_%02d', run_id, archive_stamp, archive_idx));
                if archive_idx > 999
                    error('CerUPP:RunIdArchiveCollision', ...
                        ['Could not resolve a unique archive directory for existing run_output_root="%s". ' ...
                         'Tried timestamped suffixes up to %d.'], run_output_root, archive_idx);
                end
            end
            archive_path = archive_try;
        end

        function ensure_target_dir_ready_local(target_dir)
            if isempty(target_dir)
                target_dir = '.';
            end
            if exist(target_dir, 'dir') ~= 7
                [ok_mkdir, mkdir_msg, mkdir_msgid] = mkdir(target_dir);
                if ~ok_mkdir && (exist(target_dir, 'dir') ~= 7)
                    error('run_output_utils:DirCreateFailed', ...
                        'Could not create directory "%s" (%s): %s', ...
                        target_dir, char(string(mkdir_msgid)), char(string(mkdir_msg)));
                end
            end
        end

        function phase_specs = build_run_status_phase_specs_local(mode_tag)
            if nargin < 1 || isempty(mode_tag)
                mode_tag = 'normal_exit';
            end
            mode_tag = char(string(mode_tag));
            switch mode_tag
                case 'setup'
                    phase_specs = struct( ...
                        'status_phase_tag', run_warn_state_utils.phase_setup(), ...
                        'status_warn_key', 'setup_run_status_write_failed', ...
                        'status_warn_id', 'CerUPP:RunStatus:RunStatusWriteFailed', ...
                        'status_failure_tag', 'run_status_setup_write', ...
                        'pointer_phase_tag', run_warn_state_utils.phase_setup(), ...
                        'pointer_warn_key', 'setup_current_run_pointer_write_failed', ...
                        'pointer_warn_id', 'CerUPP:RunStatus:CurrentRunPointerWriteFailed', ...
                        'pointer_failure_tag', 'current_run_pointer');
                case 'normal_exit'
                    phase_specs = struct( ...
                        'status_phase_tag', 'end', ...
                        'status_warn_key', 'final_run_status_write_failed', ...
                        'status_warn_id', 'CerUPP:RunStatus:FinalRunStatusWriteFailed', ...
                        'status_failure_tag', 'run_status_final_write', ...
                        'pointer_phase_tag', 'end', ...
                        'pointer_warn_key', 'final_current_run_pointer_delete_failed', ...
                        'pointer_warn_id', 'CerUPP:RunStatus:CurrentRunPointerDeleteFailed', ...
                        'pointer_failure_tag', 'current_run_pointer_delete');
                case 'caught_error'
                    phase_specs = struct( ...
                        'status_phase_tag', 'end', ...
                        'status_warn_key', 'failed_run_status_write_failed', ...
                        'status_warn_id', 'CerUPP:RunStatus:FailedRunStatusWriteFailed', ...
                        'status_failure_tag', 'run_status_failure_write', ...
                        'pointer_phase_tag', 'end', ...
                        'pointer_warn_key', 'failed_current_run_pointer_delete_failed', ...
                        'pointer_warn_id', 'CerUPP:RunStatus:FailedCurrentRunPointerDeleteFailed', ...
                        'pointer_failure_tag', 'current_run_pointer_delete');
                otherwise
                    error('run_output_utils:InvalidFinalizeRunAttemptStatusMode', ...
                        'Unsupported run-status lifecycle mode "%s".', mode_tag);
            end
        end

        function status_payload = merge_status_extra_fields_local(status_payload, status_extra_fields)
            if isempty(status_extra_fields)
                return;
            end
            if ~(isstruct(status_extra_fields) && isscalar(status_extra_fields))
                error('run_output_utils:InvalidRunStatusExtraFields', ...
                    'status_extra_fields must be one scalar struct when provided.');
            end
            extra_field_names = fieldnames(status_extra_fields);
            for field_idx = 1:numel(extra_field_names)
                field_name = extra_field_names{field_idx};
                if ~isvarname(field_name)
                    error('run_output_utils:InvalidRunStatusExtraFieldName', ...
                        'status_extra_fields contains invalid field name "%s".', field_name);
                end
                if isfield(status_payload, field_name)
                    error('run_output_utils:ConflictingRunStatusExtraField', ...
                        ['status_extra_fields.%s conflicts with one built-in run-status ', ...
                         'field. Use a distinct extra field name.'], field_name);
                end
                status_payload.(field_name) = status_extra_fields.(field_name);
            end
        end

        function [run_warn_state, save_ok] = publish_run_status_payload_local( ...
                run_status_ctx, status_payload, status_cfg, run_warn_state)
            save_ok = false;
            if ~(isfield(run_status_ctx, 'enabled') && run_status_ctx.enabled)
                save_ok = true;
                return;
            end
            artifact_path_ctx = run_output_utils.resolve_run_status_artifact_paths_local( ...
                run_status_ctx);
            [run_warn_state, save_ok] = checkpoint_utils.write_run_status_file( ...
                struct( ...
                    'run_bucket', artifact_path_ctx.status_root, ...
                    'status_name', artifact_path_ctx.status_name, ...
                    'status_payload', status_payload, ...
                    'phase_tag', struct_utils.opt_struct_field(status_cfg, 'phase_tag', run_warn_state_utils.phase_end()), ...
                    'warn_key', struct_utils.opt_struct_field(status_cfg, 'warn_key', 'run_status_write_failed'), ...
                    'warn_id', struct_utils.opt_struct_field(status_cfg, 'warn_id', 'CerUPP:RunStatus:RunStatusWriteFailed'), ...
                    'failure_tag', struct_utils.opt_struct_field(status_cfg, 'failure_tag', 'run_status_final_write')), ...
                run_warn_state);
        end

        function status_txt = ternary_status_local(attempted, ok)
            if ~attempted
                status_txt = 'skipped';
            elseif ok
                status_txt = 'written';
            else
                status_txt = 'failed';
            end
        end

        function [run_warn_state, pointer_status] = apply_current_run_pointer_local( ...
                run_status_ctx, pointer_cfg, action_mode, run_warn_state)
            pointer_status = 'skipped';
            write_current_pointer = isfield(run_status_ctx, 'write_current_pointer') && ...
                run_status_ctx.write_current_pointer;
            if ~write_current_pointer
                return;
            end
            artifact_path_ctx = run_output_utils.resolve_run_status_artifact_paths_local( ...
                run_status_ctx);
            shared_pointer_cfg = struct( ...
                'run_bucket', artifact_path_ctx.current_pointer_root, ...
                'pointer_name', artifact_path_ctx.current_pointer_name, ...
                'phase_tag', struct_utils.opt_struct_field(pointer_cfg, 'phase_tag', run_warn_state_utils.phase_end()), ...
                'warn_key', struct_utils.opt_struct_field(pointer_cfg, 'warn_key', 'run_id_pointer_write_failed'), ...
                'warn_id', struct_utils.opt_struct_field(pointer_cfg, 'warn_id', 'CerUPP:RunStatus:RunIdPointerWriteFailed'), ...
                'failure_tag', struct_utils.opt_struct_field(pointer_cfg, 'failure_tag', 'current_run_pointer'));
            action_mode = char(string(action_mode));
            switch action_mode
                case 'write'
                    shared_pointer_cfg.run_id = struct_utils.req_struct_field( ...
                        pointer_cfg, 'run_id', 'run_output_utils.apply_current_run_pointer_local');
                    run_warn_state = checkpoint_utils.write_run_id_pointer( ...
                        shared_pointer_cfg, run_warn_state);
                    pointer_status = 'written';
                case 'delete'
                    [run_warn_state, pointer_status] = checkpoint_utils.delete_run_id_pointer( ...
                        shared_pointer_cfg, run_warn_state);
                otherwise
                    error('run_output_utils:InvalidRunStatusPointerAction', ...
                        'Unsupported run-status pointer action "%s".', action_mode);
            end
        end
    end
end
