function [memmon_last_gb, memmon_peak_gb, memmon_time_vec, memmon_mem_vec, ...
        do_memmon_base, progress_mem_enabled, run_warn_state, ...
        memmon_warn_state, memmon_sample] = sample_memmon_or_latch_off( ...
        sample_tag, curr_z_step, z_curr, prop_code_start, ...
        memmon_time_vec, memmon_mem_vec, num_zsteps, ...
        memmon_last_gb, memmon_peak_gb, memmon_warn_state, ...
        memmon_cfg, do_memmon_base, progress_mem_enabled, ...
        run_warn_state, phase_tag)
% Propagation-loop MEMMON helper for cerupp.m.
% Sample the memory monitor once, keep the returned sample when it
% succeeds, and latch MEMMON off for the rest of the run if a
% non-threshold monitor failure occurs.

    memmon_sample = struct();
    try
        [memmon_last_gb, memmon_peak_gb, memmon_time_vec, memmon_mem_vec, ...
            memmon_warn_state, memmon_sample] = ...
            runtime_monitor_utils.memmon_checkpoint_fast( ...
                sample_tag, curr_z_step, z_curr, prop_code_start, ...
                memmon_time_vec, memmon_mem_vec, num_zsteps, ...
                memmon_last_gb, memmon_peak_gb, memmon_warn_state, ...
                memmon_cfg);
    catch me_memmon
        if strcmp(me_memmon.identifier, 'CerUPP:MemMon:AbortOnThreshold')
            rethrow(me_memmon);
        end
        [do_memmon_base, run_warn_state] = ...
            run_warn_state_utils.latch_off_after_failure( ...
                do_memmon_base, run_warn_state, phase_tag, ...
                'prop_memmon_monitor_failure', ...
                'CerUPP:MemMon:MonitorFailure', ...
                ['MEMMON (memory monitor) failure at step %d (%s): %s. ', ...
                 'Disabling MEMMON (memory monitor) for remainder of run.'], ...
                curr_z_step, sample_tag, me_memmon.message);
        progress_mem_enabled = false;
    end
end
