function setup_state = build_plasma_ofi_nla_step_inputs(cfg)
%BUILD_PLASMA_OFI_NLA_STEP_INPUTS Finish the once-per-run plasma / OFI / NLA setup.
% Called after Section 4A has already settled the late runtime/output
% policy and built the setup-time Keldysh runtime object.

    if (nargin ~= 1) || ~isstruct(cfg) || ~isscalar(cfg)
        error('CerUPP:InvalidPlasmaOfiNlaSetupCfg', ...
            'build_plasma_ofi_nla_step_inputs requires one scalar cfg struct.');
    end

    [plasma_runtime_cfg, fee_z_rk2_flag, plasma_z_rk2_flag, ...
        nla_z_rk2_flag, plasma_evolve_t_rk2_flag, ...
        nla_use_ofi_rate_law_flag, keldysh_enabled, ...
        plasma_ofi_use_remaining_neutral_factor_flag, ...
        ofi_branch_active_for_setup, ...
        nla_use_remaining_neutral_factor_flag, ...
        nla_ofi_energy_accounting_mode, ...
        nla_check_ofi_event_energy_flag, nla_use_ofi_event_depletion_flag, ...
        frozen_cfg_ofi_k_orders, ...
        beta_k_vec, nl_absorption_flag, run_warn_state, ...
        setup_physics_rewrite_report, frozen_cfg_rho_nt_m3, ...
        plasma_flag, ion_routine_flag, frozen_cfg_sigma_k_vec, ...
        frozen_cfg_rho_nt_keldysh_norm_m3, medium_spec, ...
        keldysh_convention_autoselect_used, ion_routine_flag_requested, ...
        use_nlse_flag_requested, use_nlse_flag, ...
        nonparaxial_diffraction_order_requested, ...
        nonparaxial_diffraction_order, resolved_nla_setup_closure, ...
        keldysh_display_k, ...
        keldysh_lut_i_roi_min_effective, medium_param_knobs_applied, ...
        resolved_keldysh_convention_desc, frozen_cfg_ui, ...
        frozen_cfg_keldysh_gap_j, frozen_cfg_keldysh_matched_depletion_j, ...
        n_sell_fund, frozen_cfg_tau_c, frozen_cfg_alpha_recombine, ...
        keldysh_mred_over_me, plasma_m_over_me, m_plasma_kg, ...
        propagation_medium_name, x, y, t, omega_window, inv_vg_fund, ...
        core_idx, mask_2_d, num_x_pts, num_y_pts, diagnostics_flag, ...
        strict_stage_finite_scan_flag, checkpoint_diag_reassembly_flag, ...
        enable_drho_xz_diagnostics, sigma_vec, sigma_aval_omega_fund, ...
        dz_vec_all, nl_index_3d, omega_fund, n2_kerr_disable_tol, ...
        kerr_enabled_flag, qomega_3d] = ...
        struct_utils.unpack_struct_fields(cfg, ...
        {'plasma_runtime_cfg', 'fee_z_rk2_flag', 'plasma_z_rk2_flag', ...
         'nla_z_rk2_flag', 'plasma_evolve_t_rk2_flag', ...
         'nla_use_ofi_rate_law_flag', 'keldysh_enabled', ...
         'plasma_ofi_use_remaining_neutral_factor_flag', ...
         'ofi_branch_active_for_setup', ...
         'nla_use_remaining_neutral_factor_flag', ...
         'nla_ofi_energy_accounting_mode', ...
         'nla_check_ofi_event_energy_flag', ...
         'nla_use_ofi_event_depletion_flag', 'frozen_cfg_ofi_k_orders', ...
         'beta_k_vec', 'nl_absorption_flag', 'run_warn_state', ...
         'setup_physics_rewrite_report', 'frozen_cfg_rho_nt_m3', ...
         'plasma_flag', 'ion_routine_flag', 'frozen_cfg_sigma_k_vec', ...
         'frozen_cfg_rho_nt_keldysh_norm_m3', 'medium_spec', ...
         'keldysh_convention_autoselect_used', 'ion_routine_flag_requested', ...
         'use_nlse_flag_requested', 'use_nlse_flag', ...
         'nonparaxial_diffraction_order_requested', ...
         'nonparaxial_diffraction_order', 'resolved_nla_setup_closure', ...
         'keldysh_display_k', ...
         'keldysh_lut_i_roi_min_effective', 'medium_param_knobs_applied', ...
         'resolved_keldysh_convention_desc', 'frozen_cfg_ui', ...
         'frozen_cfg_keldysh_gap_j', ...
         'frozen_cfg_keldysh_matched_depletion_j', 'n_sell_fund', ...
         'frozen_cfg_tau_c', 'frozen_cfg_alpha_recombine', ...
         'keldysh_mred_over_me', 'plasma_m_over_me', 'm_plasma_kg', ...
         'propagation_medium_name', 'x', 'y', 't', 'omega_window', ...
         'inv_vg_fund', 'core_idx', 'mask_2_d', 'num_x_pts', ...
         'num_y_pts', 'diagnostics_flag', ...
         'strict_stage_finite_scan_flag', ...
         'checkpoint_diag_reassembly_flag', 'enable_drho_xz_diagnostics', ...
         'sigma_vec', 'sigma_aval_omega_fund', 'dz_vec_all', ...
         'nl_index_3d', 'omega_fund', 'n2_kerr_disable_tol', ...
         'kerr_enabled_flag', 'qomega_3d'}, ...
        'build_plasma_ofi_nla_step_inputs cfg');

    if ~isstruct(plasma_runtime_cfg) || ~isfield(plasma_runtime_cfg, 'keldysh_cfg') || ...
            ~isstruct(plasma_runtime_cfg.keldysh_cfg)
        error('CerUPP:MissingKeldyshRuntimeCfg', ...
            ['build_plasma_ofi_nla_step_inputs requires plasma_runtime_cfg.keldysh_cfg ', ...
             'to exist before the late plasma/NLA settle runs.']);
    end

    submodel_cfgs = build_submodel_cfgs_local(struct( ...
        'fee_z_rk2_flag', fee_z_rk2_flag, ...
        'plasma_z_rk2_flag', plasma_z_rk2_flag, ...
        'nla_z_rk2_flag', nla_z_rk2_flag, ...
        'plasma_evolve_t_rk2_flag', plasma_evolve_t_rk2_flag, ...
        'nla_use_ofi_rate_law_flag', nla_use_ofi_rate_law_flag, ...
        'keldysh_enabled', keldysh_enabled, ...
        'plasma_ofi_use_remaining_neutral_factor_flag', ...
            plasma_ofi_use_remaining_neutral_factor_flag, ...
        'ofi_branch_active_for_setup', ofi_branch_active_for_setup, ...
        'nla_use_remaining_neutral_factor_flag', ...
            nla_use_remaining_neutral_factor_flag, ...
        'nla_ofi_energy_accounting_mode', nla_ofi_energy_accounting_mode, ...
        'nla_check_ofi_event_energy_flag', nla_check_ofi_event_energy_flag, ...
        'nla_use_ofi_event_depletion_flag', ...
            nla_use_ofi_event_depletion_flag, ...
        'ofi_k_orders', frozen_cfg_ofi_k_orders, ...
        'beta_k_vec', beta_k_vec, ...
        'nl_absorption_flag', nl_absorption_flag, ...
        'run_warn_state', run_warn_state, ...
        'setup_physics_rewrite_report', setup_physics_rewrite_report, ...
        'plasma_runtime_cfg', plasma_runtime_cfg, ...
        'rho_nt_m3', frozen_cfg_rho_nt_m3, ...
        'plasma_flag', plasma_flag, ...
        'ion_routine_flag', ion_routine_flag, ...
        'sigma_k_vec', frozen_cfg_sigma_k_vec, ...
        'rho_nt_keldysh_norm_m3', frozen_cfg_rho_nt_keldysh_norm_m3, ...
        'ui', frozen_cfg_ui, ...
        'keldysh_matched_depletion_j', ...
            frozen_cfg_keldysh_matched_depletion_j, ...
        'medium_spec', medium_spec, ...
        'keldysh_convention_autoselect_used', ...
            keldysh_convention_autoselect_used, ...
        'ion_routine_flag_requested', ion_routine_flag_requested, ...
        'use_nlse_flag_requested', use_nlse_flag_requested, ...
        'use_nlse_flag', use_nlse_flag, ...
        'nonparaxial_diffraction_order_requested', ...
            nonparaxial_diffraction_order_requested, ...
        'nonparaxial_diffraction_order', nonparaxial_diffraction_order, ...
        'kerr_enabled_flag', kerr_enabled_flag, ...
        'resolved_nla_setup_closure', resolved_nla_setup_closure));
    run_warn_state = submodel_cfgs.run_warn_state;
    setup_physics_rewrite_report = submodel_cfgs.setup_physics_rewrite_report;
    plasma_runtime_cfg = submodel_cfgs.plasma_runtime_cfg;
    nla_runtime_cfg = submodel_cfgs.nla_runtime_cfg;
    rho_nt = submodel_cfgs.rho_nt;
    avalanche_branch_active_for_setup = ...
        submodel_cfgs.avalanche_branch_active_for_setup;
    plasma_z_rk2_flag_effective = submodel_cfgs.plasma_z_rk2_flag_effective;
    nla_z_rk2_flag_effective = submodel_cfgs.nla_z_rk2_flag_effective;
    plasma_evolve_t_rk2_flag = submodel_cfgs.plasma_evolve_t_rk2_flag;
    resolved_physics_policy = submodel_cfgs.resolved_physics_policy;
    submodel_warn_state = submodel_cfgs.submodel_warn_state;

    setup_contract_state = finalize_setup_contract_local(struct( ...
        'nla_runtime_cfg', nla_runtime_cfg, ...
        'ofi_branch_active_for_setup', ofi_branch_active_for_setup, ...
        'keldysh_enabled', keldysh_enabled, ...
        'nl_absorption_flag', nl_absorption_flag, ...
        'run_warn_state', run_warn_state, ...
        'plasma_runtime_cfg', plasma_runtime_cfg, ...
        'keldysh_display_k', keldysh_display_k, ...
        'ofi_k_orders', frozen_cfg_ofi_k_orders, ...
        'sigma_k_vec', frozen_cfg_sigma_k_vec, ...
        'keldysh_lut_i_roi_min_effective', ...
            keldysh_lut_i_roi_min_effective, ...
        'medium_spec', medium_spec, ...
        'medium_param_knobs_applied', medium_param_knobs_applied, ...
        'resolved_keldysh_convention_desc', ...
            resolved_keldysh_convention_desc, ...
        'keldysh_convention_autoselect_used', ...
            keldysh_convention_autoselect_used, ...
        'ui', frozen_cfg_ui, ...
        'keldysh_gap_j', frozen_cfg_keldysh_gap_j, ...
        'keldysh_matched_depletion_j', ...
            frozen_cfg_keldysh_matched_depletion_j, ...
        'rho_nt_m3', frozen_cfg_rho_nt_m3, ...
        'rho_nt_keldysh_norm_m3', frozen_cfg_rho_nt_keldysh_norm_m3, ...
        'n_sell_fund', n_sell_fund, ...
        'tau_c', frozen_cfg_tau_c, ...
        'alpha_recombine', frozen_cfg_alpha_recombine, ...
        'keldysh_mred_over_me', keldysh_mred_over_me, ...
        'plasma_m_over_me', plasma_m_over_me, ...
        'm_plasma_kg', m_plasma_kg, ...
        'propagation_medium_name', propagation_medium_name, ...
        'resolved_nla_setup_closure', resolved_nla_setup_closure, ...
        'resolved_physics_policy', resolved_physics_policy));
    run_warn_state = setup_contract_state.run_warn_state;
    keldysh_effective_nla_available_flag = ...
        setup_contract_state.keldysh_effective_nla_available_flag;
    need_keldysh_effective_nla_raw_history_flag = ...
        setup_contract_state.need_keldysh_effective_nla_raw_history_flag;
    track_keldysh_effective_nla_diag_flag = ...
        setup_contract_state.track_keldysh_effective_nla_diag_flag;

    [~, ix_axis0_setup] = min(abs(x));
    [~, iy_axis0_setup] = min(abs(y));

    stepper_payloads = build_stepper_payloads_local(struct( ...
        'plasma_runtime_cfg', plasma_runtime_cfg, ...
        'nla_runtime_cfg', nla_runtime_cfg, ...
        'submodel_warn_state', submodel_warn_state, ...
        't', t, ...
        'omega_window', omega_window, ...
        'ix_axis0', ix_axis0_setup, ...
        'iy_axis0', iy_axis0_setup, ...
        'inv_vg_fund', inv_vg_fund, ...
        'core_idx', core_idx, ...
        'mask_2_d', mask_2_d, ...
        'num_x_pts', num_x_pts, ...
        'num_y_pts', num_y_pts, ...
        'plasma_flag', plasma_flag, ...
        'nl_absorption_flag', nl_absorption_flag, ...
        'diagnostics_flag', diagnostics_flag, ...
        'strict_stage_finite_scan_flag', strict_stage_finite_scan_flag, ...
        'keldysh_effective_nla_available_flag', ...
            keldysh_effective_nla_available_flag, ...
        'need_keldysh_effective_nla_raw_history_flag', ...
            need_keldysh_effective_nla_raw_history_flag, ...
        'checkpoint_diag_reassembly_flag', checkpoint_diag_reassembly_flag, ...
        'enable_drho_xz_diagnostics', enable_drho_xz_diagnostics, ...
        'ion_routine_flag', ion_routine_flag, ...
        'rho_nt_m3', frozen_cfg_rho_nt_m3, ...
        'ui', frozen_cfg_ui, ...
        'sigma_vec', sigma_vec, ...
        'sigma_aval_omega_fund', sigma_aval_omega_fund, ...
        'alpha_recombine', frozen_cfg_alpha_recombine, ...
        'plasma_z_rk2_flag_effective', plasma_z_rk2_flag_effective, ...
        'plasma_evolve_t_rk2_flag', plasma_evolve_t_rk2_flag, ...
        'dz_vec_all', dz_vec_all, ...
        'nl_index_3d', nl_index_3d, ...
        'omega_fund', omega_fund, ...
        'n2_kerr_disable_tol', n2_kerr_disable_tol, ...
        'kerr_enabled_flag', kerr_enabled_flag, ...
        'use_nlse_flag', use_nlse_flag, ...
        'qomega_3d', qomega_3d));
    submodel_warn_state = stepper_payloads.submodel_warn_state;
    vg_fund = stepper_payloads.vg_fund;
    core_idx = stepper_payloads.core_idx;
    step_runtime_ctx = stepper_payloads.step_runtime_ctx;
    plasma_runtime_cfg = stepper_payloads.plasma_runtime_cfg;
    nla_runtime_cfg = stepper_payloads.nla_runtime_cfg;
    dt_vec = stepper_payloads.dt_vec;
    last_operator_dz = stepper_payloads.last_operator_dz;
    kerr_n2_xy_in_step = stepper_payloads.kerr_n2_xy_in_step;

    setup_state = struct( ...
        'nla_runtime_cfg', nla_runtime_cfg, ...
        'run_warn_state', run_warn_state, ...
        'plasma_runtime_cfg', plasma_runtime_cfg, ...
        'rho_nt', rho_nt, ...
        'avalanche_branch_active_for_setup', avalanche_branch_active_for_setup, ...
        'plasma_z_rk2_flag_effective', plasma_z_rk2_flag_effective, ...
        'nla_z_rk2_flag_effective', nla_z_rk2_flag_effective, ...
        'plasma_evolve_t_rk2_flag', plasma_evolve_t_rk2_flag, ...
        'resolved_physics_policy', resolved_physics_policy, ...
        'submodel_warn_state', submodel_warn_state, ...
        'keldysh_effective_nla_available_flag', ...
            keldysh_effective_nla_available_flag, ...
        'need_keldysh_effective_nla_raw_history_flag', ...
            need_keldysh_effective_nla_raw_history_flag, ...
        'track_keldysh_effective_nla_diag_flag', ...
            track_keldysh_effective_nla_diag_flag, ...
        'vg_fund', vg_fund, ...
        'core_idx', core_idx, ...
        'step_runtime_ctx', step_runtime_ctx, ...
        'dt_vec', dt_vec, ...
        'last_operator_dz', last_operator_dz, ...
        'kerr_n2_xy_in_step', kerr_n2_xy_in_step, ...
        'setup_physics_rewrite_report', setup_physics_rewrite_report);
end

function submodel_cfgs = build_submodel_cfgs_local(cfg)
    plasma_z_rk2_flag_effective = cfg.fee_z_rk2_flag;
    if ~isempty(cfg.plasma_z_rk2_flag)
        plasma_z_rk2_flag_effective = struct_utils.normalize_bool_scalar( ...
            cfg.plasma_z_rk2_flag, 'plasma_z_rk2_flag', 'CerUPP:InvalidPlasmaZRk2Flag');
    end

    nla_z_rk2_flag_effective = plasma_z_rk2_flag_effective;
    if ~isempty(cfg.nla_z_rk2_flag)
        nla_z_rk2_flag_effective = struct_utils.normalize_bool_scalar( ...
            cfg.nla_z_rk2_flag, 'nla_z_rk2_flag', 'CerUPP:InvalidNlaZRk2Flag');
    end

    plasma_evolve_t_rk2_flag = struct_utils.normalize_bool_scalar( ...
        cfg.plasma_evolve_t_rk2_flag, ...
        'plasma_evolve_t_rk2_flag', 'CerUPP:InvalidPlasmaTimeRk2Flag');
    resolved_nla_runtime_closure = nla_support.resolve_closure_record( ...
        cfg.resolved_nla_setup_closure);
    resolved_nla_runtime_closure.rk_order_mode = 'explicit';
    resolved_nla_runtime_closure.rk_order = 1 + double(nla_z_rk2_flag_effective);

    nla_setup_opts = struct( ...
        'nla_use_ofi_rate_law_flag', cfg.nla_use_ofi_rate_law_flag, ...
        'keldysh_enabled', logical(cfg.keldysh_enabled), ...
        'plasma_ofi_use_remaining_neutral_factor_flag', ...
            logical(cfg.plasma_ofi_use_remaining_neutral_factor_flag), ...
        'ofi_branch_active', cfg.ofi_branch_active_for_setup, ...
        'nla_z_rk2_flag', nla_z_rk2_flag_effective, ...
        'nla_use_remaining_neutral_factor_flag', ...
            logical(cfg.nla_use_remaining_neutral_factor_flag), ...
        'nla_ofi_energy_accounting_mode', ...
            cfg.nla_ofi_energy_accounting_mode, ...
        'nla_check_ofi_event_energy_flag', ...
            logical(cfg.nla_check_ofi_event_energy_flag), ...
        'nla_use_ofi_event_depletion_flag', ...
            logical(cfg.nla_use_ofi_event_depletion_flag), ...
        'plasma_flag', logical(cfg.plasma_flag), ...
        'resolved_closure', resolved_nla_runtime_closure);
    [nla_runtime_cfg, run_warn_state, setup_physics_rewrite_report] = ...
        nla_support.build_runtime_cfg( ...
            cfg.ofi_k_orders, cfg.beta_k_vec, cfg.nl_absorption_flag, ...
            nla_setup_opts, struct(), cfg.run_warn_state, ...
            cfg.setup_physics_rewrite_report);

    plasma_runtime_cfg = cfg.plasma_runtime_cfg;
    [plasma_runtime_cfg.keldysh_cfg, plasma_setup_warn_state] = ...
        plasma_setup_support.detach_keldysh_warn_state_local( ...
            plasma_runtime_cfg.keldysh_cfg);
    submodel_warn_state = struct( ...
        'plasma', plasma_setup_warn_state, ...
        'nla', struct());
    rho_nt = cfg.rho_nt_m3;
    plasma_runtime_cfg.rho_nt_m3 = cfg.rho_nt_m3;
    plasma_runtime_cfg.Ui_J = cfg.ui;
    plasma_runtime_cfg.keldysh_matched_depletion_J = ...
        cfg.keldysh_matched_depletion_j;
    neutral_reservoir_cap_m3 = struct_utils.opt_struct_field( ...
        plasma_runtime_cfg, 'neutral_reservoir_cap_m3', ...
        struct_utils.opt_struct_field(plasma_runtime_cfg, 'rho_stage_cap', Inf));
    plasma_runtime_cfg.neutral_reservoir_m3 = ...
        plasma_setup_support.resolve_effective_neutral_reservoir_m3_local( ...
            cfg.rho_nt_m3, neutral_reservoir_cap_m3);
    avalanche_branch_active_for_setup = ...
        plasma_setup_support.is_avalanche_branch_active_local( ...
            cfg.plasma_flag, cfg.ion_routine_flag);

    [~, matched_ofi_nla_enabled] = ...
        nla_support.resolve_effective_closure_state(nla_runtime_cfg);
    ofi_context_needed_for_setup = ...
        logical(cfg.ofi_branch_active_for_setup) || logical(matched_ofi_nla_enabled);
    plasma_runtime_cfg.ofi_setup = plasma_setup_support.build_ofi_setup_static_local( ...
        plasma_runtime_cfg, cfg.ofi_k_orders, cfg.sigma_k_vec, ...
        ofi_context_needed_for_setup);
    nla_runtime_cfg = plasma_setup_support.attach_nla_runtime_closure_local( ...
        nla_runtime_cfg, plasma_runtime_cfg, cfg.rho_nt_keldysh_norm_m3);

    resolved_physics_policy = driver_setup_support.build_resolved_physics_policy_local( ...
        cfg.medium_spec, cfg.keldysh_convention_autoselect_used, ...
        cfg.ion_routine_flag_requested, cfg.ion_routine_flag, ...
        cfg.use_nlse_flag_requested, cfg.use_nlse_flag, ...
        cfg.nonparaxial_diffraction_order_requested, ...
        cfg.nonparaxial_diffraction_order, plasma_runtime_cfg.keldysh_cfg, ...
        cfg.ofi_branch_active_for_setup, avalanche_branch_active_for_setup, ...
        cfg.kerr_enabled_flag, ...
        setup_physics_rewrite_report);

    submodel_cfgs = struct( ...
        'run_warn_state', run_warn_state, ...
        'setup_physics_rewrite_report', setup_physics_rewrite_report, ...
        'plasma_runtime_cfg', plasma_runtime_cfg, ...
        'nla_runtime_cfg', nla_runtime_cfg, ...
        'submodel_warn_state', submodel_warn_state, ...
        'rho_nt', rho_nt, ...
        'avalanche_branch_active_for_setup', avalanche_branch_active_for_setup, ...
        'plasma_z_rk2_flag_effective', plasma_z_rk2_flag_effective, ...
        'nla_z_rk2_flag_effective', nla_z_rk2_flag_effective, ...
        'plasma_evolve_t_rk2_flag', plasma_evolve_t_rk2_flag, ...
        'resolved_physics_policy', resolved_physics_policy);
end

function setup_contract_state = finalize_setup_contract_local(cfg)
    [nla_closure_code_effective, matched_plasma_ofi_nla_enabled, ...
        nla_closure_effective] = nla_support.resolve_effective_closure_state( ...
        cfg.nla_runtime_cfg);
    resolved_nla_closure = nla_support.resolve_closure_record(cfg.nla_runtime_cfg);
    static_nla_closure_code = uint8(1);
    static_ofi_family_active = cfg.ofi_branch_active_for_setup && ...
        ~logical(cfg.keldysh_enabled);
    static_nla_family_active = logical(cfg.nl_absorption_flag) && ...
        (nla_closure_code_effective == static_nla_closure_code);

    keldysh_effective_nla_available_flag = logical(cfg.nl_absorption_flag) && ...
        logical(matched_plasma_ofi_nla_enabled) && ...
        plasma_setup_support.resolve_keldysh_effective_diag_enabled_local( ...
            cfg.plasma_runtime_cfg);
    % The matched-Keldysh trace family is available whenever the runtime
    % closure can emit it. The large raw [core,t,z] cubes keep a separate
    % flag so later output policy can slim storage without changing the
    % setup-time capability contract.
    need_keldysh_effective_nla_raw_history_flag = ...
        logical(keldysh_effective_nla_available_flag);
    track_keldysh_effective_nla_diag_flag = ...
        need_keldysh_effective_nla_raw_history_flag;
    run_warn_state = cfg.run_warn_state;
    if logical(matched_plasma_ofi_nla_enabled) && ...
            logical(struct_utils.opt_struct_field( ...
                resolved_nla_closure, ...
                'plasma_ofi_nla_weighting_mismatch_requested', false))
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, ...
            'setup', ...
            'plasma_ofi_nla_weighting_mismatch', ...
            'CerUPP:Physics:PlasmaOfiNlaWeightingMismatch', ...
            ['nla_use_ofi_rate_law_flag=true keeps the optical sink on the same OFI rate family as the plasma source, ', ...
             'but the weighting flags differ: plasma_ofi_use_remaining_neutral_factor_flag=%d while ', ...
             'nla_use_remaining_neutral_factor_flag=%d. CerUPP will honor them separately: the plasma source keeps its requested weighting, ', ...
             'and the OFI-based NLA sink keeps its own weighting.'], ...
            double(logical(struct_utils.opt_struct_field( ...
                resolved_nla_closure, ...
                'plasma_ofi_use_remaining_neutral_factor_flag', true))), ...
            double(logical(struct_utils.opt_struct_field( ...
                resolved_nla_closure, ...
                'nla_use_remaining_neutral_factor_flag_effective', false))));
    end
    if logical(cfg.keldysh_enabled) && logical(cfg.ofi_branch_active_for_setup) && ...
            logical(cfg.nl_absorption_flag) && ...
            (nla_closure_code_effective == static_nla_closure_code)
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, ...
            'setup', ...
            'keldysh_ofi_static_nla_hybrid_model', ...
            'CerUPP:Physics:KeldyshOfiStaticNlaHybrid', ...
            ['keldysh_enabled=true with plasma_flag=true and nl_absorption_flag=true uses a hybrid model: ' ...
             'electron generation follows dynamic Keldysh W_ion(I), while optical depletion stays on the static beta_K sink. ' ...
             'Set nla_use_ofi_rate_law_flag=true to keep the applied depletion tied to the same plasma OFI law.']);
    end
    run_warn_state = plasma_setup_support.emit_setup_keldysh_bookkeeping_warning_local( ...
        run_warn_state, cfg.plasma_runtime_cfg, ...
        cfg.keldysh_enabled, cfg.ofi_branch_active_for_setup, ...
        cfg.keldysh_display_k, cfg.ofi_k_orders, cfg.sigma_k_vec, ...
        nla_closure_effective, cfg.keldysh_lut_i_roi_min_effective);

    plasma_setup_support.print_effective_plasma_keldysh_params_local( ...
        cfg.medium_spec, cfg.medium_param_knobs_applied, ...
        cfg.keldysh_enabled, cfg.keldysh_display_k, ...
        cfg.resolved_keldysh_convention_desc, ...
        cfg.keldysh_convention_autoselect_used, ...
        cfg.keldysh_lut_i_roi_min_effective, ...
        cfg.ui, cfg.keldysh_gap_j, cfg.keldysh_matched_depletion_j, ...
        cfg.rho_nt_m3, cfg.rho_nt_keldysh_norm_m3, ...
        cfg.n_sell_fund, cfg.ofi_k_orders, cfg.sigma_k_vec, ...
        cfg.tau_c, cfg.alpha_recombine, ...
        cfg.keldysh_mred_over_me, cfg.plasma_m_over_me, cfg.m_plasma_kg, ...
        cfg.plasma_runtime_cfg, cfg.resolved_nla_setup_closure);
    driver_setup_support.print_report( ...
        cfg.resolved_physics_policy.setup_physics_rewrites);

    setup_contract_state = struct( ...
        'run_warn_state', run_warn_state, ...
        'keldysh_effective_nla_available_flag', ...
            keldysh_effective_nla_available_flag, ...
        'need_keldysh_effective_nla_raw_history_flag', ...
            need_keldysh_effective_nla_raw_history_flag, ...
        'track_keldysh_effective_nla_diag_flag', ...
            track_keldysh_effective_nla_diag_flag);
end

function stepper_payloads = build_stepper_payloads_local(cfg)
    % Only the grouped submodel warning ledgers remain mutable across
    % propagation steps. Freeze the stable step-facing runtime owner once here
    % and keep the same-dz operator fastpath obvious in cerupp.m.
    submodel_warn_state_in = struct_utils.opt_struct_field( ...
        cfg, 'submodel_warn_state', struct());
    submodel_warn_state = struct( ...
        'plasma', struct_utils.clone_warned_keys_map( ...
            struct_utils.ensure_warned_keys_map( ...
                struct_utils.opt_struct_field( ...
                    submodel_warn_state_in, 'plasma', struct()))), ...
        'nla', struct_utils.clone_warned_keys_map( ...
            struct_utils.ensure_warned_keys_map( ...
                struct_utils.opt_struct_field( ...
                    submodel_warn_state_in, 'nla', struct()))));

    dt_vec = diff(cfg.t(:));
    if any(~isfinite(dt_vec)) || any(dt_vec <= 0)
        error('CerUPP:InvalidTimeStepVector', ...
            'dt_vec derived from t must be strictly positive and finite.');
    end
    driver_setup_support.validate_omega_window_fft_order_local(cfg.omega_window);
    if ~isfinite(cfg.inv_vg_fund) || (cfg.inv_vg_fund <= 0)
        error('CerUPP:InvalidGroupVelocitySlope', ...
            'Computed inv_vg_fund is invalid during setup validation (%.6e).', ...
            cfg.inv_vg_fund);
    end
    vg_fund = 1 / cfg.inv_vg_fund;
    core_idx = propagation_support.validate_core_geometry_local( ...
        cfg.core_idx, cfg.mask_2_d, cfg.num_x_pts, cfg.num_y_pts);
    axis_linear_idx = sub2ind( ...
        [cfg.num_x_pts, cfg.num_y_pts], cfg.ix_axis0, cfg.iy_axis0);
    [axis_in_core, axis_core_row] = ismember(axis_linear_idx, core_idx(:));
    step_runtime_ctx = propagation_support.build_step_runtime_context_local( ...
        cfg.plasma_flag, cfg.nl_absorption_flag, cfg.diagnostics_flag, ...
        cfg.strict_stage_finite_scan_flag, false, ...
        cfg.keldysh_effective_nla_available_flag, ...
        cfg.need_keldysh_effective_nla_raw_history_flag, ...
        cfg.plasma_runtime_cfg, cfg.nla_runtime_cfg, ...
        cfg.checkpoint_diag_reassembly_flag, cfg.enable_drho_xz_diagnostics, ...
        cfg.omega_window, cfg.ion_routine_flag, cfg.rho_nt_m3, cfg.ui, ...
        cfg.sigma_vec, cfg.sigma_aval_omega_fund, cfg.alpha_recombine, ...
        core_idx, dt_vec, cfg.plasma_z_rk2_flag_effective, ...
        cfg.plasma_evolve_t_rk2_flag, axis_in_core, axis_core_row);
    last_operator_dz = double(cfg.dz_vec_all(1));

    kerr_n2_xy_in_step = propagation_support.build_kerr_step_payload_local( ...
        cfg.nl_index_3d, cfg.omega_window, cfg.omega_fund, ...
        cfg.n2_kerr_disable_tol, cfg.qomega_3d, cfg.use_nlse_flag, ...
        cfg.num_x_pts, cfg.num_y_pts, core_idx);

    stepper_payloads = struct( ...
        'submodel_warn_state', submodel_warn_state, ...
        'vg_fund', vg_fund, ...
        'core_idx', core_idx, ...
        'step_runtime_ctx', step_runtime_ctx, ...
        'plasma_runtime_cfg', cfg.plasma_runtime_cfg, ...
        'nla_runtime_cfg', cfg.nla_runtime_cfg, ...
        'dt_vec', dt_vec, ...
        'last_operator_dz', last_operator_dz, ...
        'kerr_n2_xy_in_step', kerr_n2_xy_in_step);
end
