function varargout = cerupp_section4_setup(varargin)
% Driver-only helper for the Section 4A final pre-loop setup pass.
% In the usual no-input mode this helper reads the current cerupp.m
% workspace, uses the already-frozen remaining Section 3 launch inputs,
% runs the late runtime/output settle helper, and allocates the stored-z
% arrays that Section 5 uses.
% To change the physics or output knobs, edit the visible setup blocks in
% cerupp.m instead of editing this helper.

    if nargin == 0
        caller_field_names = { ...
            'plot_warn_flag', ...
            'show_plots_flag', ...
            'show_3d_diagnostic_plots_flag', ...
            'make_initial_plots_flag', ...
            'save_outputs_as_fig_flag', ...
            'save_outputs_as_png_flag', ...
            'fwhm_fund', ...
            'td_pulse', ...
            't_center', ...
            'beta_chirp', ...
            'p_input', ...
            'dkx_offset_angle', ...
            'dky_offset_angle', ...
            'oam_charge1', ...
            'x_offset', ...
            'y_offset', ...
            'p_input_beam2', ...
            'dkx_offset_angle_beam2', ...
            'dky_offset_angle_beam2', ...
            'oam_charge_beam2', ...
            'x_offset_beam2', ...
            'y_offset_beam2', ...
            'rng_seed', ...
            'noise_amplitude', ...
            'w0', ...
            'p_input_w', ...
            'p_input_w_beam2', ...
            'i_laser_peak', ...
            'i_laser_peak_beam2', ...
            't0_gauss', ...
            'dkx_offset', ...
            'dky_offset', ...
            'dkx_offset_beam2', ...
            'dky_offset_beam2', ...
            'lambda_visible_band_min', ...
            'lambda_visible_band_max', ...
            'chromatic_onset_bin_width', ...
            'lambda_blue_band_min', ...
            'lambda_blue_band_max', ...
            'lambda_green_band_min', ...
            'lambda_green_band_max', ...
            'lambda_red_band_min', ...
            'lambda_red_band_max', ...
            'fundamental_band_half_width', ...
            'x', ...
            'y', ...
            't', ...
            'kx', ...
            'ky', ...
            'kperp', ...
            'lambda_window', ...
            'omega_window', ...
            'lambda_fund', ...
            'omega_fund', ...
            'omega_ref', ...
            'num_x_pts', ...
            'num_y_pts', ...
            'n', ...
            'delta_t', ...
            'delta_omega', ...
            'delta_x', ...
            'delta_y', ...
            'delta_kx', ...
            'delta_ky', ...
            'core_idx', ...
            'nu_sorted', ...
            'idx_nu', ...
            'eps_safe', ...
            'freq_offset', ...
            't_window', ...
            'z_domain', ...
            'A_xy', ...
            'mask', ...
            'mask_f', ...
            'mask_f_w', ...
            'mask_f_runtime', ...
            'mask_f_w_runtime', ...
            'mask_f_xy', ...
            'c', ...
            'propagation_medium_name', ...
            'kcut', ...
            'k_min_med', ...
            'mask_loss_warn_frac', ...
            'distance_to_propagate', ...
            'stepsize', ...
            'lambda_ref', ...
            'mask_pad_w', ...
            'mask_pad_x', ...
            'mask_pad_y', ...
            'spatial_inner_frac', ...
            'kperp_alpha', ...
            'kperp_ramp_frac', ...
            'kperp_nyquist_frac', ...
            'comp_window_x_width', ...
            'comp_window_y_width', ...
            'n_recompute_tol', ...
            'n2_recompute_tol', ...
            'core_radius', ...
            'n2_kerr', ...
            'plasma_flag', ...
            'nl_absorption_flag', ...
            'keldysh_enabled', ...
            'keldysh_use_interference_corrected_rate_flag', ...
            'plasma_z_rk2_flag', ...
            'nla_z_rk2_flag', ...
            'plasma_evolve_t_rk2_flag', ...
            'diagnostics_flag', ...
            'enable_setup_freeze_guard_flag', ...
            'center_i', ...
            'n_omega_fund_xy', ...
            'n_ratio_diag_xy', ...
            'n_sell', ...
            'diagnostic_band_cfg', ...
            'fluence_use_parseval', ...
            'setup_freeze_guard', ...
            'output_cfg', ...
            'perf_cfg', ...
            'cadence_cfg', ...
            'rebuild_policy', ...
            'plot_settings', ...
            'runtime_setup', ...
            'run_warn_state', ...
            'run_meta', ...
            'setup_physics_rewrite_report', ...
            'output_root', ...
            'run_tag', ...
            'append_timestamp_to_run_id', ...
            'archive_existing_run_output_root', ...
            'auto_timestamp_on_run_output_collision', ...
            'quick_debug_mode_flag', ...
            'enable_console_output_log_flag', ...
            'frozen_cfg_raw_startup_setup', ...
            'frozen_cfg_raw_section2_setup', ...
            'frozen_cfg_raw_section3_setup', ...
            'medium_spec', ...
            'resolved_keldysh_convention_desc', ...
            'keldysh_convention_autoselect_used', ...
            'selected_builtin_medium_family', ...
            'n2_air_placeholder_threshold', ...
            'keldysh_lut_i_roi_min', ...
            'keldysh_lut_i_roi_min_requested_raw', ...
            'keldysh_electron_effective_mass_over_me', ...
            'keldysh_hole_effective_mass_over_me', ...
            'ui', ...
            'keldysh_gap', ...
            'keldysh_matched_depletion', ...
            'rho_nt', ...
            'k_power_vec', ...
            'sigma_k_vec', ...
            'tau_c', ...
            'alpha_recombine', ...
            'plasma_m_over_me', ...
            'air_placeholder_ui', ...
            'air_placeholder_rho_nt', ...
            'air_placeholder_k_power', ...
            'air_placeholder_sigma_k', ...
            'keldysh_display_k_requested_raw', ...
            'keldysh_lookup_csv_name_requested_raw', ...
            'keldysh_display_k', ...
            'keldysh_use_interference_corrected_rate_flag', ...
            'plasma_ofi_use_remaining_neutral_factor_flag', ...
            'nla_use_remaining_neutral_factor_flag', ...
            'nla_ofi_energy_accounting_mode', ...
            'nla_check_ofi_event_energy_flag', ...
            'nla_use_ofi_event_depletion_flag', ...
            'keldysh_lookup_csv_name', ...
            'allow_keldysh_cache_reuse_without_match', ...
            'nla_use_ofi_rate_law_flag', ...
            'use_nlse_flag', ...
            'z_dependent_medium_flag', ...
            'allow_z_dependent_keldysh', ...
            'ion_routine_flag', ...
            'fee_z_rk2_flag', ...
            'use_exact_avalanche_exp_update_flag', ...
            'keldysh_lut_n_global', ...
            'keldysh_lut_n_roi', ...
            'keldysh_lut_i_global_min', ...
            'keldysh_zero_rate_below', ...
            'keldysh_lut_i_global_max', ...
            'keldysh_lut_i_roi_max', ...
            'rho_plasma_cap', ...
            'rho_neutral_supply', ...
            'raw_rho_plasma_cap', ...
            'raw_rho_neutral_supply', ...
            'simple_masks_flag', ...
            'nonparaxial_diffraction_order', ...
            'i_fil_cutoff', ...
            'i_fil_cutoff_vis', ...
            'rho_fil_cutoff', ...
            'frozen_cfg_ui', ...
            'frozen_cfg_keldysh_gap_j', ...
            'frozen_cfg_keldysh_matched_depletion_j', ...
            'medium_param_knobs_applied', ...
            'time_grid_supports_parseval_fluence', ...
            'lambda_nm', ...
            'plasma_runtime_cfg', ...
            'medium_cfg', ...
            'medium_cfg_defaults', ...
            'frozen_cfg_ofi_k_orders', ...
            'beta_k_vec', ...
            'frozen_cfg_sigma_k_vec', ...
            'frozen_cfg_rho_nt_m3', ...
            'frozen_cfg_rho_nt_keldysh_norm_m3', ...
            'frozen_cfg_neutral_reservoir_m3', ...
            'ion_routine_flag_requested', ...
            'use_nlse_flag_requested', ...
            'nonparaxial_diffraction_order_requested', ...
            'resolved_nla_setup_closure', ...
            'n_sell_fund', ...
            'frozen_cfg_tau_c', ...
            'frozen_cfg_alpha_recombine', ...
            'keldysh_mred_over_me', ...
            'm_plasma_kg', ...
            'inv_vg_fund', ...
            'mask_2_d', ...
            'diffraction_dispersion_matrix', ...
            'guiding_matrix', ...
            'lin_index_3d', ...
            'sigma_vec', ...
            'sigma_aval_omega_fund', ...
            'dz_vec_all', ...
            'nl_index_3d', ...
            'n2_kerr_disable_tol', ...
            'kerr_enabled_flag', ...
            'qomega_3d', ...
            'ofi_branch_active_for_setup', ...
            'keldysh_lut_i_roi_min_effective', ...
            'num_zsteps', ...
            't_setup'};
        caller_field_names = unique([ ...
            caller_field_names, ...
            driver_setup_support.runtime_output_visible_field_names_local()], 'stable');
        cfg = struct();
        for ii = 1:numel(caller_field_names)
            field_name = caller_field_names{ii};
            try
                cfg.(field_name) = evalin('caller', field_name);
            catch err
                if strcmp(err.identifier, 'MATLAB:UndefinedFunction') || ...
                        strcmp(err.identifier, 'MATLAB:UndefinedVariable')
                    error('CerUPP:MissingSection4CallerField', ...
                        ['cerupp_section4_setup expected caller variable ''%s'' ', ...
                         'to exist before the Section 4 helper call.'], ...
                        field_name);
                end
                rethrow(err);
            end
        end
        cfg.outdir = struct_utils.req_struct_field( ...
            cfg.runtime_setup, 'outdir', 'cerupp_section4_setup.runtime_setup');
        cfg.visible_runtime_knobs = ...
            driver_setup_support.build_visible_runtime_knobs_local(cfg);

        section4_state = build_section4_state_local(cfg);
        output_field_names = fieldnames(section4_state);
        for ii = 1:numel(output_field_names)
            field_name = output_field_names{ii};
            assignin('caller', field_name, section4_state.(field_name));
        end
        if nargout > 0
            varargout{1} = section4_state;
        end
        return;
    end

    if (nargin ~= 1) || ~isstruct(varargin{1}) || ~isscalar(varargin{1})
        error('CerUPP:InvalidSection4SetupCfg', ...
            'cerupp_section4_setup accepts either no inputs or one scalar cfg struct.');
    end

    section4_state = build_section4_state_local(varargin{1});
    if nargout > 1
        error('CerUPP:InvalidSection4SetupOutputCount', ...
            'cerupp_section4_setup returns at most one output struct.');
    end
    if nargout == 1
        varargout{1} = section4_state;
    end
end

function section4_state = build_section4_state_local(cfg)
    if ~(isstruct(cfg.diagnostic_band_cfg) && isscalar(cfg.diagnostic_band_cfg))
        error('CerUPP:InvalidSection4DiagnosticBandCfg', ...
            'Section 4 requires one validated diagnostic_band_cfg struct from the earlier Section 3 freeze capture.');
    end
    if ~(isstruct(cfg.frozen_cfg_raw_section3_setup) && isscalar(cfg.frozen_cfg_raw_section3_setup))
        error('CerUPP:InvalidSection4RawSection3Freeze', ...
            'Section 4 requires the earlier frozen_cfg_raw_section3_setup snapshot from the Block-3 capture.');
    end
    live_diagnostic_band_cfg = driver_setup_support.validate_diagnostic_band_cfg( ...
        cfg.diagnostic_band_cfg, 'cerupp_section4_setup live diagnostic_band_cfg');
    frozen_cfg_raw_section3_setup = cfg.frozen_cfg_raw_section3_setup;
    diagnostic_band_cfg = driver_setup_support.validate_diagnostic_band_cfg( ...
        struct_utils.req_struct_field( ...
            frozen_cfg_raw_section3_setup, 'diagnostic_band_cfg', ...
            'cerupp_section4_setup.frozen_cfg_raw_section3_setup'), ...
        'cerupp_section4_setup frozen diagnostic_band_cfg');
    setup_freeze_guard = cfg.setup_freeze_guard;
    visible_runtime_knobs = struct_utils.req_struct_field( ...
        cfg, 'visible_runtime_knobs', 'cerupp_section4_setup cfg');
    cfg.visible_runtime_knobs = visible_runtime_knobs;
    cfg.diagnostic_band_cfg_live = live_diagnostic_band_cfg;

    section3_setup_state = cerupp_section3d_setup( ...
        cfg, diagnostic_band_cfg, setup_freeze_guard, ...
        frozen_cfg_raw_section3_setup);

    grid_state = section3_setup_state.grid_state;
    output_plan = section3_setup_state.output_plan;
    output_dev_cfg = section3_setup_state.output_dev_cfg;
    perf_cfg = section3_setup_state.perf_cfg;
    A_S = section3_setup_state.A_S;
    core_idx = section3_setup_state.core_idx;
    phase_diagnostic_flag = section3_setup_state.phase_diagnostic_flag;
    keldysh_effective_nla_available_flag = ...
        section3_setup_state.keldysh_effective_nla_available_flag;
    need_keldysh_effective_nla_raw_history_flag = ...
        section3_setup_state.need_keldysh_effective_nla_raw_history_flag;
    track_keldysh_effective_nla_diag_flag = ...
        section3_setup_state.track_keldysh_effective_nla_diag_flag;
    [ix_axis0, iy_axis0, x_axis0, y_axis0] = struct_utils.unpack_struct_fields( ...
        grid_state, {'ix_axis0', 'iy_axis0', 'x_axis0', 'y_axis0'}, 'grid_state');
    num_storage_steps = ceil( ...
        cfg.num_zsteps / output_plan.cadence.diagnostic_store_stride_steps);

    section4a_state = storage_support.initialize_section4a_storage_state(struct( ...
        'grid_state', struct( ...
            'x', cfg.x, ...
            'y', cfg.y, ...
            'num_x_pts', cfg.num_x_pts, ...
            'num_y_pts', cfg.num_y_pts, ...
            'core_idx', core_idx, ...
            'n', cfg.n), ...
        'field_state', struct( ...
            'A_S', A_S, ...
            'A_xy', cfg.A_xy), ...
        'output_plan', output_plan, ...
        'setup_state', struct( ...
            'num_storage_steps', num_storage_steps, ...
            'omega_fund', cfg.omega_fund, ...
            'omega_ref', cfg.omega_ref, ...
            't', cfg.t, ...
            'num_zsteps', cfg.num_zsteps, ...
            'z_domain', cfg.z_domain, ...
            'n_ratio_diag_xy', cfg.n_ratio_diag_xy, ...
            't_setup', cfg.t_setup), ...
        'physics_state', struct( ...
            'phase_diagnostic_flag', phase_diagnostic_flag, ...
            'plasma_flag', cfg.plasma_flag, ...
            'nl_absorption_flag', cfg.nl_absorption_flag, ...
            'keldysh_effective_nla_available_flag', ...
                keldysh_effective_nla_available_flag, ...
            'need_keldysh_effective_nla_raw_history_flag', ...
                need_keldysh_effective_nla_raw_history_flag, ...
            'track_keldysh_effective_nla_diag_flag', ...
                track_keldysh_effective_nla_diag_flag, ...
            'keldysh_enabled', cfg.keldysh_enabled, ...
            'ofi_branch_active_for_setup', cfg.ofi_branch_active_for_setup), ...
        'perf_cfg', perf_cfg, ...
        'output_dev_cfg', output_dev_cfg));

    section4_state = section3_setup_state;
    section4_state.diagnostic_band_cfg = diagnostic_band_cfg;
    section4_state.ix_axis0 = ix_axis0;
    section4_state.iy_axis0 = iy_axis0;
    section4_state.x_axis0 = x_axis0;
    section4_state.y_axis0 = y_axis0;
    section4_state.num_storage_steps = num_storage_steps;
    section4_state.section5a_preloop_state = section4a_state;
end

function current_preplot_freeze_surfaces = build_current_preplot_freeze_surfaces_local(cfg)
    current_raw_startup_setup = driver_setup_support.build_raw_startup_setup_local(struct( ...
        'output_root', cfg.output_root, ...
        'run_tag', cfg.run_tag, ...
        'append_timestamp_to_run_id', cfg.append_timestamp_to_run_id, ...
        'archive_existing_run_output_root', cfg.archive_existing_run_output_root, ...
        'auto_timestamp_on_run_output_collision', ...
            cfg.auto_timestamp_on_run_output_collision, ...
        'quick_debug_mode_flag', cfg.quick_debug_mode_flag, ...
        'enable_console_output_log_flag', cfg.enable_console_output_log_flag));
    current_raw_medium_setup = driver_setup_support.build_raw_medium_setup_local( ...
        driver_setup_support.build_raw_medium_inputs_local(struct( ...
            'selected_builtin_medium_family', cfg.selected_builtin_medium_family, ...
            'n2_air_placeholder_threshold', cfg.n2_air_placeholder_threshold, ...
            'lambda_fund', cfg.lambda_fund, ...
            'core_radius', cfg.core_radius, ...
            'n2_kerr', cfg.n2_kerr, ...
            'n2_kerr_disable_tol', cfg.n2_kerr_disable_tol, ...
            'keldysh_lut_i_roi_min', cfg.keldysh_lut_i_roi_min_requested_raw, ...
            'keldysh_electron_effective_mass_over_me', ...
                cfg.keldysh_electron_effective_mass_over_me, ...
            'keldysh_hole_effective_mass_over_me', ...
                cfg.keldysh_hole_effective_mass_over_me, ...
            'ui', cfg.ui, ...
            'keldysh_gap', cfg.keldysh_gap, ...
            'keldysh_matched_depletion', cfg.keldysh_matched_depletion, ...
            'rho_nt', cfg.rho_nt, ...
            'k_power_vec', cfg.k_power_vec, ...
            'sigma_k_vec', cfg.sigma_k_vec, ...
            'tau_c', cfg.tau_c, ...
            'alpha_recombine', cfg.alpha_recombine, ...
            'plasma_flag', cfg.plasma_flag, ...
            'nl_absorption_flag', cfg.nl_absorption_flag, ...
            'nla_use_ofi_rate_law_flag', cfg.nla_use_ofi_rate_law_flag, ...
            'keldysh_enabled', cfg.keldysh_enabled, ...
            'plasma_m_over_me', cfg.plasma_m_over_me, ...
            'air_placeholder_ui', cfg.air_placeholder_ui, ...
            'air_placeholder_rho_nt', cfg.air_placeholder_rho_nt, ...
            'air_placeholder_k_power', cfg.air_placeholder_k_power, ...
            'air_placeholder_sigma_k', cfg.air_placeholder_sigma_k)));
    current_computational_setup_surface = ...
        driver_setup_support.build_computational_setup_surface_local(struct( ...
            'distance_to_propagate', cfg.distance_to_propagate, ...
            'stepsize', cfg.stepsize, ...
            't_window', cfg.t_window, ...
            'n', cfg.n, ...
            'lambda_ref', cfg.lambda_ref, ...
            'mask_pad_w', cfg.mask_pad_w, ...
            'mask_pad_x', cfg.mask_pad_x, ...
            'mask_pad_y', cfg.mask_pad_y, ...
            'spatial_inner_frac', cfg.spatial_inner_frac, ...
            'kperp_alpha', cfg.kperp_alpha, ...
            'kperp_ramp_frac', cfg.kperp_ramp_frac, ...
            'kperp_nyquist_frac', cfg.kperp_nyquist_frac, ...
            'mask_loss_warn_frac', cfg.mask_loss_warn_frac, ...
            'comp_window_x_width', cfg.comp_window_x_width, ...
            'num_x_pts', cfg.num_x_pts, ...
            'comp_window_y_width', cfg.comp_window_y_width, ...
            'num_y_pts', cfg.num_y_pts, ...
            'n_recompute_tol', cfg.n_recompute_tol, ...
            'n2_recompute_tol', cfg.n2_recompute_tol));
    current_raw_section2_setup = driver_setup_support.build_raw_section2_setup_local(struct( ...
        'plasma_flag', cfg.plasma_flag, ...
        'nl_absorption_flag', cfg.nl_absorption_flag, ...
        'keldysh_enabled', cfg.keldysh_enabled, ...
        'keldysh_use_interference_corrected_rate_flag', ...
            cfg.keldysh_use_interference_corrected_rate_flag, ...
        'keldysh_display_k', cfg.keldysh_display_k_requested_raw, ...
        'plasma_ofi_use_remaining_neutral_factor_flag', ...
            cfg.plasma_ofi_use_remaining_neutral_factor_flag, ...
        'nla_use_remaining_neutral_factor_flag', ...
            cfg.nla_use_remaining_neutral_factor_flag, ...
        'nla_ofi_energy_accounting_mode', ...
            cfg.nla_ofi_energy_accounting_mode, ...
        'nla_check_ofi_event_energy_flag', ...
            cfg.nla_check_ofi_event_energy_flag, ...
        'nla_use_ofi_event_depletion_flag', ...
            cfg.nla_use_ofi_event_depletion_flag, ...
        'keldysh_lookup_csv_name', ...
            cfg.keldysh_lookup_csv_name_requested_raw, ...
        'allow_keldysh_cache_reuse_without_match', ...
            cfg.allow_keldysh_cache_reuse_without_match, ...
        'nla_use_ofi_rate_law_flag', cfg.nla_use_ofi_rate_law_flag, ...
        'use_nlse_flag', cfg.use_nlse_flag, ...
        'z_dependent_medium_flag', cfg.z_dependent_medium_flag, ...
        'allow_z_dependent_keldysh', cfg.allow_z_dependent_keldysh, ...
        'ion_routine_flag', cfg.ion_routine_flag, ...
        'fee_z_rk2_flag', cfg.fee_z_rk2_flag, ...
        'plasma_z_rk2_flag', cfg.plasma_z_rk2_flag, ...
        'nla_z_rk2_flag', cfg.nla_z_rk2_flag, ...
        'plasma_evolve_t_rk2_flag', cfg.plasma_evolve_t_rk2_flag, ...
        'use_exact_avalanche_exp_update_flag', ...
            cfg.use_exact_avalanche_exp_update_flag, ...
            'keldysh_lut_n_global', cfg.keldysh_lut_n_global, ...
            'keldysh_lut_n_roi', cfg.keldysh_lut_n_roi, ...
            'keldysh_lut_i_global_min', cfg.keldysh_lut_i_global_min, ...
            'keldysh_zero_rate_below', cfg.keldysh_zero_rate_below, ...
            'keldysh_lut_i_global_max', cfg.keldysh_lut_i_global_max, ...
            'keldysh_lut_i_roi_max', cfg.keldysh_lut_i_roi_max, ...
            'rho_plasma_cap', cfg.raw_rho_plasma_cap, ...
        'rho_neutral_supply', cfg.raw_rho_neutral_supply, ...
        'simple_masks_flag', cfg.simple_masks_flag, ...
        'nonparaxial_diffraction_order', cfg.nonparaxial_diffraction_order, ...
        'i_fil_cutoff', cfg.i_fil_cutoff, ...
        'i_fil_cutoff_vis', cfg.i_fil_cutoff_vis, ...
        'rho_fil_cutoff', cfg.rho_fil_cutoff, ...
        'diagnostics_flag', cfg.diagnostics_flag, ...
        'checkpoint_diag_reassembly_flag', cfg.checkpoint_diag_reassembly_flag, ...
        'enable_drho_xz_diagnostics', cfg.enable_drho_xz_diagnostics, ...
        'reuse_linear_guiding_operator_cache_flag', ...
            cfg.reuse_linear_guiding_operator_cache_flag, ...
        'diagnostic_store_stride_steps', ...
            cfg.diagnostic_store_stride_steps, ...
        'checkpoint_stride_steps', cfg.checkpoint_stride_steps, ...
        'a_s_rho_snapshot_checkpoint_stride_steps', ...
            cfg.a_s_rho_snapshot_checkpoint_stride_steps, ...
        'memmon_projection_stride_steps', ...
            cfg.memmon_projection_stride_steps, ...
        'raw_medium_setup', current_raw_medium_setup, ...
        'computational_setup_surface', current_computational_setup_surface));
    current_setup_only_plot_controls = build_setup_only_plot_controls_local(struct( ...
        'plot_warn_flag', cfg.plot_warn_flag, ...
        'show_plots_flag', cfg.show_plots_flag, ...
        'show_3d_diagnostic_plots_flag', cfg.show_3d_diagnostic_plots_flag, ...
        'make_initial_plots_flag', cfg.make_initial_plots_flag, ...
        'save_outputs_as_fig_flag', cfg.save_outputs_as_fig_flag, ...
        'save_outputs_as_png_flag', cfg.save_outputs_as_png_flag));
    current_diagnostic_band_cfg = driver_setup_support.validate_diagnostic_band_cfg( ...
        driver_setup_support.build_raw_diagnostic_band_cfg_local(struct( ...
            'lambda_visible_band_min', cfg.lambda_visible_band_min, ...
            'lambda_visible_band_max', cfg.lambda_visible_band_max, ...
            'chromatic_onset_bin_width', cfg.chromatic_onset_bin_width, ...
            'lambda_blue_band_min', cfg.lambda_blue_band_min, ...
            'lambda_blue_band_max', cfg.lambda_blue_band_max, ...
            'lambda_green_band_min', cfg.lambda_green_band_min, ...
            'lambda_green_band_max', cfg.lambda_green_band_max, ...
            'lambda_red_band_min', cfg.lambda_red_band_min, ...
            'lambda_red_band_max', cfg.lambda_red_band_max, ...
            'lambda_fundamental_band_half_width', ...
                cfg.fundamental_band_half_width)), ...
        'cerupp_section4_setup current diagnostic_band_cfg');
    current_raw_section3_setup = driver_setup_support.build_raw_section3_setup_local(struct( ...
        'setup_plot_controls', struct( ...
            'plot_warn_flag', cfg.plot_warn_flag, ...
            'show_plots_flag', cfg.show_plots_flag, ...
            'show_3d_diagnostic_plots_flag', cfg.show_3d_diagnostic_plots_flag, ...
            'make_initial_plots_flag', cfg.make_initial_plots_flag, ...
            'save_outputs_as_fig_flag', cfg.save_outputs_as_fig_flag, ...
            'save_outputs_as_png_flag', cfg.save_outputs_as_png_flag), ...
        'launch', struct( ...
            'fwhm_fund', cfg.fwhm_fund, ...
            'td_pulse', cfg.td_pulse, ...
            't_center', cfg.t_center, ...
            'beta_chirp', cfg.beta_chirp, ...
            'p_input', cfg.p_input, ...
            'dkx_offset_angle', cfg.dkx_offset_angle, ...
            'dky_offset_angle', cfg.dky_offset_angle, ...
            'oam_charge1', cfg.oam_charge1, ...
            'x_offset', cfg.x_offset, ...
            'y_offset', cfg.y_offset, ...
            'p_input_beam2', cfg.p_input_beam2, ...
            'dkx_offset_angle_beam2', cfg.dkx_offset_angle_beam2, ...
            'dky_offset_angle_beam2', cfg.dky_offset_angle_beam2, ...
            'oam_charge_beam2', cfg.oam_charge_beam2, ...
            'x_offset_beam2', cfg.x_offset_beam2, ...
            'y_offset_beam2', cfg.y_offset_beam2, ...
            'rng_seed', cfg.rng_seed, ...
            'noise_amplitude', cfg.noise_amplitude), ...
        'diagnostic_band_cfg', current_diagnostic_band_cfg));
    current_preplot_freeze_surfaces = struct( ...
        'raw_startup_setup', current_raw_startup_setup, ...
        'raw_section2_setup', current_raw_section2_setup, ...
        'setup_only_plot_controls', current_setup_only_plot_controls, ...
        'raw_section3_setup', current_raw_section3_setup, ...
        'derived_launch_setup', struct( ...
            'w0', cfg.w0, ...
            'p_input_w', cfg.p_input_w, ...
            'p_input_w_beam2', cfg.p_input_w_beam2, ...
            'i_laser_peak', cfg.i_laser_peak, ...
            'i_laser_peak_beam2', cfg.i_laser_peak_beam2, ...
            't0_gauss', cfg.t0_gauss, ...
            'dkx_offset', cfg.dkx_offset, ...
            'dky_offset', cfg.dky_offset, ...
            'dkx_offset_beam2', cfg.dkx_offset_beam2, ...
            'dky_offset_beam2', cfg.dky_offset_beam2));
end

function setup_state = cerupp_section3d_setup( ...
        cfg, diagnostic_band_cfg, setup_freeze_guard, frozen_cfg_raw_section3_setup)
%CERUPP_SECTION3D_SETUP Internal helper for the late Section 4A setup pass.
% Build the z=0 launch state, finish the late Section 3 launch/runtime
% settle, finish the once-per-run plasma/NLA setup, and return the
% driver-owned state that cerupp_section4_setup.m uses for the remaining
% pre-loop allocation pass.

    if (nargin ~= 4) || ~isstruct(cfg) || ~isscalar(cfg)
        error('CerUPP:InvalidSection3DSetupInputs', ...
            ['cerupp_section3d_setup requires cfg, diagnostic_band_cfg, ', ...
             'setup_freeze_guard, and frozen_cfg_raw_section3_setup.']);
    end
    if ~isstruct(diagnostic_band_cfg) || ~isscalar(diagnostic_band_cfg)
        error('CerUPP:InvalidSection3DDiagnosticBandCfg', ...
            'cerupp_section3d_setup requires diagnostic_band_cfg as one scalar struct.');
    end
    if ~isstruct(frozen_cfg_raw_section3_setup) || ~isscalar(frozen_cfg_raw_section3_setup)
        error('CerUPP:InvalidSection3DRawSection3Setup', ...
            ['cerupp_section3d_setup requires frozen_cfg_raw_section3_setup ', ...
             'as one scalar struct.']);
    end
    if ~isstruct(setup_freeze_guard) || ~isscalar(setup_freeze_guard)
        error('CerUPP:InvalidSection3DSetupFreezeGuard', ...
            'cerupp_section3d_setup requires setup_freeze_guard as one scalar struct.');
    end

    visible_runtime_knobs = struct_utils.req_struct_field( ...
        cfg, 'visible_runtime_knobs', 'cerupp_section3d_setup cfg');

    [output_cfg, perf_cfg, cadence_cfg, plot_settings, runtime_setup, ...
        run_warn_state, run_meta, setup_physics_rewrite_report, ...
        frozen_cfg_raw_startup_setup, frozen_cfg_raw_section2_setup, ...
        diagnostic_band_cfg_live, ...
        fluence_use_parseval] = ...
        struct_utils.unpack_struct_fields(cfg, ...
        {'output_cfg', 'perf_cfg', 'cadence_cfg', 'plot_settings', ...
         'runtime_setup', 'run_warn_state', 'run_meta', ...
         'setup_physics_rewrite_report', 'frozen_cfg_raw_startup_setup', ...
         'frozen_cfg_raw_section2_setup', 'diagnostic_band_cfg_live', ...
         'fluence_use_parseval'}, ...
        'cerupp_section3d_setup cfg');

    [medium_spec, resolved_keldysh_convention_desc, ...
        keldysh_convention_autoselect_used, frozen_cfg_ui, ...
        frozen_cfg_keldysh_gap_j, frozen_cfg_keldysh_matched_depletion_j, ...
        medium_param_knobs_applied] = ...
        struct_utils.unpack_struct_fields(cfg, ...
        {'medium_spec', 'resolved_keldysh_convention_desc', ...
         'keldysh_convention_autoselect_used', 'frozen_cfg_ui', ...
         'frozen_cfg_keldysh_gap_j', 'frozen_cfg_keldysh_matched_depletion_j', ...
         'medium_param_knobs_applied'}, ...
        'cerupp_section3d_setup cfg');

    [time_grid_supports_parseval_fluence, lambda_nm] = ...
        struct_utils.unpack_struct_fields(cfg, ...
        {'time_grid_supports_parseval_fluence', 'lambda_nm'}, ...
        'cerupp_section3d_setup cfg');

    [plasma_runtime_cfg, medium_cfg, medium_cfg_defaults, ...
        frozen_cfg_ofi_k_orders, beta_k_vec, frozen_cfg_sigma_k_vec, ...
        frozen_cfg_rho_nt_m3, frozen_cfg_rho_nt_keldysh_norm_m3, ...
        ion_routine_flag_requested, use_nlse_flag_requested, ...
        nonparaxial_diffraction_order_requested, resolved_nla_setup_closure, ...
        n_sell_fund, frozen_cfg_tau_c, frozen_cfg_alpha_recombine, ...
        keldysh_mred_over_me, m_plasma_kg, propagation_medium_name, ...
        inv_vg_fund, mask_2_d, sigma_vec, sigma_aval_omega_fund, ...
        dz_vec_all, nl_index_3d, n2_kerr_disable_tol, ...
        kerr_enabled_flag, qomega_3d, ofi_branch_active_for_setup, ...
        keldysh_lut_i_roi_min_requested_raw, ...
        keldysh_lut_i_roi_min_effective] = ...
        struct_utils.unpack_struct_fields(cfg, ...
        {'plasma_runtime_cfg', 'medium_cfg', 'medium_cfg_defaults', ...
         'frozen_cfg_ofi_k_orders', 'beta_k_vec', 'frozen_cfg_sigma_k_vec', ...
         'frozen_cfg_rho_nt_m3', 'frozen_cfg_rho_nt_keldysh_norm_m3', ...
         'ion_routine_flag_requested', 'use_nlse_flag_requested', ...
         'nonparaxial_diffraction_order_requested', 'resolved_nla_setup_closure', ...
         'n_sell_fund', 'frozen_cfg_tau_c', 'frozen_cfg_alpha_recombine', ...
         'keldysh_mred_over_me', 'm_plasma_kg', 'propagation_medium_name', ...
         'inv_vg_fund', 'mask_2_d', 'sigma_vec', 'sigma_aval_omega_fund', ...
         'dz_vec_all', 'nl_index_3d', 'n2_kerr_disable_tol', ...
         'kerr_enabled_flag', 'qomega_3d', 'ofi_branch_active_for_setup', ...
         'keldysh_lut_i_roi_min_requested_raw', ...
         'keldysh_lut_i_roi_min_effective'}, ...
        'cerupp_section3d_setup cfg');

    % Recheck the already-frozen setup blocks before any more setup-time
    % work so late raw edits stop here rather than after the launch build
    % or optional initial-plot setup has already started.
    current_preplot_freeze_surfaces = build_current_preplot_freeze_surfaces_local(cfg);
    user_setup_guard.assert_selected_clean( ...
        setup_freeze_guard, current_preplot_freeze_surfaces);

    section2_medium_selector = struct_utils.req_struct_field( ...
        frozen_cfg_raw_section2_setup, 'medium_selector', ...
        'cerupp_section3d_setup.frozen_cfg_raw_section2_setup');
    section2_computational = struct_utils.req_struct_field( ...
        frozen_cfg_raw_section2_setup, 'computational', ...
        'cerupp_section3d_setup.frozen_cfg_raw_section2_setup');

    band_diagnostic_inputs = struct( ...
        'time_grid_supports_parseval_fluence', ...
            time_grid_supports_parseval_fluence, ...
        'diagnostic_band_cfg', diagnostic_band_cfg, ...
        'lambda_nm', lambda_nm, ...
        'lambda_fund', section2_medium_selector.lambda_fund, ...
        'omega_window', cfg.omega_window, ...
        'mask_f_w', cfg.mask_f_w, ...
        'c', cfg.c, ...
        'n', section2_computational.n, ...
        'delta_t', cfg.delta_t);

    [time_grid_supports_parseval_fluence, fundamental_band_support, ...
        mask_visible_band_3d, mask_fundamental_band_3d, ...
        mask_red_band_3d, mask_green_band_3d, mask_blue_band_3d, ...
        run_warn_state] = build_band_store_plan_inputs_local( ...
        band_diagnostic_inputs, run_warn_state);

    section2_physics_model = struct_utils.req_struct_field( ...
        frozen_cfg_raw_section2_setup, 'physics_model', ...
        'cerupp_section3d_setup.frozen_cfg_raw_section2_setup');
    section2_physics_solver = struct_utils.req_struct_field( ...
        frozen_cfg_raw_section2_setup, 'physics_solver', ...
        'cerupp_section3d_setup.frozen_cfg_raw_section2_setup');
    section2_step_runtime_diagnostics = struct_utils.req_struct_field( ...
        frozen_cfg_raw_section2_setup, 'step_runtime_diagnostics', ...
        'cerupp_section3d_setup.frozen_cfg_raw_section2_setup');
    section2_medium_defaults = struct_utils.req_struct_field( ...
        frozen_cfg_raw_section2_setup, 'medium_defaults', ...
        'cerupp_section3d_setup.frozen_cfg_raw_section2_setup');
    [plasma_flag, nl_absorption_flag, keldysh_enabled, ...
        keldysh_display_k, plasma_ofi_use_remaining_neutral_factor_flag, ...
        nla_use_remaining_neutral_factor_flag, nla_use_ofi_rate_law_flag, ...
        nla_ofi_energy_accounting_mode, ...
        nla_check_ofi_event_energy_flag, nla_use_ofi_event_depletion_flag, ...
        use_nlse_flag, ion_routine_flag] = struct_utils.unpack_struct_fields( ...
        section2_physics_model, ...
        {'plasma_flag', 'nl_absorption_flag', 'keldysh_enabled', ...
         'keldysh_display_k', ...
         'plasma_ofi_use_remaining_neutral_factor_flag', ...
         'nla_use_remaining_neutral_factor_flag', ...
         'nla_use_ofi_rate_law_flag', ...
         'nla_ofi_energy_accounting_mode', ...
         'nla_check_ofi_event_energy_flag', ...
         'nla_use_ofi_event_depletion_flag', 'use_nlse_flag', ...
         'ion_routine_flag'}, ...
        'cerupp_section3d_setup.frozen_cfg_raw_section2_setup.physics_model');
    [fee_z_rk2_flag, plasma_z_rk2_flag, nla_z_rk2_flag, ...
        plasma_evolve_t_rk2_flag, diagnostics_flag, ...
        nonparaxial_diffraction_order] = struct_utils.unpack_struct_fields( ...
        driver_setup_support.merge_scalar_structs_local( ...
            section2_physics_solver, section2_step_runtime_diagnostics), ...
        {'fee_z_rk2_flag', 'plasma_z_rk2_flag', 'nla_z_rk2_flag', ...
         'plasma_evolve_t_rk2_flag', 'diagnostics_flag', ...
         'nonparaxial_diffraction_order'}, ...
        ['cerupp_section3d_setup.frozen_cfg_raw_section2_setup.', ...
         'physics_solver+step_runtime_diagnostics']);
    plasma_m_over_me = struct_utils.req_struct_field( ...
        section2_medium_defaults, 'plasma_m_over_me', ...
        'cerupp_section3d_setup.frozen_cfg_raw_section2_setup.medium_defaults');

    grid_state = build_grid_state_local(struct( ...
        'x', cfg.x, ...
        'y', cfg.y, ...
        't', cfg.t, ...
        'kx', cfg.kx, ...
        'ky', cfg.ky, ...
        'kperp', cfg.kperp, ...
        'lambda_window', cfg.lambda_window, ...
        'omega_window', cfg.omega_window, ...
        'lambda_fund', section2_medium_selector.lambda_fund, ...
        'omega_fund', cfg.omega_fund, ...
        'num_x_pts', section2_computational.num_x_pts, ...
        'num_y_pts', section2_computational.num_y_pts, ...
        'n', section2_computational.n, ...
        'delta_t', cfg.delta_t, ...
        'delta_omega', cfg.delta_omega, ...
        'delta_x', cfg.delta_x, ...
        'delta_y', cfg.delta_y, ...
        'delta_kx', cfg.delta_kx, ...
        'delta_ky', cfg.delta_ky, ...
        'core_idx', cfg.core_idx, ...
        'nu_sorted', cfg.nu_sorted, ...
        'idx_nu', cfg.idx_nu, ...
        'eps_safe', cfg.eps_safe, ...
        'freq_offset', cfg.freq_offset, ...
        't_window', cfg.t_window, ...
        'z_domain', cfg.z_domain));
    [x, y, t, omega_window, omega_fund, num_x_pts, num_y_pts, core_idx] = ...
        struct_utils.unpack_struct_fields(grid_state, ...
        {'x', 'y', 't', 'omega_window', 'omega_fund', ...
         'num_x_pts', 'num_y_pts', 'core_idx'}, ...
        'cerupp_section3d_setup.grid_state');

    [grid_state, A_S, A_SSF, A_F, run_warn_state] = ...
        build_launch_state_local(grid_state, struct( ...
            'A_xy', cfg.A_xy, ...
            'fwhm_fund', cfg.fwhm_fund, ...
            'mask', cfg.mask, ...
            'mask_f', cfg.mask_f, ...
            'mask_f_w', cfg.mask_f_w, ...
            'mask_f_runtime', cfg.mask_f_runtime, ...
            'mask_f_w_runtime', cfg.mask_f_w_runtime, ...
            'mask_f_xy', cfg.mask_f_xy, ...
            'c', cfg.c, ...
            'n_sell', cfg.n_sell, ...
            'kcut', cfg.kcut, ...
            'k_min_med', cfg.k_min_med, ...
            'mask_loss_warn_frac', cfg.mask_loss_warn_frac), ...
            run_warn_state);

    if output_cfg.make_initial_plots_flag
        initial_plot_state = build_initial_plot_state_local( ...
            struct( ...
                'x', cfg.x, ...
                'y', cfg.y, ...
                't', cfg.t, ...
                'kx', cfg.kx, ...
                'ky', cfg.ky, ...
                'kperp', cfg.kperp, ...
                'lambda_window', cfg.lambda_window, ...
                'omega_window', cfg.omega_window, ...
                'lambda_fund', cfg.lambda_fund, ...
                'omega_fund', cfg.omega_fund, ...
                'num_x_pts', cfg.num_x_pts, ...
                'num_y_pts', cfg.num_y_pts, ...
                'n', cfg.n, ...
                'delta_t', cfg.delta_t, ...
                'delta_omega', cfg.delta_omega, ...
                'delta_x', cfg.delta_x, ...
                'delta_y', cfg.delta_y, ...
                'delta_kx', cfg.delta_kx, ...
                'delta_ky', cfg.delta_ky, ...
                'core_idx', cfg.core_idx, ...
                'nu_sorted', cfg.nu_sorted, ...
                'idx_nu', cfg.idx_nu, ...
                'eps_safe', cfg.eps_safe, ...
                'freq_offset', cfg.freq_offset, ...
                't_window', cfg.t_window, ...
                'z_domain', cfg.z_domain), ...
            struct( ...
                'A_xy', cfg.A_xy, ...
                'center_i', cfg.center_i, ...
                'n_omega_fund_xy', cfg.n_omega_fund_xy, ...
                'n_ratio_diag_xy', cfg.n_ratio_diag_xy, ...
                'n_sell', cfg.n_sell, ...
                'propagation_medium_name', cfg.propagation_medium_name, ...
                'c', cfg.c), ...
            plot_settings, run_warn_state);
        run_warn_state = plot_utils.run_initial_setup_plots(initial_plot_state);
    end

    % 4A-I. Freeze the late runtime/output raw knobs, then settle them into
    % the built late runtime/output setup.
    % The 4A/4B/4C/4D/4E labels below are internal subcaptures of the one
    % late Block-4 freeze stage, not extra user-facing freeze blocks.
    [perf_cfg, output_cfg, cadence_cfg, plot_settings, ...
        fluence_use_parseval_requested, fluence_use_parseval, ...
        fluence_method_name_requested, fluence_method_name, ...
        raw_runtime_output_setup_current] = ...
        driver_setup_support.settle_late_runtime_output_cfg_local(struct( ...
            'visible_runtime_knobs', visible_runtime_knobs, ...
            'frozen_cfg_raw_startup_setup', frozen_cfg_raw_startup_setup, ...
            'frozen_cfg_raw_section2_setup', frozen_cfg_raw_section2_setup, ...
            'frozen_cfg_raw_section3_setup', frozen_cfg_raw_section3_setup, ...
            'perf_cfg', perf_cfg, ...
            'output_cfg', output_cfg, ...
            'outdir', runtime_setup.outdir));
    setup_freeze_guard = user_setup_guard.capture_surface( ...
        setup_freeze_guard, 'raw_runtime_output_setup', ...
        ['Freeze block 4A/4 (late runtime/output raw knobs) before Section 4A ', ...
         'settles the selected monitor cadence, saved-file settings, and output plan'], ...
        raw_runtime_output_setup_current);
    keldysh_runtime_branch_summary = run_meta.keldysh_runtime_branch_summary;
    [resolved_output_policy, phase_diagnostic_flag, ...
        strict_stage_finite_scan_flag, run_meta, run_warn_state, ...
        perf_cfg] = driver_setup_support.resolve_nonphysics_setup_local( ...
        struct( ...
            'output_cfg', output_cfg, ...
            'perf_cfg', perf_cfg, ...
            'quick_debug_mode_flag', ...
                frozen_cfg_raw_startup_setup.early_run_mode.quick_debug_mode_flag, ...
            'enable_setup_freeze_guard_flag', ...
                cfg.enable_setup_freeze_guard_flag, ...
            'run_warn_state', run_warn_state, ...
            'release_version', runtime_setup.release_version, ...
            'curr_cerupp_version', runtime_setup.curr_cerupp_version, ...
            'restart_compat_version', runtime_setup.restart_compat_version, ...
            'output_root_resolved', runtime_setup.output_root_resolved, ...
            'run_bucket', runtime_setup.run_bucket, ...
            'run_output_root', runtime_setup.run_output_root, ...
            'append_timestamp_to_run_id', runtime_setup.append_timestamp_to_run_id, ...
            'archive_existing_run_output_root', runtime_setup.archive_existing_run_output_root, ...
            'auto_timestamp_on_run_output_collision', ...
                runtime_setup.auto_timestamp_on_run_output_collision, ...
            'auto_timestamped_run_output_root', runtime_setup.auto_timestamped_run_output_root, ...
            'fluence_use_parseval_requested', fluence_use_parseval_requested, ...
            'fluence_use_parseval', fluence_use_parseval, ...
            'fluence_method_name_requested', fluence_method_name_requested, ...
            'fluence_method_name', fluence_method_name, ...
            'medium_spec', medium_spec, ...
            'resolved_keldysh_convention_desc', resolved_keldysh_convention_desc, ...
            'keldysh_convention_autoselect_used', keldysh_convention_autoselect_used, ...
            'nl_absorption_flag', nl_absorption_flag, ...
            'nla_use_ofi_rate_law_flag', nla_use_ofi_rate_law_flag, ...
            'keldysh_enabled', keldysh_enabled, ...
            'keldysh_lut_n_global', cfg.keldysh_lut_n_global, ...
            'keldysh_lut_n_roi', cfg.keldysh_lut_n_roi, ...
            'frozen_cfg_ui', frozen_cfg_ui, ...
            'frozen_cfg_keldysh_gap_j', frozen_cfg_keldysh_gap_j, ...
            'frozen_cfg_keldysh_matched_depletion_j', frozen_cfg_keldysh_matched_depletion_j, ...
            'lambda_fund', cfg.lambda_fund, ...
            'omega_fund', cfg.omega_fund, ...
            'rho_neutral_supply', cfg.rho_neutral_supply, ...
            'rho_plasma_cap', cfg.rho_plasma_cap, ...
            'frozen_cfg_neutral_reservoir_m3', ...
                cfg.frozen_cfg_neutral_reservoir_m3, ...
            'medium_param_knobs_applied', medium_param_knobs_applied));
    run_meta.keldysh_runtime_branch_summary = keldysh_runtime_branch_summary;

    [store_diag_plan, store_band_plan] = ...
        driver_setup_support.build_store_plans_local( ...
        output_cfg, resolved_output_policy, phase_diagnostic_flag, ...
        fluence_use_parseval, time_grid_supports_parseval_fluence, ...
        fundamental_band_support, ...
        mask_visible_band_3d, mask_fundamental_band_3d, ...
        mask_red_band_3d, mask_green_band_3d, mask_blue_band_3d);
    output_plan = driver_setup_support.build_output_plan_local( ...
        output_cfg, resolved_output_policy, store_diag_plan, ...
        store_band_plan, cadence_cfg);
    output_dev_cfg = struct_utils.req_struct_field( ...
        struct_utils.req_struct_field(output_plan, 'request', ...
            'cerupp_section3d_setup.output_plan'), ...
        'dev', 'cerupp_section3d_setup.output_plan.request');
    effective_runtime_output_setup = ...
        driver_setup_support.build_effective_runtime_output_setup_local( ...
        perf_cfg, output_cfg, cadence_cfg, plot_settings, ...
        fluence_use_parseval_requested, fluence_use_parseval, ...
        fluence_method_name_requested, fluence_method_name, ...
        phase_diagnostic_flag, strict_stage_finite_scan_flag, output_plan);

    % 4A-II. Record the settled Section 4A runtime/output bundle for the
    % final pre-loop owner-drift check.
    setup_freeze_guard = user_setup_guard.capture_surface( ...
        setup_freeze_guard, 'effective_runtime_output_setup', ...
        ['Freeze block 4B/4 (settled Section 4A runtime/output bundle) after ', ...
         'Section 4A finishes the selected output plan, monitor cadence, and plot settings'], ...
        effective_runtime_output_setup);


    % With the late runtime/output policy now settled, finish the once-per-run
    % plasma/NLA helper work that depends on the selected diagnostics/output
    % configuration as well as the already-built Keldysh runtime object.
    plasma_ofi_nla_setup_state = build_plasma_ofi_nla_step_inputs(struct( ...
        'plasma_runtime_cfg', plasma_runtime_cfg, ...
        'fee_z_rk2_flag', fee_z_rk2_flag, ...
        'plasma_z_rk2_flag', plasma_z_rk2_flag, ...
        'nla_z_rk2_flag', nla_z_rk2_flag, ...
        'plasma_evolve_t_rk2_flag', plasma_evolve_t_rk2_flag, ...
        'nla_use_ofi_rate_law_flag', nla_use_ofi_rate_law_flag, ...
        'keldysh_enabled', keldysh_enabled, ...
        'plasma_ofi_use_remaining_neutral_factor_flag', ...
            plasma_ofi_use_remaining_neutral_factor_flag, ...
        'ofi_branch_active_for_setup', ofi_branch_active_for_setup, ...
        'nla_use_remaining_neutral_factor_flag', ...
            nla_use_remaining_neutral_factor_flag, ...
        'nla_ofi_energy_accounting_mode', ...
            nla_ofi_energy_accounting_mode, ...
        'nla_check_ofi_event_energy_flag', ...
            nla_check_ofi_event_energy_flag, ...
        'nla_use_ofi_event_depletion_flag', ...
            nla_use_ofi_event_depletion_flag, ...
        'frozen_cfg_ofi_k_orders', frozen_cfg_ofi_k_orders, ...
        'beta_k_vec', beta_k_vec, ...
        'nl_absorption_flag', nl_absorption_flag, ...
        'run_warn_state', run_warn_state, ...
        'setup_physics_rewrite_report', setup_physics_rewrite_report, ...
        'frozen_cfg_rho_nt_m3', frozen_cfg_rho_nt_m3, ...
        'plasma_flag', plasma_flag, ...
        'ion_routine_flag', ion_routine_flag, ...
        'frozen_cfg_sigma_k_vec', frozen_cfg_sigma_k_vec, ...
        'frozen_cfg_rho_nt_keldysh_norm_m3', ...
            frozen_cfg_rho_nt_keldysh_norm_m3, ...
        'medium_spec', medium_spec, ...
        'keldysh_convention_autoselect_used', ...
            keldysh_convention_autoselect_used, ...
        'ion_routine_flag_requested', ion_routine_flag_requested, ...
        'use_nlse_flag_requested', use_nlse_flag_requested, ...
        'use_nlse_flag', use_nlse_flag, ...
        'nonparaxial_diffraction_order_requested', ...
            nonparaxial_diffraction_order_requested, ...
        'nonparaxial_diffraction_order', nonparaxial_diffraction_order, ...
        'resolved_nla_setup_closure', resolved_nla_setup_closure, ...
        'keldysh_display_k', keldysh_display_k, ...
        'keldysh_lut_i_roi_min_requested_raw', ...
            keldysh_lut_i_roi_min_requested_raw, ...
        'keldysh_lut_i_roi_min_effective', ...
            keldysh_lut_i_roi_min_effective, ...
        'medium_param_knobs_applied', medium_param_knobs_applied, ...
        'resolved_keldysh_convention_desc', ...
            resolved_keldysh_convention_desc, ...
        'frozen_cfg_ui', frozen_cfg_ui, ...
        'frozen_cfg_keldysh_gap_j', frozen_cfg_keldysh_gap_j, ...
        'frozen_cfg_keldysh_matched_depletion_j', ...
            frozen_cfg_keldysh_matched_depletion_j, ...
        'n_sell_fund', n_sell_fund, ...
        'frozen_cfg_tau_c', frozen_cfg_tau_c, ...
        'frozen_cfg_alpha_recombine', frozen_cfg_alpha_recombine, ...
        'keldysh_mred_over_me', keldysh_mred_over_me, ...
        'plasma_m_over_me', plasma_m_over_me, ...
        'm_plasma_kg', m_plasma_kg, ...
        'propagation_medium_name', propagation_medium_name, ...
        'x', x, ...
        'y', y, ...
        't', t, ...
        'omega_window', omega_window, ...
        'inv_vg_fund', inv_vg_fund, ...
        'core_idx', core_idx, ...
        'mask_2_d', mask_2_d, ...
        'num_x_pts', num_x_pts, ...
        'num_y_pts', num_y_pts, ...
        'diagnostics_flag', diagnostics_flag, ...
        'strict_stage_finite_scan_flag', strict_stage_finite_scan_flag, ...
        'checkpoint_diag_reassembly_flag', ...
            output_cfg.checkpoint_diag_reassembly_flag, ...
        'enable_drho_xz_diagnostics', ...
            output_dev_cfg.enable_drho_xz_diagnostics, ...
        'sigma_vec', sigma_vec, ...
        'sigma_aval_omega_fund', sigma_aval_omega_fund, ...
        'dz_vec_all', dz_vec_all, ...
        'nl_index_3d', nl_index_3d, ...
        'omega_fund', omega_fund, ...
        'n2_kerr_disable_tol', n2_kerr_disable_tol, ...
        'kerr_enabled_flag', kerr_enabled_flag, ...
        'qomega_3d', qomega_3d));
    [nla_runtime_cfg, run_warn_state, plasma_runtime_cfg, rho_nt, ...
        avalanche_branch_active_for_setup, plasma_z_rk2_flag_effective, ...
        nla_z_rk2_flag_effective, plasma_evolve_t_rk2_flag, ...
        resolved_physics_policy, submodel_warn_state, ...
        keldysh_effective_nla_available_flag, ...
        need_keldysh_effective_nla_raw_history_flag, ...
        track_keldysh_effective_nla_diag_flag, vg_fund, core_idx, ...
        step_runtime_ctx, dt_vec, last_operator_dz, ...
        kerr_n2_xy_in_step, setup_physics_rewrite_report] = ...
        struct_utils.unpack_struct_fields(plasma_ofi_nla_setup_state, ...
        {'nla_runtime_cfg', 'run_warn_state', 'plasma_runtime_cfg', ...
         'rho_nt', 'avalanche_branch_active_for_setup', ...
         'plasma_z_rk2_flag_effective', 'nla_z_rk2_flag_effective', ...
         'plasma_evolve_t_rk2_flag', 'resolved_physics_policy', ...
         'submodel_warn_state', 'keldysh_effective_nla_available_flag', ...
         'need_keldysh_effective_nla_raw_history_flag', ...
         'track_keldysh_effective_nla_diag_flag', ...
         'vg_fund', 'core_idx', 'step_runtime_ctx', 'dt_vec', ...
         'last_operator_dz', 'kerr_n2_xy_in_step', ...
         'setup_physics_rewrite_report'}, ...
        'cerupp_section3d_setup.plasma_ofi_nla_setup_state');


    % 4A-III. Thread the finalized setup summary into run metadata.
    setup_diagnostics_meta = ...
        driver_setup_support.build_setup_diagnostics_meta_local( ...
        diagnostic_band_cfg, ...
        output_cfg, resolved_output_policy, ...
        fluence_use_parseval_requested, fluence_use_parseval, ...
        fluence_method_name_requested, fluence_method_name, ...
        time_grid_supports_parseval_fluence, cadence_cfg);
    rebuild_policy = struct_utils.opt_struct_field( ...
        cfg, 'rebuild_policy', struct(), ...
        'treat_empty_as_missing', true);
    if isempty(rebuild_policy)
        rebuild_policy = driver_setup_support.build_rebuild_policy_local(struct( ...
            'z_dependent_medium_flag', struct_utils.req_struct_field( ...
                section2_physics_model, 'z_dependent_medium_flag', ...
                'cerupp_section4_setup.frozen_cfg_raw_section2_setup.physics_model'), ...
            'allow_z_dependent_keldysh', struct_utils.req_struct_field( ...
                section2_physics_model, 'allow_z_dependent_keldysh', ...
                'cerupp_section4_setup.frozen_cfg_raw_section2_setup.physics_model'), ...
            'keldysh_enabled', keldysh_enabled));
    end
    resolved_setup_contract = ...
        driver_setup_support.build_resolved_setup_contract_local( ...
        run_meta, setup_diagnostics_meta, resolved_physics_policy, ...
        plasma_runtime_cfg.keldysh_cfg, nla_runtime_cfg, ...
        ofi_branch_active_for_setup, avalanche_branch_active_for_setup, ...
        rebuild_policy);
    run_meta = driver_setup_support.attach_resolved_setup_contract_local( ...
        run_meta, resolved_setup_contract, store_diag_plan);

    setup_freeze_guard = user_setup_guard.capture_surface( ...
        setup_freeze_guard, 'built_launch_state', ...
        ['Freeze block 4C/4 (built launch field state) after Section 4A ', ...
         'finishes the settled A_S / A_SSF / A_F launch arrays that ', ...
         'the propagation loop will launch directly'], ...
        driver_setup_support.build_built_launch_state_freeze_surface_local(struct( ...
            'A_S', A_S, ...
            'A_SSF', A_SSF, ...
            'A_F', A_F)));
    setup_freeze_guard = user_setup_guard.capture_surface( ...
        setup_freeze_guard, 'built_propagation_state', ...
        ['Freeze block 4D/4 (built propagation operator and mask state) ', ...
         'after Section 4A settles the pre-loop operators, absorber mask, and ', ...
         'core support that the first propagation step will reuse'], ...
        driver_setup_support.build_built_propagation_state_freeze_surface_local(struct( ...
            'core_idx', core_idx, ...
            'lin_index_3d', cfg.lin_index_3d, ...
            'nl_index_3d', nl_index_3d, ...
            'mask', cfg.mask, ...
            'mask_2_d', mask_2_d, ...
            'sigma_vec', sigma_vec, ...
            'diffraction_dispersion_matrix', ...
                cfg.diffraction_dispersion_matrix, ...
            'guiding_matrix', cfg.guiding_matrix, ...
            'qomega_3d', qomega_3d, ...
            'mask_f', cfg.mask_f, ...
            'mask_f_w', cfg.mask_f_w)));
    % Record the settled runtime-physics templates that propagation reuses
    % directly so the final pre-loop guard can stop if they are edited
    % after Section 4 has already built them.
    setup_freeze_guard = user_setup_guard.capture_surface( ...
        setup_freeze_guard, 'effective_runtime_physics_setup', ...
        ['Freeze block 4E/4 (settled runtime physics templates) after ', ...
         'Section 4A finishes the prebuilt plasma/NLA/runtime state used ', ...
         'directly by propagation'], ...
        driver_setup_support.build_effective_runtime_physics_setup_freeze_surface_local(struct( ...
            'plasma_runtime_cfg', plasma_runtime_cfg, ...
            'nla_runtime_cfg', nla_runtime_cfg, ...
            'step_runtime_ctx', step_runtime_ctx, ...
            'kerr_n2_xy_in_step', kerr_n2_xy_in_step, ...
            'resolved_setup_contract', resolved_setup_contract, ...
            'resolved_physics_policy', resolved_physics_policy)));

    setup_state = struct( ...
        'grid_state', grid_state, ...
        'A_S', A_S, ...
        'A_SSF', A_SSF, ...
        'A_F', A_F, ...
        'frozen_cfg_raw_section3_setup', frozen_cfg_raw_section3_setup, ...
        'setup_freeze_guard', setup_freeze_guard, ...
        'run_warn_state', run_warn_state, ...
        'perf_cfg', perf_cfg, ...
        'output_cfg', output_cfg, ...
        'cadence_cfg', cadence_cfg, ...
        'plot_settings', plot_settings, ...
        'fluence_use_parseval_requested', fluence_use_parseval_requested, ...
        'fluence_use_parseval', fluence_use_parseval, ...
        'fluence_method_name_requested', fluence_method_name_requested, ...
        'fluence_method_name', fluence_method_name, ...
        'time_grid_supports_parseval_fluence', ...
            time_grid_supports_parseval_fluence, ...
        'fundamental_band_support', fundamental_band_support, ...
        'phase_diagnostic_flag', phase_diagnostic_flag, ...
        'strict_stage_finite_scan_flag', strict_stage_finite_scan_flag, ...
        'run_meta', run_meta, ...
        'output_plan', output_plan, ...
        'output_dev_cfg', output_dev_cfg, ...
        'effective_runtime_output_setup', effective_runtime_output_setup, ...
        'setup_diagnostics_meta', setup_diagnostics_meta, ...
        'resolved_setup_contract', resolved_setup_contract, ...
        'plasma_runtime_cfg', plasma_runtime_cfg, ...
        'nla_runtime_cfg', nla_runtime_cfg, ...
        'rho_nt', rho_nt, ...
        'avalanche_branch_active_for_setup', avalanche_branch_active_for_setup, ...
        'submodel_warn_state', submodel_warn_state, ...
        'keldysh_effective_nla_available_flag', ...
            keldysh_effective_nla_available_flag, ...
        'need_keldysh_effective_nla_raw_history_flag', ...
            need_keldysh_effective_nla_raw_history_flag, ...
        'track_keldysh_effective_nla_diag_flag', ...
            track_keldysh_effective_nla_diag_flag, ...
        'vg_fund', vg_fund, ...
        'core_idx', core_idx, ...
        'step_runtime_ctx', step_runtime_ctx, ...
        'dt_vec', dt_vec, ...
        'last_operator_dz', last_operator_dz, ...
        'kerr_n2_xy_in_step', kerr_n2_xy_in_step, ...
        'plasma_z_rk2_flag_effective', plasma_z_rk2_flag_effective, ...
        'nla_z_rk2_flag_effective', nla_z_rk2_flag_effective, ...
        'plasma_evolve_t_rk2_flag', plasma_evolve_t_rk2_flag, ...
        'resolved_physics_policy', resolved_physics_policy, ...
        'setup_physics_rewrite_report', setup_physics_rewrite_report);
end

function [time_grid_supports_parseval_fluence, fundamental_band_support, ...
          mask_visible_band_3d, mask_fundamental_band_3d, ...
          mask_red_band_3d, mask_green_band_3d, mask_blue_band_3d, ...
          run_warn_state] = build_band_store_plan_inputs_local( ...
            band_diagnostic_inputs, run_warn_state)
    [time_grid_supports_parseval_fluence, diagnostic_band_cfg, lambda_nm, ...
        lambda_fund, omega_window, mask_f_w, c, n, delta_t] = ...
        struct_utils.unpack_struct_fields(band_diagnostic_inputs, ...
        {'time_grid_supports_parseval_fluence', 'diagnostic_band_cfg', ...
         'lambda_nm', 'lambda_fund', 'omega_window', 'mask_f_w', ...
         'c', 'n', 'delta_t'}, ...
        'cerupp_section3d_setup.band_diagnostic_inputs');

    lambda_m_to_nm_scale = 1e9;
    lambda_fund_nm = lambda_fund * lambda_m_to_nm_scale;
    active_omega_support_mask = reshape(double(mask_f_w), 1, []) > 0;
    mask_visible_band = active_omega_support_mask & ...
        (lambda_nm >= diagnostic_band_cfg.lambda_visible_band_min) & ...
        (lambda_nm <= diagnostic_band_cfg.lambda_visible_band_max);
    mask_fundamental_band = active_omega_support_mask & ...
        (abs(lambda_nm - lambda_fund_nm) <= ...
        diagnostic_band_cfg.lambda_fundamental_band_half_width);
    mask_blue_band = active_omega_support_mask & ...
        (lambda_nm >= diagnostic_band_cfg.lambda_blue_band_min) & ...
        (lambda_nm <= diagnostic_band_cfg.lambda_blue_band_max);
    mask_green_band = active_omega_support_mask & ...
        (lambda_nm >= diagnostic_band_cfg.lambda_green_band_min) & ...
        (lambda_nm <= diagnostic_band_cfg.lambda_green_band_max);
    mask_red_band = active_omega_support_mask & ...
        (lambda_nm >= diagnostic_band_cfg.lambda_red_band_min) & ...
        (lambda_nm <= diagnostic_band_cfg.lambda_red_band_max);

    mask_visible_band_3d = reshape(mask_visible_band, 1, 1, []);
    mask_fundamental_band_3d = reshape(mask_fundamental_band, 1, 1, []);
    mask_red_band_3d = reshape(mask_red_band, 1, 1, []);
    mask_green_band_3d = reshape(mask_green_band, 1, 1, []);
    mask_blue_band_3d = reshape(mask_blue_band, 1, 1, []);

    fundamental_band_requested_lambda_min_nm = ...
        lambda_fund_nm - diagnostic_band_cfg.lambda_fundamental_band_half_width;
    fundamental_band_requested_lambda_max_nm = ...
        lambda_fund_nm + diagnostic_band_cfg.lambda_fundamental_band_half_width;
    if fundamental_band_requested_lambda_min_nm <= 0
        error('CerUPP:InvalidFundamentalBandLambdaRange', ...
            ['Fundamental-band diagnostic window must stay above 0 nm. ', ...
             'Requested interval was [%.3f, %.3f] nm.'], ...
            fundamental_band_requested_lambda_min_nm, ...
            fundamental_band_requested_lambda_max_nm);
    end

    fundamental_band_requested_omega_min = ...
        2*pi*c / (fundamental_band_requested_lambda_max_nm / lambda_m_to_nm_scale);
    fundamental_band_requested_omega_max = ...
        2*pi*c / (fundamental_band_requested_lambda_min_nm / lambda_m_to_nm_scale);
    fundamental_band_sampled_omega = sort(omega_window(mask_fundamental_band));
    fundamental_band_sampled_lambda_nm = lambda_nm(mask_fundamental_band);
    fundamental_band_sampled_num_bins = numel(fundamental_band_sampled_omega);
    fundamental_band_omega_cell_width = 2*pi / (n * delta_t);
    fundamental_band_omega_cell_coverage_fraction = 0;
    fundamental_band_sampled_omega_min = NaN;
    fundamental_band_sampled_omega_max = NaN;
    if fundamental_band_sampled_num_bins > 0
        fundamental_band_cell_omega_min = ...
            fundamental_band_sampled_omega - 0.5 * fundamental_band_omega_cell_width;
        fundamental_band_cell_omega_max = ...
            fundamental_band_sampled_omega + 0.5 * fundamental_band_omega_cell_width;
        fundamental_band_overlap_omega_min = max( ...
            fundamental_band_cell_omega_min, fundamental_band_requested_omega_min);
        fundamental_band_overlap_omega_max = min( ...
            fundamental_band_cell_omega_max, fundamental_band_requested_omega_max);
        fundamental_band_overlap_width = max( ...
            0, fundamental_band_overlap_omega_max - fundamental_band_overlap_omega_min);
        fundamental_band_requested_omega_width = ...
            fundamental_band_requested_omega_max - fundamental_band_requested_omega_min;
        if fundamental_band_requested_omega_width > 0
            fundamental_band_omega_cell_coverage_fraction = min( ...
                1, sum(fundamental_band_overlap_width) / fundamental_band_requested_omega_width);
        end
        fundamental_band_overlap_has_support = (fundamental_band_overlap_width > 0);
        if any(fundamental_band_overlap_has_support)
            fundamental_band_sampled_omega_min = min( ...
                fundamental_band_overlap_omega_min(fundamental_band_overlap_has_support));
            fundamental_band_sampled_omega_max = max( ...
                fundamental_band_overlap_omega_max(fundamental_band_overlap_has_support));
        end
    end

    fundamental_band_sampled_lambda_min_nm = NaN;
    fundamental_band_sampled_lambda_max_nm = NaN;
    if isfinite(fundamental_band_sampled_omega_min) && ...
            isfinite(fundamental_band_sampled_omega_max)
        fundamental_band_sampled_lambda_min_nm = ...
            2*pi*c / fundamental_band_sampled_omega_max * lambda_m_to_nm_scale;
        fundamental_band_sampled_lambda_max_nm = ...
            2*pi*c / fundamental_band_sampled_omega_min * lambda_m_to_nm_scale;
    elseif fundamental_band_sampled_num_bins > 0
        fundamental_band_sampled_lambda_min_nm = min(fundamental_band_sampled_lambda_nm);
        fundamental_band_sampled_lambda_max_nm = max(fundamental_band_sampled_lambda_nm);
    end

    fundamental_band_support_status = 'none';
    if (fundamental_band_sampled_num_bins > 0) && ...
            (fundamental_band_omega_cell_coverage_fraction > 0)
        if fundamental_band_omega_cell_coverage_fraction >= (1 - 1e-12)
            fundamental_band_support_status = 'full';
        else
            fundamental_band_support_status = 'partial';
        end
    end

    fundamental_band_support = struct( ...
        'requested_lambda_min_nm', fundamental_band_requested_lambda_min_nm, ...
        'requested_lambda_max_nm', fundamental_band_requested_lambda_max_nm, ...
        'requested_omega_min', fundamental_band_requested_omega_min, ...
        'requested_omega_max', fundamental_band_requested_omega_max, ...
        'sampled_lambda_min_nm', fundamental_band_sampled_lambda_min_nm, ...
        'sampled_lambda_max_nm', fundamental_band_sampled_lambda_max_nm, ...
        'sampled_omega_min', fundamental_band_sampled_omega_min, ...
        'sampled_omega_max', fundamental_band_sampled_omega_max, ...
        'sampled_num_bins', fundamental_band_sampled_num_bins, ...
        'omega_cell_coverage_fraction', fundamental_band_omega_cell_coverage_fraction, ...
        'status', fundamental_band_support_status, ...
        'has_any_support', ~strcmp(fundamental_band_support_status, 'none'), ...
        'has_full_support', strcmp(fundamental_band_support_status, 'full'));

    if ~fundamental_band_support.has_any_support
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'fundamental_band_mask_empty', ...
            'CerUPP:FundamentalBandMaskEmpty', ...
            ['Fundamental-band diagnostic mask has no sampled wavelength bins inside ', ...
             'lambda_fund +/- %.1f nm around %.1f nm. Fundamental-band fluence/time-trace ', ...
             'diagnostics will be marked unavailable and related fundamental-band plots skipped.'], ...
            diagnostic_band_cfg.lambda_fundamental_band_half_width, lambda_fund_nm);
    elseif strcmp(fundamental_band_support.status, 'partial')
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'fundamental_band_mask_partial_support', ...
            'CerUPP:FundamentalBandMaskPartialSupport', ...
            ['Fundamental-band diagnostic mask only partially covers the requested %.1f-%.1f nm band. ', ...
             'Current sampled support is %.1f-%.1f nm across %d bins (%.1f%% omega-cell coverage). ', ...
             'Stored masked-bin reductions remain available, and related fundamental-band plots stay enabled ', ...
             'with this partial sampled support noted in the warning/labels.'], ...
            fundamental_band_requested_lambda_min_nm, ...
            fundamental_band_requested_lambda_max_nm, ...
            fundamental_band_support.sampled_lambda_min_nm, ...
            fundamental_band_support.sampled_lambda_max_nm, ...
            fundamental_band_support.sampled_num_bins, ...
            100 * fundamental_band_support.omega_cell_coverage_fraction);
    end
end

function grid_state = build_grid_state_local(grid_inputs)
    grid_state = struct( ...
        'x', struct_utils.req_struct_field(grid_inputs, 'x', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'y', struct_utils.req_struct_field(grid_inputs, 'y', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        't', struct_utils.req_struct_field(grid_inputs, 't', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'kx', struct_utils.req_struct_field(grid_inputs, 'kx', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'ky', struct_utils.req_struct_field(grid_inputs, 'ky', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'kperp', struct_utils.req_struct_field(grid_inputs, 'kperp', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'lambda_window', struct_utils.req_struct_field(grid_inputs, 'lambda_window', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'omega_window', struct_utils.req_struct_field(grid_inputs, 'omega_window', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'lambda_fund', struct_utils.req_struct_field(grid_inputs, 'lambda_fund', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'omega_fund', struct_utils.req_struct_field(grid_inputs, 'omega_fund', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'num_x_pts', struct_utils.req_struct_field(grid_inputs, 'num_x_pts', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'num_y_pts', struct_utils.req_struct_field(grid_inputs, 'num_y_pts', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'n', struct_utils.req_struct_field(grid_inputs, 'n', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'delta_t', struct_utils.req_struct_field(grid_inputs, 'delta_t', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'delta_omega', struct_utils.req_struct_field(grid_inputs, 'delta_omega', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'delta_x', struct_utils.req_struct_field(grid_inputs, 'delta_x', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'delta_y', struct_utils.req_struct_field(grid_inputs, 'delta_y', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'delta_kx', struct_utils.req_struct_field(grid_inputs, 'delta_kx', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'delta_ky', struct_utils.req_struct_field(grid_inputs, 'delta_ky', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'core_idx', struct_utils.req_struct_field(grid_inputs, 'core_idx', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'x_cut', struct_utils.req_struct_field(grid_inputs, 'x', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'nu_sorted', struct_utils.req_struct_field(grid_inputs, 'nu_sorted', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'idx_nu', struct_utils.req_struct_field(grid_inputs, 'idx_nu', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'eps_safe', struct_utils.req_struct_field(grid_inputs, 'eps_safe', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'freq_offset', struct_utils.req_struct_field(grid_inputs, 'freq_offset', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        't_window', struct_utils.req_struct_field(grid_inputs, 't_window', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'z_domain', struct_utils.req_struct_field(grid_inputs, 'z_domain', ...
            'cerupp_section3d_setup.grid_inputs'));
end

function initial_plot_state = build_initial_plot_state_local( ...
        grid_inputs, initial_plot_inputs, plot_settings, run_warn_state)
    initial_plot_state = struct( ...
        'x', struct_utils.req_struct_field(grid_inputs, 'x', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'y', struct_utils.req_struct_field(grid_inputs, 'y', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        't', struct_utils.req_struct_field(grid_inputs, 't', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'A_xy', struct_utils.req_struct_field(initial_plot_inputs, 'A_xy', ...
            'cerupp_section3d_setup.initial_plot_inputs'), ...
        'center_i', struct_utils.req_struct_field(initial_plot_inputs, 'center_i', ...
            'cerupp_section3d_setup.initial_plot_inputs'), ...
        'n_omega_fund_xy', struct_utils.req_struct_field( ...
            initial_plot_inputs, 'n_omega_fund_xy', ...
            'cerupp_section3d_setup.initial_plot_inputs'), ...
        'n_ratio_diag_xy', struct_utils.req_struct_field( ...
            initial_plot_inputs, 'n_ratio_diag_xy', ...
            'cerupp_section3d_setup.initial_plot_inputs'), ...
        'freq_offset', struct_utils.req_struct_field(grid_inputs, 'freq_offset', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'initial_plot_settings', plot_settings.initial, ...
        'lambda_window', struct_utils.req_struct_field(grid_inputs, 'lambda_window', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'n_sell', struct_utils.req_struct_field(initial_plot_inputs, 'n_sell', ...
            'cerupp_section3d_setup.initial_plot_inputs'), ...
        'propagation_medium_name', struct_utils.req_struct_field( ...
            initial_plot_inputs, 'propagation_medium_name', ...
            'cerupp_section3d_setup.initial_plot_inputs'), ...
        'omega_window', struct_utils.req_struct_field(grid_inputs, 'omega_window', ...
            'cerupp_section3d_setup.grid_inputs'), ...
        'c', struct_utils.req_struct_field(initial_plot_inputs, 'c', ...
            'cerupp_section3d_setup.initial_plot_inputs'), ...
        'run_warn_state', run_warn_state);
end

function [grid_state, A_S, A_SSF, A_F, run_warn_state] = ...
        build_launch_state_local(grid_state, launch_state_inputs, run_warn_state)
    x = struct_utils.req_struct_field( ...
        grid_state, 'x', 'cerupp_section3d_setup.grid_state');
    y = struct_utils.req_struct_field( ...
        grid_state, 'y', 'cerupp_section3d_setup.grid_state');
    t = struct_utils.req_struct_field( ...
        grid_state, 't', 'cerupp_section3d_setup.grid_state');
    kperp = struct_utils.req_struct_field( ...
        grid_state, 'kperp', 'cerupp_section3d_setup.grid_state');
    lambda_window = struct_utils.req_struct_field( ...
        grid_state, 'lambda_window', 'cerupp_section3d_setup.grid_state');
    omega_window = struct_utils.req_struct_field( ...
        grid_state, 'omega_window', 'cerupp_section3d_setup.grid_state');

    [A_xy, fwhm_fund, mask, mask_f, mask_f_w, mask_f_runtime, ...
        mask_f_w_runtime, mask_f_xy, c, n_sell, kcut, k_min_med, ...
        mask_loss_warn_frac] = ...
        struct_utils.unpack_struct_fields(launch_state_inputs, ...
        {'A_xy', 'fwhm_fund', 'mask', 'mask_f', 'mask_f_w', ...
         'mask_f_runtime', 'mask_f_w_runtime', 'mask_f_xy', 'c', ...
         'n_sell', 'kcut', 'k_min_med', ...
         'mask_loss_warn_frac'}, ...
        'cerupp_section3d_setup.launch_state_inputs');

    fprintf(['Beamwidth reference (input setting only; no precomputed z=0 plot point) ', ...
             'FWHM_fund=%.3f um\n'], ...
        fwhm_fund * 1e6);

    A_S = A_xy;
    A_SSF = fft(A_S, [], 3);
    A_F = fft2(A_SSF);

    mask_loss_diagnostic = propagation_support.estimate_linear_mask_energy_loss_once( ...
        A_F, mask_f, mask_f_w);
    if isfinite(mask_loss_diagnostic.applied_step_loss_frac)
        fprintf(['Setup smooth-mask geometry check (one-time): the built smooth spectral mask would remove ~= ', ...
                 '%.3f%% of the launch-spectrum energy.\n'], ...
            100 * mask_loss_diagnostic.applied_step_loss_frac);
        if mask_loss_diagnostic.applied_step_loss_frac > mask_loss_warn_frac
            run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
                run_warn_state, 'setup', ...
                'setup_mask_loss_soft_warn', ...
                'CerUPP:Setup:MaskLossSoftWarn', ...
                ['One-time setup geometry estimate: the built smooth spectral mask would remove %.2f%% of ', ...
                 'the launch-spectrum energy, exceeding the configured mask_loss_warn_frac threshold ', ...
                 '(%.2f%%).'], ...
                100 * mask_loss_diagnostic.applied_step_loss_frac, ...
                100 * mask_loss_warn_frac);
        end
    else
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', ...
            'setup_mask_loss_diag_skipped', ...
            'CerUPP:MaskLossSetupDiagnosticSkipped', ...
            'Mask-loss setup diagnostic skipped (non-finite or zero baseline spectral energy).');
    end

    dt_vec_runtime = diff(t(:));
    if isa(A_S, 'single')
        dt_vec = single(dt_vec_runtime);
    else
        dt_vec = double(dt_vec_runtime);
    end

    [~, ix_axis0] = min(abs(x));
    [~, iy_axis0] = min(abs(y));
    x_axis0 = x(ix_axis0);
    y_axis0 = y(iy_axis0);
    k_band_med = double(n_sell(:)) .* double(omega_window(:)) / double(c);
    % Reuse the exact step-1 launch-entry helper so the printed launch
    % summary cannot drift from the propagated launch field.
    A_F_launch_report = propagation_support.apply_runtime_launch_mask_local( ...
        A_F, mask_f_runtime, mask_f_w_runtime, mask);

    run_warn_state = mask_and_offaxis_setup_and_check_validity.mask_setup_launch_weighted_angle_report( ...
        A_F_launch_report, mask_f_runtime, mask_f_w_runtime, ...
        kperp, k_band_med, kcut, k_min_med, ...
        run_warn_state);

    grid_state.dt_vec = dt_vec;
    grid_state.ix_axis0 = ix_axis0;
    grid_state.iy_axis0 = iy_axis0;
    grid_state.x_axis0 = x_axis0;
    grid_state.y_axis0 = y_axis0;
end

function setup_only_plot_controls = build_setup_only_plot_controls_local(section3_capture_inputs)
    [plot_warn_flag, show_plots_flag, show_3d_diagnostic_plots_flag, ...
        make_initial_plots_flag, save_outputs_as_fig_flag, ...
        save_outputs_as_png_flag] = ...
        struct_utils.unpack_struct_fields(section3_capture_inputs, ...
        {'plot_warn_flag', 'show_plots_flag', ...
         'show_3d_diagnostic_plots_flag', 'make_initial_plots_flag', ...
         'save_outputs_as_fig_flag', 'save_outputs_as_png_flag'}, ...
        'cerupp_section3d_setup.section3_capture_inputs');

    setup_only_plot_controls = struct( ...
        'plot_warn_flag', plot_warn_flag, ...
        'show_plots_flag', show_plots_flag, ...
        'show_3d_diagnostic_plots_flag', show_3d_diagnostic_plots_flag, ...
        'make_initial_plots_flag', make_initial_plots_flag, ...
        'save_outputs_as_fig_flag', save_outputs_as_fig_flag, ...
        'save_outputs_as_png_flag', save_outputs_as_png_flag);
end
