function varargout = cerupp_section5a_freeze_guard(varargin)
% Driver-only Section 5A helper for cerupp.m.
% In the usual no-input mode this helper reads the current cerupp.m
% workspace, rebuilds the current compare surfaces for every captured
% freeze stage and later built launch/operator/runtime record, and runs
% the full pre-loop freeze guard before propagation starts.

    if nargin == 0
        caller_field_names = caller_field_names_local();
        cfg = struct();
        for ii = 1:numel(caller_field_names)
            field_name = caller_field_names{ii};
            try
                cfg.(field_name) = evalin('caller', field_name);
            catch err
                if strcmp(err.identifier, 'MATLAB:UndefinedFunction') || ...
                        strcmp(err.identifier, 'MATLAB:UndefinedVariable')
                    error('CerUPP:MissingSection5ACallerField', ...
                        ['cerupp_section5a_freeze_guard expected caller variable ''%s'' ', ...
                         'to exist before the Section 5A helper call.'], ...
                        field_name);
                end
                rethrow(err);
            end
        end
        freeze_guard_state = build_freeze_guard_state_local(cfg);
        freeze_guard_state = apply_freeze_guard_local(freeze_guard_state);
        if nargout > 0
            varargout{1} = freeze_guard_state;
        end
        return;
    end

    if (nargin ~= 1) || ~isstruct(varargin{1}) || ~isscalar(varargin{1})
        error('CerUPP:InvalidSection5AFreezeGuardCfg', ...
            'cerupp_section5a_freeze_guard accepts either no inputs or one scalar cfg struct.');
    end

    freeze_guard_state = build_freeze_guard_state_local(varargin{1});
    freeze_guard_state = apply_freeze_guard_local(freeze_guard_state);
    if nargout > 1
        error('CerUPP:InvalidSection5AFreezeGuardOutputCount', ...
            'cerupp_section5a_freeze_guard returns at most one output struct.');
    end
    if nargout == 1
        varargout{1} = freeze_guard_state;
    end
end

function caller_field_names = caller_field_names_local()
    caller_field_names = { ...
        'setup_freeze_guard', ...
        'run_warn_state', ...
        'frozen_cfg_raw_startup_setup', ...
        'frozen_cfg_raw_section2_setup', ...
        'frozen_cfg_raw_section3_setup', ...
        'runtime_setup', ...
        'perf_cfg', ...
        'output_cfg', ...
        'cadence_cfg', ...
        'plot_settings', ...
        'fluence_use_parseval_requested', ...
        'fluence_use_parseval', ...
        'fluence_method_name_requested', ...
        'fluence_method_name', ...
        'phase_diagnostic_flag', ...
        'strict_stage_finite_scan_flag', ...
        'output_plan', ...
        'output_root', ...
        'run_tag', ...
        'curr_cerupp_version', ...
        'append_timestamp_to_run_id', ...
        'archive_existing_run_output_root', ...
        'auto_timestamp_on_run_output_collision', ...
        'quick_debug_mode_flag', ...
        'enable_console_output_log_flag', ...
        'selected_builtin_medium_family', ...
        'n2_air_placeholder_threshold', ...
        'lambda_fund', ...
        'core_radius', ...
        'n2_kerr', ...
        'n2_kerr_disable_tol', ...
        'keldysh_lut_i_roi_min_requested_raw', ...
        'keldysh_electron_effective_mass_over_me', ...
        'keldysh_hole_effective_mass_over_me', ...
        'ui', ...
        'keldysh_gap', ...
        'keldysh_matched_depletion', ...
        'rho_nt', ...
        'k_power_vec', ...
        'sigma_k_vec', ...
        'tau_c', ...
        'alpha_recombine', ...
        'plasma_flag', ...
        'nl_absorption_flag', ...
        'keldysh_enabled', ...
        'keldysh_use_interference_corrected_rate_flag', ...
        'plasma_m_over_me', ...
        'air_placeholder_ui', ...
        'air_placeholder_rho_nt', ...
        'air_placeholder_k_power', ...
        'air_placeholder_sigma_k', ...
        'distance_to_propagate', ...
        'stepsize', ...
        't_window', ...
        'n', ...
        'lambda_ref', ...
        'mask_pad_w', ...
        'mask_pad_x', ...
        'mask_pad_y', ...
        'spatial_inner_frac', ...
        'kperp_alpha', ...
        'kperp_ramp_frac', ...
        'kperp_nyquist_frac', ...
        'mask_loss_warn_frac', ...
        'comp_window_x_width', ...
        'num_x_pts', ...
        'comp_window_y_width', ...
        'num_y_pts', ...
        'n_recompute_tol', ...
        'n2_recompute_tol', ...
        'keldysh_display_k_requested_raw', ...
        'plasma_ofi_use_remaining_neutral_factor_flag', ...
        'nla_use_remaining_neutral_factor_flag', ...
        'nla_ofi_energy_accounting_mode', ...
        'nla_check_ofi_event_energy_flag', ...
        'nla_use_ofi_event_depletion_flag', ...
        'keldysh_lookup_csv_name_requested_raw', ...
        'allow_keldysh_cache_reuse_without_match', ...
        'nla_use_ofi_rate_law_flag', ...
        'use_nlse_flag', ...
        'z_dependent_medium_flag', ...
        'allow_z_dependent_keldysh', ...
        'ion_routine_flag', ...
        'fee_z_rk2_flag', ...
        'plasma_z_rk2_flag', ...
        'nla_z_rk2_flag', ...
        'plasma_evolve_t_rk2_flag', ...
        'use_exact_avalanche_exp_update_flag', ...
        'keldysh_lut_n_global', ...
        'keldysh_lut_n_roi', ...
        'keldysh_lut_i_global_min', ...
        'keldysh_zero_rate_below', ...
        'keldysh_lut_i_global_max', ...
        'keldysh_lut_i_roi_max', ...
        'raw_rho_plasma_cap', ...
        'raw_rho_neutral_supply', ...
        'simple_masks_flag', ...
        'nonparaxial_diffraction_order', ...
        'i_fil_cutoff', ...
        'i_fil_cutoff_vis', ...
        'rho_fil_cutoff', ...
        'diagnostics_flag', ...
        'checkpoint_diag_reassembly_flag', ...
        'enable_drho_xz_diagnostics', ...
        'reuse_linear_guiding_operator_cache_flag', ...
        'diagnostic_store_stride_steps', ...
        'checkpoint_stride_steps', ...
        'a_s_rho_snapshot_checkpoint_stride_steps', ...
        'memmon_projection_stride_steps', ...
        'track_energy_flag', ...
        'show_plasma_stiffness_diagnostic_flag', ...
        'plasma_stiffness_diagnostic_stride', ...
        'progress_print_stride', ...
        'enable_advance_step_substep_timing_flag', ...
        'advance_step_substep_timing_sample_count', ...
        'enable_memory_monitor_flag', ...
        'memmon_abort_gb', ...
        'memmon_abort_on_exceed', ...
        'memmon_first_n_steps', ...
        'memmon_stride', ...
        'enable_wallclock_timeout_abort_flag', ...
        'wallclock_expected_timeout_hours', ...
        'wallclock_projection_min_steps', ...
        'plot_warn_flag', ...
        'show_plots_flag', ...
        'show_3d_diagnostic_plots_flag', ...
        'make_initial_plots_flag', ...
        'save_outputs_as_fig_flag', ...
        'save_outputs_as_png_flag', ...
        'run_postprocessing_flag', ...
        'store_reduced_spectral_z_diagnostics_flag', ...
        'z_3d_slice', ...
        'store_phase_map_flag', ...
        'store_spectral_fluence_flag', ...
        'store_full_spectrum_flag', ...
        'intermediate_saves_flag', ...
        'checkpoint_full_save_flag', ...
        'checkpoint_unique_files_flag', ...
        'save_final_full_output_flag', ...
        'fullsave_collect_core_history_flag', ...
        'save_final_restart_checkpoint_flag', ...
        'save_end_snapshot_flag', ...
        'write_current_run_pointer_flag', ...
        'write_latest_successful_run_id_flag', ...
        'write_run_status_flag', ...
        'show_additional_dev_plots', ...
        'fwhm_fund', ...
        'td_pulse', ...
        't_center', ...
        'beta_chirp', ...
        'p_input', ...
        'dkx_offset_angle', ...
        'dky_offset_angle', ...
        'oam_charge1', ...
        'x_offset', ...
        'y_offset', ...
        'p_input_beam2', ...
        'dkx_offset_angle_beam2', ...
        'dky_offset_angle_beam2', ...
        'oam_charge_beam2', ...
        'x_offset_beam2', ...
        'y_offset_beam2', ...
        'rng_seed', ...
        'noise_amplitude', ...
        'lambda_visible_band_min', ...
        'lambda_visible_band_max', ...
        'chromatic_onset_bin_width', ...
        'lambda_blue_band_min', ...
        'lambda_blue_band_max', ...
        'lambda_green_band_min', ...
        'lambda_green_band_max', ...
        'lambda_red_band_min', ...
        'lambda_red_band_max', ...
        'fundamental_band_half_width', ...
        'w0', ...
        'p_input_w', ...
        'p_input_w_beam2', ...
        'i_laser_peak', ...
        'i_laser_peak_beam2', ...
        't0_gauss', ...
        'dkx_offset', ...
        'dky_offset', ...
        'dkx_offset_beam2', ...
        'dky_offset_beam2', ...
        'plasma_runtime_cfg', ...
        'nla_runtime_cfg', ...
        'step_runtime_ctx', ...
        'kerr_n2_xy_in_step', ...
        'resolved_setup_contract', ...
        'resolved_physics_policy', ...
        'A_S', ...
        'A_SSF', ...
        'A_F', ...
        'core_idx', ...
        'lin_index_3d', ...
        'nl_index_3d', ...
        'mask', ...
        'mask_2_d', ...
        'sigma_vec', ...
        'diffraction_dispersion_matrix', ...
        'guiding_matrix', ...
        'qomega_3d', ...
        'mask_f', ...
        'mask_f_w'};
    caller_field_names = unique([ ...
        caller_field_names, ...
        driver_setup_support.runtime_output_visible_field_names_local()], ...
        'stable');

end

function freeze_guard_state = build_freeze_guard_state_local(cfg)
    runtime_setup = struct_utils.req_struct_field( ...
        cfg, 'runtime_setup', 'cerupp_section5a_freeze_guard.runtime_setup');
    cfg.outdir = struct_utils.req_struct_field( ...
        runtime_setup, 'outdir', 'cerupp_section5a_freeze_guard.runtime_setup');

    raw_startup_setup = driver_setup_support.build_raw_startup_setup_local( ...
        project_cfg_fields_local(cfg, { ...
            'output_root', ...
            'run_tag', ...
            'curr_cerupp_version', ...
            'append_timestamp_to_run_id', ...
            'archive_existing_run_output_root', ...
            'auto_timestamp_on_run_output_collision', ...
            'quick_debug_mode_flag', ...
            'enable_console_output_log_flag'}, ...
            'cerupp_section5a_freeze_guard.raw_startup_setup'));
    raw_medium_setup = driver_setup_support.build_raw_medium_setup_local( ...
        driver_setup_support.build_raw_medium_inputs_local(struct( ...
            'selected_builtin_medium_family', cfg.selected_builtin_medium_family, ...
            'n2_air_placeholder_threshold', cfg.n2_air_placeholder_threshold, ...
            'lambda_fund', cfg.lambda_fund, ...
            'core_radius', cfg.core_radius, ...
            'n2_kerr', cfg.n2_kerr, ...
            'n2_kerr_disable_tol', cfg.n2_kerr_disable_tol, ...
            'keldysh_lut_i_roi_min', cfg.keldysh_lut_i_roi_min_requested_raw, ...
            'keldysh_electron_effective_mass_over_me', ...
                cfg.keldysh_electron_effective_mass_over_me, ...
            'keldysh_hole_effective_mass_over_me', ...
                cfg.keldysh_hole_effective_mass_over_me, ...
            'ui', cfg.ui, ...
            'keldysh_gap', cfg.keldysh_gap, ...
            'keldysh_matched_depletion', cfg.keldysh_matched_depletion, ...
            'rho_nt', cfg.rho_nt, ...
            'k_power_vec', cfg.k_power_vec, ...
            'sigma_k_vec', cfg.sigma_k_vec, ...
            'tau_c', cfg.tau_c, ...
            'alpha_recombine', cfg.alpha_recombine, ...
            'plasma_flag', cfg.plasma_flag, ...
            'nl_absorption_flag', cfg.nl_absorption_flag, ...
            'nla_use_ofi_rate_law_flag', cfg.nla_use_ofi_rate_law_flag, ...
            'keldysh_enabled', cfg.keldysh_enabled, ...
            'plasma_m_over_me', cfg.plasma_m_over_me, ...
            'air_placeholder_ui', cfg.air_placeholder_ui, ...
            'air_placeholder_rho_nt', cfg.air_placeholder_rho_nt, ...
            'air_placeholder_k_power', cfg.air_placeholder_k_power, ...
            'air_placeholder_sigma_k', cfg.air_placeholder_sigma_k)));
    computational_setup_surface = ...
        driver_setup_support.build_computational_setup_surface_local( ...
            project_cfg_fields_local(cfg, { ...
                'distance_to_propagate', ...
                'stepsize', ...
                't_window', ...
                'n', ...
                'lambda_ref', ...
                'mask_pad_w', ...
                'mask_pad_x', ...
                'mask_pad_y', ...
                'spatial_inner_frac', ...
                'kperp_alpha', ...
                'kperp_ramp_frac', ...
                'kperp_nyquist_frac', ...
                'mask_loss_warn_frac', ...
                'comp_window_x_width', ...
                'num_x_pts', ...
                'comp_window_y_width', ...
                'num_y_pts', ...
                'n_recompute_tol', ...
                'n2_recompute_tol'}, ...
                'cerupp_section5a_freeze_guard.computational_setup_surface'));
    raw_section2_setup = driver_setup_support.build_raw_section2_setup_local(struct( ...
        'raw_section2_inputs', struct( ...
            'plasma_flag', cfg.plasma_flag, ...
            'nl_absorption_flag', cfg.nl_absorption_flag, ...
            'keldysh_enabled', cfg.keldysh_enabled, ...
            'keldysh_use_interference_corrected_rate_flag', ...
                cfg.keldysh_use_interference_corrected_rate_flag, ...
            'keldysh_display_k', cfg.keldysh_display_k_requested_raw, ...
            'plasma_ofi_use_remaining_neutral_factor_flag', ...
                cfg.plasma_ofi_use_remaining_neutral_factor_flag, ...
            'nla_use_remaining_neutral_factor_flag', ...
                cfg.nla_use_remaining_neutral_factor_flag, ...
            'nla_ofi_energy_accounting_mode', ...
                cfg.nla_ofi_energy_accounting_mode, ...
            'nla_check_ofi_event_energy_flag', ...
                cfg.nla_check_ofi_event_energy_flag, ...
            'nla_use_ofi_event_depletion_flag', ...
                cfg.nla_use_ofi_event_depletion_flag, ...
            'keldysh_lookup_csv_name', ...
                cfg.keldysh_lookup_csv_name_requested_raw, ...
            'allow_keldysh_cache_reuse_without_match', ...
                cfg.allow_keldysh_cache_reuse_without_match, ...
            'nla_use_ofi_rate_law_flag', cfg.nla_use_ofi_rate_law_flag, ...
            'use_nlse_flag', cfg.use_nlse_flag, ...
            'z_dependent_medium_flag', cfg.z_dependent_medium_flag, ...
            'allow_z_dependent_keldysh', cfg.allow_z_dependent_keldysh, ...
            'ion_routine_flag', cfg.ion_routine_flag, ...
            'fee_z_rk2_flag', cfg.fee_z_rk2_flag, ...
            'plasma_z_rk2_flag', cfg.plasma_z_rk2_flag, ...
            'nla_z_rk2_flag', cfg.nla_z_rk2_flag, ...
            'plasma_evolve_t_rk2_flag', cfg.plasma_evolve_t_rk2_flag, ...
            'use_exact_avalanche_exp_update_flag', ...
                cfg.use_exact_avalanche_exp_update_flag, ...
            'keldysh_lut_n_global', cfg.keldysh_lut_n_global, ...
            'keldysh_lut_n_roi', cfg.keldysh_lut_n_roi, ...
            'keldysh_lut_i_global_min', cfg.keldysh_lut_i_global_min, ...
            'keldysh_zero_rate_below', cfg.keldysh_zero_rate_below, ...
            'keldysh_lut_i_global_max', cfg.keldysh_lut_i_global_max, ...
            'keldysh_lut_i_roi_max', cfg.keldysh_lut_i_roi_max, ...
            'rho_plasma_cap', cfg.raw_rho_plasma_cap, ...
            'rho_neutral_supply', cfg.raw_rho_neutral_supply, ...
            'simple_masks_flag', cfg.simple_masks_flag, ...
            'nonparaxial_diffraction_order', ...
                cfg.nonparaxial_diffraction_order, ...
            'i_fil_cutoff', cfg.i_fil_cutoff, ...
            'i_fil_cutoff_vis', cfg.i_fil_cutoff_vis, ...
            'rho_fil_cutoff', cfg.rho_fil_cutoff, ...
            'diagnostics_flag', cfg.diagnostics_flag, ...
            'checkpoint_diag_reassembly_flag', ...
                cfg.checkpoint_diag_reassembly_flag, ...
            'enable_drho_xz_diagnostics', cfg.enable_drho_xz_diagnostics, ...
            'reuse_linear_guiding_operator_cache_flag', ...
                cfg.reuse_linear_guiding_operator_cache_flag, ...
            'diagnostic_store_stride_steps', ...
                cfg.diagnostic_store_stride_steps, ...
            'checkpoint_stride_steps', cfg.checkpoint_stride_steps, ...
            'a_s_rho_snapshot_checkpoint_stride_steps', ...
                cfg.a_s_rho_snapshot_checkpoint_stride_steps, ...
            'memmon_projection_stride_steps', ...
                cfg.memmon_projection_stride_steps), ...
        'raw_medium_setup', raw_medium_setup, ...
        'computational_setup_surface', computational_setup_surface));
    setup_only_plot_controls = project_cfg_fields_local(cfg, { ...
        'plot_warn_flag', ...
        'show_plots_flag', ...
        'show_3d_diagnostic_plots_flag', ...
        'make_initial_plots_flag', ...
        'save_outputs_as_fig_flag', ...
        'save_outputs_as_png_flag'}, ...
        'cerupp_section5a_freeze_guard.setup_only_plot_controls');
    launch_cfg = project_cfg_fields_local(cfg, { ...
        'fwhm_fund', ...
        'td_pulse', ...
        't_center', ...
        'beta_chirp', ...
        'p_input', ...
        'dkx_offset_angle', ...
        'dky_offset_angle', ...
        'oam_charge1', ...
        'x_offset', ...
        'y_offset', ...
        'p_input_beam2', ...
        'dkx_offset_angle_beam2', ...
        'dky_offset_angle_beam2', ...
        'oam_charge_beam2', ...
        'x_offset_beam2', ...
        'y_offset_beam2', ...
        'rng_seed', ...
        'noise_amplitude'}, ...
        'cerupp_section5a_freeze_guard.launch');
    diagnostic_band_cfg = driver_setup_support.validate_diagnostic_band_cfg( ...
        driver_setup_support.build_raw_diagnostic_band_cfg_local(struct( ...
            'lambda_visible_band_min', cfg.lambda_visible_band_min, ...
            'lambda_visible_band_max', cfg.lambda_visible_band_max, ...
            'chromatic_onset_bin_width', cfg.chromatic_onset_bin_width, ...
            'lambda_blue_band_min', cfg.lambda_blue_band_min, ...
            'lambda_blue_band_max', cfg.lambda_blue_band_max, ...
            'lambda_green_band_min', cfg.lambda_green_band_min, ...
            'lambda_green_band_max', cfg.lambda_green_band_max, ...
            'lambda_red_band_min', cfg.lambda_red_band_min, ...
            'lambda_red_band_max', cfg.lambda_red_band_max, ...
            'lambda_fundamental_band_half_width', ...
                cfg.fundamental_band_half_width)), ...
        'cerupp_section5a_freeze_guard live diagnostic_band_cfg');
    raw_section3_setup = driver_setup_support.build_raw_section3_setup_local(struct( ...
        'setup_plot_controls', setup_only_plot_controls, ...
        'launch', launch_cfg, ...
        'diagnostic_band_cfg', diagnostic_band_cfg));
    derived_launch_setup = project_cfg_fields_local(cfg, { ...
        'w0', ...
        'p_input_w', ...
        'p_input_w_beam2', ...
        'i_laser_peak', ...
        'i_laser_peak_beam2', ...
        't0_gauss', ...
        'dkx_offset', ...
        'dky_offset', ...
        'dkx_offset_beam2', ...
        'dky_offset_beam2'}, ...
        'cerupp_section5a_freeze_guard.derived_launch_setup');
    effective_runtime_output_setup = ...
        driver_setup_support.build_effective_runtime_output_setup_local( ...
            cfg.perf_cfg, cfg.output_cfg, cfg.cadence_cfg, cfg.plot_settings, ...
            cfg.fluence_use_parseval_requested, cfg.fluence_use_parseval, ...
            cfg.fluence_method_name_requested, cfg.fluence_method_name, ...
            cfg.phase_diagnostic_flag, cfg.strict_stage_finite_scan_flag, ...
            cfg.output_plan);
    effective_runtime_physics_setup = ...
        driver_setup_support.build_effective_runtime_physics_setup_freeze_surface_local(struct( ...
        'plasma_runtime_cfg', cfg.plasma_runtime_cfg, ...
        'nla_runtime_cfg', cfg.nla_runtime_cfg, ...
        'step_runtime_ctx', cfg.step_runtime_ctx, ...
        'kerr_n2_xy_in_step', cfg.kerr_n2_xy_in_step, ...
        'resolved_setup_contract', cfg.resolved_setup_contract, ...
        'resolved_physics_policy', cfg.resolved_physics_policy));
    built_launch_state = ...
        driver_setup_support.build_built_launch_state_freeze_surface_local(struct( ...
            'A_S', cfg.A_S, ...
            'A_SSF', cfg.A_SSF, ...
            'A_F', cfg.A_F));
    built_propagation_state = ...
        driver_setup_support.build_built_propagation_state_freeze_surface_local(struct( ...
            'core_idx', cfg.core_idx, ...
            'lin_index_3d', cfg.lin_index_3d, ...
            'nl_index_3d', cfg.nl_index_3d, ...
            'mask', cfg.mask, ...
            'mask_2_d', cfg.mask_2_d, ...
            'sigma_vec', cfg.sigma_vec, ...
            'diffraction_dispersion_matrix', cfg.diffraction_dispersion_matrix, ...
            'guiding_matrix', cfg.guiding_matrix, ...
            'qomega_3d', cfg.qomega_3d, ...
            'mask_f', cfg.mask_f, ...
            'mask_f_w', cfg.mask_f_w));
    visible_runtime_knobs = ...
        driver_setup_support.build_visible_runtime_knobs_local(cfg);
    [~, ~, raw_runtime_output_setup] = ...
        driver_setup_support.build_current_late_runtime_output_surfaces_local(struct( ...
            'visible_runtime_knobs', visible_runtime_knobs, ...
            'frozen_cfg_raw_startup_setup', cfg.frozen_cfg_raw_startup_setup, ...
            'frozen_cfg_raw_section2_setup', cfg.frozen_cfg_raw_section2_setup, ...
            'frozen_cfg_raw_section3_setup', cfg.frozen_cfg_raw_section3_setup));

    freeze_guard_state = struct( ...
        'setup_freeze_guard', cfg.setup_freeze_guard, ...
        'run_warn_state', cfg.run_warn_state, ...
        'sealed_setup_freeze_surfaces', ...
            user_setup_guard.build_sealed_surface_snapshot(cfg.setup_freeze_guard), ...
        'current_surfaces', struct( ...
            'raw_startup_setup', raw_startup_setup, ...
            'raw_section2_setup', raw_section2_setup, ...
            'setup_only_plot_controls', setup_only_plot_controls, ...
            'raw_section3_setup', raw_section3_setup, ...
            'derived_launch_setup', derived_launch_setup, ...
            'built_launch_state', built_launch_state, ...
            'built_propagation_state', built_propagation_state, ...
            'raw_runtime_output_setup', raw_runtime_output_setup, ...
            'effective_runtime_output_setup', ...
                effective_runtime_output_setup, ...
            'effective_runtime_physics_setup', ...
                effective_runtime_physics_setup));
end

function freeze_guard_state = apply_freeze_guard_local(freeze_guard_state)
    setup_freeze_guard = req_field_local(freeze_guard_state, 'setup_freeze_guard');
    sealed_setup_freeze_surfaces = req_field_local( ...
        freeze_guard_state, 'sealed_setup_freeze_surfaces');
    current_surfaces = req_field_local(freeze_guard_state, 'current_surfaces');
    run_warn_state = req_field_local(freeze_guard_state, 'run_warn_state');

    if logical(setup_freeze_guard.enabled)
        user_setup_guard.assert_guard_integrity( ...
            setup_freeze_guard, sealed_setup_freeze_surfaces);
        user_setup_guard.assert_clean( ...
            setup_freeze_guard, current_surfaces);
        freeze_guard_state.run_warn_state = run_warn_state;
        return;
    end

    strict_guard = setup_freeze_guard;
    strict_guard.enabled = true;
    try
        user_setup_guard.assert_guard_integrity( ...
            strict_guard, sealed_setup_freeze_surfaces);
    catch me_guard
        [run_warn_state, handled] = emit_demoted_freeze_guard_warning_local( ...
            run_warn_state, me_guard, 'setup_freeze_guard_integrity_demoted', ...
            'CerUPP:SetupFreezeGuardIntegrityDemotedSoftWarn');
        if ~handled
            rethrow(me_guard);
        end
    end
    try
        user_setup_guard.assert_clean( ...
            strict_guard, current_surfaces);
    catch me_guard
        [run_warn_state, handled] = emit_demoted_freeze_guard_warning_local( ...
            run_warn_state, me_guard, 'setup_freeze_guard_late_edit_demoted', ...
            'CerUPP:SetupFreezeGuardLateEditDemotedSoftWarn');
        if ~handled
            rethrow(me_guard);
        end
    end
    freeze_guard_state.run_warn_state = run_warn_state;
end

function projected_cfg = project_cfg_fields_local(cfg, field_names, context_name)
    projected_cfg = struct();
    for ii = 1:numel(field_names)
        field_name = field_names{ii};
        projected_cfg.(field_name) = struct_utils.req_struct_field( ...
            cfg, field_name, context_name);
    end
end

function value = req_field_local(cfg, field_name)
    value = struct_utils.req_struct_field( ...
        cfg, field_name, 'cerupp_section5a_freeze_guard');
end

function [run_warn_state, handled] = emit_demoted_freeze_guard_warning_local( ...
        run_warn_state, me_guard, warn_key, warn_id)
    handled = false;
    if strcmp(me_guard.identifier, 'CerUPP:LateVisibleSetupEditAfterFreeze')
        handled = true;
        run_warn_state = run_warn_state_utils.emit_warn_once_with_phase( ...
            run_warn_state, 'setup', warn_key, warn_id, ...
            ['enable_setup_freeze_guard_flag=false demoted this freeze-guard hard error to ', ...
             'a soft warning: %s'], ...
            me_guard.message);
    end
end
