function varargout = cerupp_section6c_finalize_reporting(varargin)
% Driver-only Section 6C helper for cerupp.m.
% In the usual no-input mode this helper reads the current cerupp.m
% workspace, collapses the end-of-run output/status records, writes the
% latest-run pointers, and finalizes the run-status record.

    if nargin == 0
        caller_field_names = caller_field_names_local();
        cfg = struct();
        for ii = 1:numel(caller_field_names)
            field_name = caller_field_names{ii};
            try
                cfg.(field_name) = evalin('caller', field_name);
            catch err
                if strcmp(err.identifier, 'MATLAB:UndefinedFunction') || ...
                        strcmp(err.identifier, 'MATLAB:UndefinedVariable')
                    error('CerUPP:MissingSection6CCallerField', ...
                        ['cerupp_section6c_finalize_reporting expected caller variable ''%s'' ', ...
                         'to exist before the Section 6C helper call.'], ...
                        field_name);
                end
                rethrow(err);
            end
        end
        section6c_state = build_section6c_state_local(cfg);
        output_field_names = fieldnames(section6c_state);
        for ii = 1:numel(output_field_names)
            field_name = output_field_names{ii};
            assignin('caller', field_name, section6c_state.(field_name));
        end
        if nargout > 0
            varargout{1} = section6c_state;
        end
        return;
    end

    if (nargin ~= 1) || ~isstruct(varargin{1}) || ~isscalar(varargin{1})
        error('CerUPP:InvalidSection6CCfg', ...
            'cerupp_section6c_finalize_reporting accepts either no inputs or one scalar cfg struct.');
    end

    section6c_state = build_section6c_state_local(varargin{1});
    if nargout > 1
        error('CerUPP:InvalidSection6COutputCount', ...
            'cerupp_section6c_finalize_reporting returns at most one output struct.');
    end
    if nargout == 1
        varargout{1} = section6c_state;
    end
end

function caller_field_names = caller_field_names_local()
    caller_field_names = { ...
        'output_plan', ...
        'checkpoint_policy_state', ...
        'final_restart_attempted_postprop', ...
        'final_restart_write_state', ...
        'final_restart_fallback_error_id', ...
        'final_restart_fallback_error_message', ...
        'final_restart_save_ok', ...
        'end_snapshot_write_state', ...
        'end_snapshot_attempted_postprop', ...
        'end_snapshot_save_ok', ...
        'final_fullsave_build_cfg', ...
        'final_full_save_ok', ...
        'final_full_save_error_id', ...
        'final_full_save_error_message', ...
        'run_end_state', ...
        'run_warn_state', ...
        'warning_ledgers', ...
        'runtime_setup', ...
        'completed_z_steps', ...
        'num_zsteps', ...
        'terminal_output_publication_allowed', ...
        'final_a_s_state_finite', ...
        'final_a_f_state_finite', ...
        'final_rho_state_finite', ...
        'final_rho_state_shape_ok', ...
        'terminal_propagated_state', ...
        'run_status_ctx', ...
        'finalize_run_status_local'};
end

function section6c_state = build_section6c_state_local(cfg)
    run_end_state = struct_utils.req_struct_field( ...
        cfg, 'run_end_state', 'cerupp_section6c_finalize_reporting.run_end_state');
    checkpoint_policy_state = struct_utils.req_struct_field( ...
        cfg, 'checkpoint_policy_state', ...
        'cerupp_section6c_finalize_reporting.checkpoint_policy_state');
    checkpoint_failure_state = struct_utils.req_struct_field( ...
        checkpoint_policy_state, 'failure_state', ...
        'cerupp_section6c_finalize_reporting.checkpoint_policy_state');

    propagation_completed_requested_distance = ...
        (double(cfg.completed_z_steps) == double(cfg.num_zsteps));
    terminal_propagated_state = resolve_terminal_propagated_state_local( ...
        cfg, run_end_state);
    run_end_state.terminal_propagated_state = terminal_propagated_state;
    propagation_success = ...
        terminal_propagated_state.ok && propagation_completed_requested_distance;
    terminal_store_contract = ...
        resolve_terminal_store_contract_local(run_end_state);
    run_end_state.terminal_store_contract = terminal_store_contract;

    run_end_state.intermediate = build_intermediate_output_state_local( ...
        cfg.output_plan, checkpoint_policy_state, checkpoint_failure_state, ...
        cfg.completed_z_steps, cfg.num_zsteps);
    run_end_state.postprocess = collapse_postprocess_state_local( ...
        run_end_state.postprocess);
    run_end_state.final_outputs = build_initial_final_output_state_local( ...
        cfg, run_end_state, terminal_store_contract);

    warning_ledgers = cfg.warning_ledgers;
    warning_ledgers.run = cfg.run_warn_state;
    warning_ledgers = warning_utils.emit_resetting_run_end_warnings( ...
        'CerUPP:DriverRunEnd', warning_ledgers);
    run_warn_state = warning_ledgers.run;

    postprocess_phase_ok = run_end_state.postprocess.phase_ok;
    postprocess_success = run_end_state.postprocess.ok;
    physics_success = propagation_success;
    latest_pointer_writes_requested = logical( ...
        cfg.output_plan.request.write_latest_successful_run_id_flag);
    latest_successful_pointer_eligible = false;
    latest_fully_packaged_pointer_eligible = false;
    latest_propagation_complete_pointer_eligible = false;
    run_end_state.final_outputs.latest_successful_pointer = ...
        build_pending_pointer_status_local( ...
            latest_pointer_writes_requested, 'pending_post_status_contract');
    run_end_state.final_outputs.latest_fully_packaged_pointer = ...
        build_pending_pointer_status_local( ...
            latest_pointer_writes_requested, 'pending_post_status_contract');
    run_end_state.final_outputs.latest_propagation_complete_pointer = ...
        build_pending_pointer_status_local( ...
            latest_pointer_writes_requested, 'pending_post_status_contract');

    runtime_setup = struct_utils.req_struct_field( ...
        cfg, 'runtime_setup', 'cerupp_section6c_finalize_reporting.runtime_setup');
    pointer_paths = struct_utils.req_struct_field( ...
        struct_utils.req_struct_field( ...
            runtime_setup, 'artifact_paths', ...
            'cerupp_section6c_finalize_reporting.runtime_setup'), ...
        'pointers', 'cerupp_section6c_finalize_reporting.runtime_setup');
    run_id = struct_utils.req_struct_field( ...
        runtime_setup, 'run_id', 'cerupp_section6c_finalize_reporting.runtime_setup');

    run_status_requested = logical(cfg.output_plan.request.write_run_status_flag);
    if ~run_status_requested
        run_status_initial_skipped_reason = 'not_requested';
        run_status_initial_result = 'skipped_not_requested';
    else
        run_status_initial_skipped_reason = '';
        run_status_initial_result = 'pending_write';
    end
    run_end_state.final_outputs.run_status = build_artifact_status_record_local( ...
        run_status_requested, false, true, run_status_initial_skipped_reason, ...
        '', '', run_status_initial_result);

    final_output_write_success_for_status = final_outputs_ok_for_status_local( ...
        run_end_state.final_outputs);
    intermediate_output_write_success_for_status = ...
        intermediate_outputs_ok_local(run_end_state.intermediate);
    reporting_success_for_status = run_end_state.finalization.ok && ...
        terminal_store_contract.matches_accepted_state && ...
        run_end_state.postprocess.ok && ...
        intermediate_output_write_success_for_status && ...
        final_output_write_success_for_status;
    completed_with_all_requested_outputs_for_status = ...
        physics_success && reporting_success_for_status;

    artifact_status = build_artifact_status_tree_local(run_end_state);
    status_extra_fields = build_status_extra_fields_local(struct( ...
        'propagation_success', propagation_success, ...
        'propagation_completed_requested_distance', ...
            propagation_completed_requested_distance, ...
        'physics_success', physics_success, ...
        'postprocess_phase_ok', postprocess_phase_ok, ...
        'postprocess_success', postprocess_success, ...
        'run_end_state', run_end_state, ...
        'run_warn_state', run_warn_state, ...
        'terminal_propagated_state', terminal_propagated_state, ...
        'terminal_store_contract', terminal_store_contract, ...
        'intermediate_output_write_success_for_status', ...
            intermediate_output_write_success_for_status, ...
        'final_output_write_success_for_status', ...
            final_output_write_success_for_status, ...
        'reporting_success_for_status', reporting_success_for_status, ...
        'completed_with_all_requested_outputs_for_status', ...
            completed_with_all_requested_outputs_for_status, ...
        'final_restart_save_ok', cfg.final_restart_save_ok, ...
        'end_snapshot_save_ok', cfg.end_snapshot_save_ok, ...
        'final_full_save_ok', cfg.final_full_save_ok, ...
        'final_a_s_state_finite', cfg.final_a_s_state_finite, ...
        'final_a_f_state_finite', cfg.final_a_f_state_finite, ...
        'final_rho_state_finite', cfg.final_rho_state_finite, ...
        'final_rho_state_shape_ok', cfg.final_rho_state_shape_ok));

    run_status_ctx = cfg.run_status_ctx;
    if run_status_ctx.enabled || run_status_ctx.write_current_pointer
        [attempt_state, attempt_identifier, attempt_message, attempt_reason] = ...
            build_attempt_status_local(physics_success, ...
                propagation_completed_requested_distance, artifact_status, ...
                terminal_propagated_state, ...
                terminal_store_contract.matches_accepted_state, ...
                postprocess_phase_ok, ...
                intermediate_output_write_success_for_status, ...
                final_output_write_success_for_status, ...
                completed_with_all_requested_outputs_for_status);
        status_extra_fields.attempt_reason = attempt_reason;
        [run_warn_state, run_status_ctx] = cfg.finalize_run_status_local( ...
            run_warn_state, run_status_ctx, attempt_state, ...
            attempt_identifier, attempt_message, 'normal_exit', ...
            status_extra_fields);
    end

    run_end_state.final_outputs.run_status = resolve_run_status_record_local( ...
        run_status_requested, run_status_ctx);
    run_end_state.final_outputs.current_pointer = ...
        resolve_current_pointer_record_local( ...
            logical(cfg.output_plan.request.write_current_run_pointer_flag), ...
            run_status_ctx);
    final_output_write_success = final_outputs_ok_after_status_local( ...
        run_end_state.final_outputs);
    intermediate_output_write_success = ...
        intermediate_outputs_ok_local(run_end_state.intermediate);
    reporting_success = run_end_state.finalization.ok && ...
        terminal_store_contract.matches_accepted_state && ...
        run_end_state.postprocess.ok && ...
        intermediate_output_write_success && final_output_write_success;
    completed_with_all_requested_outputs = physics_success && ...
        reporting_success;
    latest_successful_pointer_eligible = ...
        propagation_completed_requested_distance && ...
        logical(cfg.final_a_s_state_finite) && ...
        logical(cfg.final_rho_state_finite) && ...
        postprocess_has_any_ok_family_local(run_end_state.postprocess);
    latest_fully_packaged_pointer_eligible = ...
        completed_with_all_requested_outputs;
    latest_propagation_complete_pointer_eligible = ...
        propagation_completed_requested_distance;
    [run_end_state.final_outputs.latest_successful_pointer, run_warn_state] = ...
        write_pointer_status_local(struct( ...
            'requested', latest_pointer_writes_requested, ...
            'eligible', latest_successful_pointer_eligible, ...
            'run_bucket', struct_utils.req_struct_field( ...
                struct_utils.req_struct_field( ...
                    pointer_paths, 'latest_successful', ...
                    'cerupp_section6c_finalize_reporting.pointer_paths'), ...
                'root', 'cerupp_section6c_finalize_reporting.pointer_paths'), ...
            'pointer_name', struct_utils.req_struct_field( ...
                struct_utils.req_struct_field( ...
                    pointer_paths, 'latest_successful', ...
                    'cerupp_section6c_finalize_reporting.pointer_paths'), ...
                'name', 'cerupp_section6c_finalize_reporting.pointer_paths'), ...
            'run_id', run_id, ...
            'warn_key', 'latest_successful_run_pointer_write_failed', ...
            'warn_id', ...
                'CerUPP:RunStatus:LatestSuccessfulRunPointerWriteFailed', ...
            'failure_tag', 'latest_successful_run_pointer', ...
            'failure_message', 'Could not write latest_successful_run_id.txt.'), ...
            run_warn_state);
    [run_end_state.final_outputs.latest_fully_packaged_pointer, ...
        run_warn_state] = write_pointer_status_local(struct( ...
            'requested', latest_pointer_writes_requested, ...
            'eligible', latest_fully_packaged_pointer_eligible, ...
            'run_bucket', struct_utils.req_struct_field( ...
                struct_utils.req_struct_field( ...
                    pointer_paths, 'latest_fully_packaged', ...
                    'cerupp_section6c_finalize_reporting.pointer_paths'), ...
                'root', 'cerupp_section6c_finalize_reporting.pointer_paths'), ...
            'pointer_name', struct_utils.req_struct_field( ...
                struct_utils.req_struct_field( ...
                    pointer_paths, 'latest_fully_packaged', ...
                    'cerupp_section6c_finalize_reporting.pointer_paths'), ...
                'name', 'cerupp_section6c_finalize_reporting.pointer_paths'), ...
            'run_id', run_id, ...
            'warn_key', 'latest_fully_packaged_run_pointer_write_failed', ...
            'warn_id', ...
                'CerUPP:RunStatus:LatestFullyPackagedRunPointerWriteFailed', ...
            'failure_tag', 'latest_fully_packaged_run_pointer', ...
            'failure_message', 'Could not write latest_fully_packaged_run_id.txt.'), ...
            run_warn_state);
    [run_end_state.final_outputs.latest_propagation_complete_pointer, ...
        run_warn_state] = write_pointer_status_local(struct( ...
            'requested', latest_pointer_writes_requested, ...
            'eligible', latest_propagation_complete_pointer_eligible, ...
            'run_bucket', struct_utils.req_struct_field( ...
                struct_utils.req_struct_field( ...
                    pointer_paths, 'latest_propagation_complete', ...
                    'cerupp_section6c_finalize_reporting.pointer_paths'), ...
                'root', 'cerupp_section6c_finalize_reporting.pointer_paths'), ...
            'pointer_name', struct_utils.req_struct_field( ...
                struct_utils.req_struct_field( ...
                    pointer_paths, 'latest_propagation_complete', ...
                    'cerupp_section6c_finalize_reporting.pointer_paths'), ...
                'name', 'cerupp_section6c_finalize_reporting.pointer_paths'), ...
            'run_id', run_id, ...
            'warn_key', 'latest_propagation_complete_run_pointer_write_failed', ...
            'warn_id', ...
                'CerUPP:RunStatus:LatestPropagationCompleteRunPointerWriteFailed', ...
            'failure_tag', 'latest_propagation_complete_run_pointer', ...
            'failure_message', ...
                'Could not write latest_propagation_complete_run_id.txt.'), ...
            run_warn_state);
    final_output_write_success = final_outputs_ok_after_status_local( ...
        run_end_state.final_outputs);
    intermediate_output_write_success = ...
        intermediate_outputs_ok_local(run_end_state.intermediate);
    reporting_success = run_end_state.finalization.ok && ...
        terminal_store_contract.matches_accepted_state && ...
        run_end_state.postprocess.ok && ...
        intermediate_output_write_success && final_output_write_success;
    completed_with_all_requested_outputs = physics_success && ...
        reporting_success;
    [attempt_state, attempt_identifier, attempt_message, attempt_reason] = ...
        build_attempt_status_local(physics_success, ...
            propagation_completed_requested_distance, ...
            build_artifact_status_tree_local(run_end_state), ...
            terminal_propagated_state, ...
            terminal_store_contract.matches_accepted_state, ...
            postprocess_phase_ok, ...
            intermediate_output_write_success, ...
            final_output_write_success, ...
            completed_with_all_requested_outputs);
    status_extra_fields = ...
        extend_status_extra_fields_with_latest_pointer_results_local( ...
            status_extra_fields, run_end_state, ...
            latest_successful_pointer_eligible, ...
            latest_fully_packaged_pointer_eligible, ...
            latest_propagation_complete_pointer_eligible, ...
            final_output_write_success, reporting_success, ...
            completed_with_all_requested_outputs, attempt_reason);
    if latest_pointer_writes_requested && run_status_requested
        [run_warn_state, run_status_ctx] = ...
            run_output_utils.republish_final_run_status_after_pointer_writes( ...
                struct( ...
                    'run_status_ctx', run_status_ctx, ...
                    'attempt_state', attempt_state, ...
                    'error_id', attempt_identifier, ...
                    'error_message', attempt_message, ...
                    'restart_compat_version', runtime_setup.restart_compat_version, ...
                    'release_version', runtime_setup.release_version, ...
                    'curr_cerupp_version', runtime_setup.curr_cerupp_version, ...
                    'status_extra_fields', status_extra_fields, ...
                    'status_phase_tag', run_warn_state_utils.phase_end(), ...
                    'status_warn_key', 'run_status_write_failed', ...
                    'status_warn_id', 'CerUPP:RunStatus:RunStatusWriteFailed', ...
                    'status_failure_tag', 'run_status_final_write'), ...
                run_warn_state);
    end
    run_end_state.final_outputs.run_status = resolve_run_status_record_local( ...
        run_status_requested, run_status_ctx);
    final_output_write_success = final_outputs_ok_after_status_local( ...
        run_end_state.final_outputs);
    intermediate_output_write_success = ...
        intermediate_outputs_ok_local(run_end_state.intermediate);
    reporting_success = run_end_state.finalization.ok && ...
        terminal_store_contract.matches_accepted_state && ...
        run_end_state.postprocess.ok && ...
        intermediate_output_write_success && final_output_write_success;
    completed_with_all_requested_outputs = physics_success && ...
        reporting_success;
    status_extra_fields.status_failure_categories = ...
        build_status_failure_categories_local(struct( ...
        'run_end_state', run_end_state, ...
        'run_warn_state', run_warn_state, ...
        'terminal_propagated_state', terminal_propagated_state, ...
        'terminal_store_contract', terminal_store_contract));
    run_end_state.reporting = struct( ...
        'physics_success', physics_success, ...
        'terminal_propagated_state_success', terminal_propagated_state.ok, ...
        'terminal_propagated_state_failure_class', ...
            terminal_propagated_state.failure_class, ...
        'status_failure_categories', ...
            status_extra_fields.status_failure_categories, ...
        'postprocess_phase_ok', postprocess_phase_ok, ...
        'postprocess_success', postprocess_success, ...
        'intermediate_output_success', intermediate_output_write_success, ...
        'final_output_success', final_output_write_success, ...
        'reporting_success', reporting_success, ...
        'completed_with_all_requested_outputs', ...
            completed_with_all_requested_outputs, ...
        'postprop_finalization_success', run_end_state.finalization.ok, ...
        'terminal_store_matches_accepted_state', ...
            terminal_store_contract.matches_accepted_state, ...
        'terminal_store_contract_reason', terminal_store_contract.reason, ...
        'latest_successful_pointer_eligible', ...
            latest_successful_pointer_eligible, ...
        'latest_fully_packaged_pointer_eligible', ...
            latest_fully_packaged_pointer_eligible, ...
        'latest_propagation_complete_pointer_eligible', ...
            latest_propagation_complete_pointer_eligible);
    artifact_status = build_artifact_status_tree_local(run_end_state);

    section6c_state = struct( ...
        'run_end_state', run_end_state, ...
        'warning_ledgers', warning_ledgers, ...
        'run_warn_state', run_warn_state, ...
        'run_status_ctx', run_status_ctx, ...
        'postprocess_phase_ok', postprocess_phase_ok, ...
        'postprocess_success', postprocess_success, ...
        'propagation_completed_requested_distance', ...
            propagation_completed_requested_distance, ...
        'propagation_success', propagation_success, ...
        'physics_success', physics_success, ...
        'latest_successful_pointer_eligible', ...
            latest_successful_pointer_eligible, ...
        'latest_fully_packaged_pointer_eligible', ...
            latest_fully_packaged_pointer_eligible, ...
        'latest_propagation_complete_pointer_eligible', ...
            latest_propagation_complete_pointer_eligible, ...
        'artifact_status', artifact_status, ...
        'status_extra_fields', status_extra_fields, ...
        'final_output_write_success', final_output_write_success, ...
        'intermediate_output_write_success', ...
            intermediate_output_write_success, ...
        'reporting_success', reporting_success, ...
        'completed_with_all_requested_outputs', ...
            completed_with_all_requested_outputs);
end

function postprocess_state = collapse_postprocess_state_local(postprocess_state)
    postprocess_state.attempted = logical(postprocess_state.attempted);
    if ~postprocess_state.requested
        postprocess_state.skipped_reason = 'not_requested';
        postprocess_state.ok = true;
        postprocess_state.result = 'skipped_not_requested';
    elseif ~postprocess_state.phase_ok
        postprocess_state.skipped_reason = ...
            postprocess_state.requested_outputs_skipped_reason;
        postprocess_state.ok = false;
        postprocess_state.result = 'failed';
    elseif ~postprocess_state.requested_outputs_complete
        postprocess_state.skipped_reason = ...
            postprocess_state.requested_outputs_skipped_reason;
        postprocess_state.ok = false;
        postprocess_state.result = 'failed';
    else
        postprocess_state.skipped_reason = '';
        postprocess_state.ok = true;
        postprocess_state.result = 'succeeded';
    end
end

function intermediate_state = build_intermediate_output_state_local( ...
        output_plan, checkpoint_policy_state, checkpoint_failure_state, ...
        completed_z_steps, num_zsteps)
    request_cfg = struct_utils.req_struct_field( ...
        output_plan, 'request', 'cerupp_section6c_finalize_reporting.output_plan');
    cadence_cfg = struct_utils.req_struct_field( ...
        output_plan, 'cadence', 'cerupp_section6c_finalize_reporting.output_plan');
    restart_due_before_run_end = any_restart_due_before_run_end_local( ...
        completed_z_steps, num_zsteps, cadence_cfg.checkpoint_stride_steps, ...
        request_cfg.save_final_restart_checkpoint_flag);
    snapshot_due_before_run_end = any_snapshot_due_before_run_end_local( ...
        completed_z_steps, num_zsteps, ...
        cadence_cfg.a_s_rho_snapshot_checkpoint_stride_steps);
    fullsave_due_before_run_end = any_fullsave_due_before_run_end_local( ...
        completed_z_steps, num_zsteps, ...
        cadence_cfg.diagnostic_store_stride_steps, ...
        cadence_cfg.checkpoint_stride_steps);
    intermediate_state = struct( ...
        'restart', build_stream_status_local(struct( ...
            'requested', logical(request_cfg.intermediate_saves), ...
            'due_before_run_end', restart_due_before_run_end, ...
            'attempt_count', checkpoint_failure_state.restart_attempt_count, ...
            'success_count', checkpoint_failure_state.restart_success_count, ...
            'last_attempt_ok', checkpoint_failure_state.restart_last_attempt_ok, ...
            'stream_enabled', checkpoint_policy_state.restart_enabled, ...
            'disabled_after_repeated_failures', ...
                checkpoint_failure_state.disable_restart_only, ...
            'ever_failed', checkpoint_failure_state.restart_ever_failed, ...
            'current_error_id', checkpoint_failure_state.error_id, ...
            'current_error_message', checkpoint_failure_state.error_message, ...
            'last_failure_error_id', checkpoint_failure_state.error_id, ...
            'last_failure_error_message', checkpoint_failure_state.error_message)), ...
        'snapshot', build_stream_status_local(struct( ...
            'requested', logical(request_cfg.intermediate_saves), ...
            'due_before_run_end', snapshot_due_before_run_end, ...
            'attempt_count', checkpoint_failure_state.snapshot_attempt_count, ...
            'success_count', checkpoint_failure_state.snapshot_success_count, ...
            'last_attempt_ok', checkpoint_failure_state.snapshot_last_attempt_ok, ...
            'stream_enabled', checkpoint_policy_state.snapshot_enabled, ...
            'disabled_after_repeated_failures', ...
                checkpoint_failure_state.disable_snapshot_only, ...
            'ever_failed', checkpoint_failure_state.snapshot_ever_failed, ...
            'current_error_id', checkpoint_failure_state.snapshot_error_id, ...
            'current_error_message', checkpoint_failure_state.snapshot_error_message, ...
            'last_failure_error_id', checkpoint_failure_state.snapshot_error_id, ...
            'last_failure_error_message', ...
                checkpoint_failure_state.snapshot_error_message)), ...
        'fullsave', build_stream_status_local(struct( ...
            'requested', logical( ...
                request_cfg.intermediate_saves && ...
                request_cfg.checkpoint_full_save_flag), ...
            'due_before_run_end', fullsave_due_before_run_end, ...
            'attempt_count', checkpoint_failure_state.fullsave_attempt_count, ...
            'success_count', checkpoint_failure_state.fullsave_success_count, ...
            'last_attempt_ok', checkpoint_failure_state.fullsave_last_attempt_ok, ...
            'stream_enabled', checkpoint_policy_state.fullsave_enabled, ...
            'disabled_after_repeated_failures', ...
                checkpoint_failure_state.disable_fullsave_only, ...
            'ever_failed', checkpoint_failure_state.fullsave_ever_failed, ...
            'current_error_id', checkpoint_failure_state.fullsave_error_id, ...
            'current_error_message', checkpoint_failure_state.fullsave_error_message, ...
            'last_failure_error_id', checkpoint_failure_state.fullsave_error_id, ...
            'last_failure_error_message', ...
                checkpoint_failure_state.fullsave_error_message)));
end

function stream_status = build_stream_status_local(cfg)
    attempted = (cfg.attempt_count > 0);
    due_before_run_end = logical(struct_utils.opt_struct_field( ...
        cfg, 'due_before_run_end', attempted));
    last_attempt_ok = logical(cfg.last_attempt_ok);
    current_error_id = '';
    current_error_message = '';
    if attempted && ~last_attempt_ok
        current_error_id = cfg.current_error_id;
        current_error_message = cfg.current_error_message;
    end
    skipped_reason = '';
    if ~cfg.requested
        skipped_reason = 'not_requested';
    elseif ~due_before_run_end
        skipped_reason = 'not_due_before_run_end';
    elseif ~attempted
        skipped_reason = 'not_attempted_before_run_end';
    elseif logical(cfg.disabled_after_repeated_failures)
        skipped_reason = 'disabled_after_repeated_failures';
    end
    stream_status = struct( ...
        'requested', logical(cfg.requested), ...
        'due_before_run_end', due_before_run_end, ...
        'attempted', attempted, ...
        'ok', (~cfg.requested) || (~due_before_run_end) || ...
            (attempted && last_attempt_ok), ...
        'produced_artifact', (cfg.success_count > 0), ...
        'skipped_reason', skipped_reason, ...
        'error_id', current_error_id, ...
        'error_message', current_error_message, ...
        'stream_enabled', logical(cfg.stream_enabled), ...
        'last_attempt_ok', last_attempt_ok, ...
        'ever_failed', logical(cfg.ever_failed), ...
        'disabled_after_repeated_failures', ...
            logical(cfg.disabled_after_repeated_failures), ...
        'last_failure_error_id', cfg.last_failure_error_id, ...
        'last_failure_error_message', cfg.last_failure_error_message);
end

function final_outputs = build_initial_final_output_state_local( ...
        cfg, run_end_state, terminal_store_contract)
    final_restart_requested = logical( ...
        cfg.output_plan.request.save_final_restart_checkpoint_flag);
    final_restart_write_state = struct_utils.req_struct_field( ...
        cfg, 'final_restart_write_state', ...
        'cerupp_section6c_finalize_reporting.final_restart_write_state');
    final_restart_attempted = final_restart_requested && ...
        (cfg.final_restart_attempted_postprop || ...
         struct_utils.req_struct_field( ...
             final_restart_write_state, 'attempted', ...
             'cerupp_section6c_finalize_reporting.final_restart_write_state'));
    final_restart_error_id = '';
    final_restart_error_message = '';
    final_restart_skipped_reason = '';
    if ~final_restart_requested
        final_restart_skipped_reason = 'not_requested';
    elseif ~run_end_state.finalization.ok && ~cfg.final_restart_save_ok
        if ~isempty(cfg.final_restart_fallback_error_id)
            final_restart_skipped_reason = ...
                'final_restart_after_finalization_failure_failed';
            final_restart_error_id = cfg.final_restart_fallback_error_id;
            final_restart_error_message = ...
                cfg.final_restart_fallback_error_message;
        else
            final_restart_skipped_reason = char(string( ...
                run_end_state.finalization.skipped_reason));
            if isempty(final_restart_skipped_reason)
                final_restart_skipped_reason = 'upstream_finalization_failed';
            end
            final_restart_error_id = run_end_state.finalization.error_id;
            final_restart_error_message = ...
                run_end_state.finalization.error_message;
        end
    elseif ~cfg.final_restart_save_ok
        final_restart_skipped_reason = 'final_restart_failed';
        final_restart_error_id = 'CerUPP:FinalRestartOutputFailed';
        final_restart_error_message = ...
            'Final restart checkpoint prepare/write failed earlier in the end-of-run path.';
    end
    if ~final_restart_requested
        final_restart_result = 'skipped_not_requested';
    elseif cfg.final_restart_save_ok
        final_restart_result = 'succeeded';
    elseif ~run_end_state.finalization.ok && ...
            ~strcmp(final_restart_skipped_reason, ...
                'final_restart_after_finalization_failure_failed')
        final_restart_result = 'skipped_upstream_failure';
    else
        final_restart_result = 'failed';
    end
    final_restart_payload_kind = char(string(struct_utils.opt_struct_field( ...
        final_restart_write_state, 'payload_kind', 'none')));
    final_restart_degraded_fallback_used = ...
        final_restart_requested && cfg.final_restart_save_ok && ...
        strcmp(final_restart_payload_kind, 'minimal');

    end_snapshot_requested = logical(cfg.output_plan.request.save_end_snapshot_flag);
    end_snapshot_write_state = struct_utils.opt_struct_field( ...
        cfg, 'end_snapshot_write_state', struct());
    end_snapshot_attempted = logical(struct_utils.opt_struct_field( ...
        end_snapshot_write_state, 'attempted', ...
        end_snapshot_requested && cfg.end_snapshot_attempted_postprop));
    end_snapshot_error_id = char(string(struct_utils.opt_struct_field( ...
        end_snapshot_write_state, 'error_id', '')));
    end_snapshot_error_message = char(string(struct_utils.opt_struct_field( ...
        end_snapshot_write_state, 'error_message', '')));
    end_snapshot_skipped_reason = char(string(struct_utils.opt_struct_field( ...
        end_snapshot_write_state, 'blocked_reason', '')));
    if ~end_snapshot_requested
        end_snapshot_skipped_reason = 'not_requested';
    elseif isempty(end_snapshot_skipped_reason) && ...
            ~logical(struct_utils.opt_struct_field( ...
                end_snapshot_write_state, 'ok', cfg.end_snapshot_save_ok))
        end_snapshot_skipped_reason = 'end_snapshot_failed';
        if isempty(end_snapshot_error_id)
            end_snapshot_error_id = 'CerUPP:EndSnapshotOutputFailed';
        end
        if isempty(end_snapshot_error_message)
            end_snapshot_error_message = ...
                'End snapshot prepare/write failed earlier in the end-of-run path.';
        end
    end
    if ~end_snapshot_requested
        end_snapshot_result = 'skipped_not_requested';
    elseif logical(struct_utils.opt_struct_field( ...
            end_snapshot_write_state, 'ok', cfg.end_snapshot_save_ok))
        end_snapshot_result = 'succeeded';
    elseif ~end_snapshot_attempted && ~isempty(end_snapshot_skipped_reason)
        end_snapshot_result = 'skipped_contract_not_met';
    else
        end_snapshot_result = 'failed';
    end

    final_fullsave_requested = logical( ...
        cfg.output_plan.request.save_final_full_output_flag);
    final_fullsave_attempted = final_fullsave_requested && ...
        run_end_state.finalization.ok && ~isempty(cfg.final_fullsave_build_cfg);
    final_fullsave_skipped_reason = '';
    final_fullsave_error_id = cfg.final_full_save_error_id;
    final_fullsave_error_message = cfg.final_full_save_error_message;
    if ~final_fullsave_requested
        final_fullsave_skipped_reason = 'not_requested';
    elseif ~terminal_store_contract.matches_accepted_state
        final_fullsave_skipped_reason = ...
            resolve_terminal_store_skipped_reason_local(terminal_store_contract);
        final_fullsave_error_id = 'CerUPP:TerminalStoreMismatch';
        final_fullsave_error_message = ...
            ['The packed stored diagnostic bundle no longer matched the ', ...
             'terminal field after a stored-plane ', ...
             'failure, so CerUPP withheld the ordinary final fullsave ', ...
             'diagnostic store.'];
    elseif ~run_end_state.finalization.ok
        final_fullsave_skipped_reason = char(string( ...
            run_end_state.finalization.skipped_reason));
        if isempty(final_fullsave_skipped_reason)
            final_fullsave_skipped_reason = 'upstream_finalization_failed';
        end
    elseif isempty(cfg.final_fullsave_build_cfg)
        final_fullsave_skipped_reason = 'build_cfg_unavailable';
    elseif ~cfg.final_full_save_ok
        final_fullsave_skipped_reason = 'final_fullsave_failed';
    end
    if ~final_fullsave_requested
        final_fullsave_result = 'skipped_not_requested';
    elseif cfg.final_full_save_ok
        final_fullsave_result = 'succeeded';
    elseif ~terminal_store_contract.matches_accepted_state
        final_fullsave_result = 'skipped_contract_not_met';
    elseif ~run_end_state.finalization.ok
        final_fullsave_result = 'skipped_upstream_failure';
    else
        final_fullsave_result = 'failed';
    end

    final_outputs = struct( ...
        'restart', build_artifact_status_record_local( ...
            final_restart_requested, final_restart_attempted, ...
            (~final_restart_requested) || cfg.final_restart_save_ok, ...
            final_restart_skipped_reason, final_restart_error_id, ...
            final_restart_error_message, final_restart_result), ...
        'snapshot', build_artifact_status_record_local( ...
            end_snapshot_requested, end_snapshot_attempted, ...
            (~end_snapshot_requested) || cfg.end_snapshot_save_ok, ...
            end_snapshot_skipped_reason, end_snapshot_error_id, ...
            end_snapshot_error_message, end_snapshot_result), ...
        'fullsave', build_artifact_status_record_local( ...
            final_fullsave_requested, final_fullsave_attempted, ...
            (~final_fullsave_requested) || cfg.final_full_save_ok, ...
            final_fullsave_skipped_reason, final_fullsave_error_id, ...
            final_fullsave_error_message, final_fullsave_result));
    final_outputs.restart.payload_kind = final_restart_payload_kind;
    final_outputs.restart.degraded_fallback_used = ...
        final_restart_degraded_fallback_used;
    final_outputs.restart.complete_package_ok = ...
        final_outputs.restart.ok && ...
        ~final_restart_degraded_fallback_used;
    final_outputs.snapshot.store_z_source = char(string( ...
        struct_utils.opt_struct_field( ...
            end_snapshot_write_state, 'store_z_source', 'none')));
end

function [pointer_status, run_warn_state] = write_pointer_status_local(cfg, run_warn_state)
    attempted = false;
    pointer_ok = true;
    skipped_reason = '';
    error_id = '';
    error_message = '';
    if ~cfg.requested
        skipped_reason = 'not_requested';
    elseif ~cfg.eligible
        skipped_reason = 'contract_not_met';
    else
        attempted = true;
        [run_warn_state, pointer_ok] = checkpoint_utils.write_run_id_pointer( ...
            struct( ...
                'run_bucket', cfg.run_bucket, ...
                'pointer_name', cfg.pointer_name, ...
                'run_id', cfg.run_id, ...
                'phase_tag', 'end', ...
                'warn_key', cfg.warn_key, ...
                'warn_id', cfg.warn_id, ...
                'failure_tag', cfg.failure_tag), ...
            run_warn_state);
        if ~pointer_ok
            skipped_reason = 'pointer_write_failed';
            error_id = cfg.warn_id;
            error_message = cfg.failure_message;
        end
    end
    if ~cfg.requested
        result = 'skipped_not_requested';
    elseif ~cfg.eligible
        result = 'skipped_contract_not_met';
    elseif pointer_ok
        result = 'succeeded';
    else
        result = 'failed';
    end
    pointer_status = build_artifact_status_record_local( ...
        cfg.requested, attempted, ...
        (~cfg.requested) || (cfg.eligible && pointer_ok), skipped_reason, ...
        error_id, error_message, result);
end

function run_status_record = resolve_run_status_record_local( ...
        run_status_requested, run_status_ctx)
    run_status_attempted = false;
    run_status_write_ok = true;
    run_status_skipped_reason = '';
    run_status_error_id = '';
    run_status_error_message = '';
    if ~run_status_requested
        run_status_skipped_reason = 'not_requested';
    elseif isfield(run_status_ctx, 'last_finalize_status') && ...
            isstruct(run_status_ctx.last_finalize_status)
        run_status_attempted = logical(struct_utils.opt_struct_field( ...
            run_status_ctx.last_finalize_status, ...
            'status_write_attempted', false));
        run_status_write_ok = logical(struct_utils.opt_struct_field( ...
            run_status_ctx.last_finalize_status, 'status_write_ok', true));
        if logical(struct_utils.opt_struct_field( ...
                run_status_ctx.last_finalize_status, ...
                'status_write_post_latest_pointer_attempted', false)) && ...
                ~logical(struct_utils.opt_struct_field( ...
                run_status_ctx.last_finalize_status, ...
                'status_write_post_latest_pointer_ok', true))
            run_status_skipped_reason = ...
                'run_status_post_latest_pointer_refresh_failed';
            run_status_error_id = ...
                'CerUPP:RunStatus:RunStatusPostLatestPointerRefreshFailed';
            run_status_error_message = ...
                'Could not refresh run_status.json after the late latest-pointer writes.';
        elseif ~run_status_write_ok
            run_status_skipped_reason = 'run_status_write_failed';
            run_status_error_id = 'CerUPP:RunStatus:RunStatusWriteFailed';
            run_status_error_message = ...
                'Could not write the final run_status.json file.';
        end
    else
        run_status_attempted = true;
        run_status_write_ok = false;
        run_status_skipped_reason = 'run_status_write_failed';
        run_status_error_id = 'CerUPP:RunStatus:RunStatusWriteFailed';
        run_status_error_message = ...
            'Final run-status write did not report a completion status.';
    end
    if ~run_status_requested
        run_status_result = 'skipped_not_requested';
    elseif run_status_write_ok
        run_status_result = 'succeeded';
    else
        run_status_result = 'failed';
    end
    run_status_record = build_artifact_status_record_local( ...
        run_status_requested, run_status_attempted, ...
        (~run_status_requested) || run_status_write_ok, ...
        run_status_skipped_reason, run_status_error_id, ...
        run_status_error_message, run_status_result);
end

function current_pointer_record = resolve_current_pointer_record_local( ...
        current_pointer_requested, run_status_ctx)
    if ~logical(current_pointer_requested)
        current_pointer_record = build_artifact_status_record_local( ...
            false, false, true, 'not_requested', '', '', ...
            'skipped_not_requested');
        return;
    end

    current_pointer_attempted = false;
    current_pointer_ok = true;
    current_pointer_skipped_reason = '';
    current_pointer_error_id = '';
    current_pointer_error_message = '';
    current_pointer_result = 'pending_status_finalize';
    if isfield(run_status_ctx, 'last_finalize_status') && ...
            isstruct(run_status_ctx.last_finalize_status)
        finalize_status = run_status_ctx.last_finalize_status;
        current_pointer_attempted = logical(struct_utils.opt_struct_field( ...
            finalize_status, 'current_pointer_delete_attempted', false));
        current_pointer_ok = logical(struct_utils.opt_struct_field( ...
            finalize_status, 'current_pointer_delete_ok', true));
        current_pointer_status = char(string(struct_utils.opt_struct_field( ...
            finalize_status, 'current_pointer_delete_status', 'skipped')));
        switch current_pointer_status
            case {'deleted', 'absent'}
                current_pointer_result = 'succeeded';
            case 'skipped'
                current_pointer_result = 'skipped_not_requested';
                current_pointer_skipped_reason = 'not_requested';
            case 'failed'
                current_pointer_result = 'failed';
                current_pointer_skipped_reason = ...
                    'current_pointer_delete_failed';
                current_pointer_error_id = ...
                    'CerUPP:RunStatus:CurrentRunPointerDeleteFailed';
                current_pointer_error_message = ...
                    'Could not retire current_run_id.txt at run end.';
                current_pointer_ok = false;
            otherwise
                current_pointer_result = current_pointer_status;
                if ~current_pointer_attempted
                    current_pointer_skipped_reason = current_pointer_status;
                end
                current_pointer_ok = false;
        end
    else
        current_pointer_ok = false;
        current_pointer_skipped_reason = ...
            'current_pointer_finalize_status_missing';
        current_pointer_error_id = ...
            'CerUPP:RunStatus:CurrentRunPointerDeleteStatusMissing';
        current_pointer_error_message = ...
            'The final run-status path did not report the current pointer cleanup result.';
        current_pointer_result = 'failed';
    end

    current_pointer_record = build_artifact_status_record_local( ...
        true, current_pointer_attempted, current_pointer_ok, ...
        current_pointer_skipped_reason, current_pointer_error_id, ...
        current_pointer_error_message, current_pointer_result);
end

function [attempt_state, attempt_identifier, attempt_message, attempt_reason] = ...
        build_attempt_status_local(physics_success, ...
        propagation_completed_requested_distance, artifact_status, ...
        terminal_propagated_state, ...
        terminal_store_matches_accepted_state, ...
        postprocess_phase_ok, intermediate_output_write_success_for_status, ...
        final_output_write_success_for_status, ...
        completed_with_all_requested_outputs_for_status)
    attempt_state = 'success';
    attempt_identifier = '';
    attempt_message = '';
    attempt_reason = 'normal_exit';
    if ~physics_success
        attempt_state = 'failed';
        if isstruct(terminal_propagated_state) && ...
                ~logical(struct_utils.opt_struct_field( ...
                terminal_propagated_state, 'ok', false))
            attempt_identifier = 'CerUPP:BadPropagatedTerminalState';
            attempt_message = ...
                'Run reached the end of cerupp.m, but final A_S, A_F, and/or rho failed the terminal propagated-state contract.';
            attempt_reason = 'bad_propagated_state';
        elseif ~propagation_completed_requested_distance
            attempt_identifier = 'CerUPP:RunStoppedBeforeRequestedDistance';
            attempt_message = ...
                'Run stopped before it reached the requested propagation distance.';
            attempt_reason = 'early_propagation_stop';
        else
            attempt_identifier = 'CerUPP:BadPropagatedTerminalState';
            attempt_message = ...
                'Run reached the end of cerupp.m, but final A_S, A_F, and/or rho failed the terminal propagated-state contract.';
            attempt_reason = 'bad_propagated_state';
        end
    elseif ~completed_with_all_requested_outputs_for_status
        attempt_state = 'partial_failed';
        [attempt_identifier, attempt_message] = ...
            resolve_primary_output_failure_local(artifact_status);
        if ~artifact_status.final.finalization.ok
            attempt_reason = 'normal_exit_with_postprop_finalization_failure';
        elseif ~terminal_store_matches_accepted_state
            attempt_reason = 'normal_exit_with_stale_terminal_store_bundle';
        elseif ~logical(struct_utils.opt_struct_field( ...
                artifact_status.final.restart, 'complete_package_ok', true))
            attempt_reason = 'normal_exit_with_degraded_final_restart';
        elseif ~postprocess_phase_ok
            attempt_reason = 'normal_exit_with_section6a_phase_failure';
        elseif ~artifact_status.final.postprocess.ok
            attempt_reason = 'normal_exit_with_section6a_output_failures';
        elseif ~intermediate_output_write_success_for_status
            attempt_reason = ...
                'normal_exit_with_intermediate_output_write_failures';
        elseif ~final_output_write_success_for_status
            attempt_reason = 'normal_exit_with_final_output_write_failures';
        else
            attempt_reason = 'normal_exit_with_output_gaps';
        end
    end
end

function [error_id, error_message] = resolve_primary_output_failure_local(artifact_status)
% Pick one concrete output-side failure id/message for the late status republish.

    error_id = '';
    error_message = '';
    if ~(isstruct(artifact_status) && isfield(artifact_status, 'final') && ...
            isstruct(artifact_status.final))
        return;
    end
    candidate_fields = { ...
        'current_pointer', ...
        'run_status', ...
        'latest_successful_pointer', ...
        'latest_fully_packaged_pointer', ...
        'latest_propagation_complete_pointer', ...
        'restart', ...
        'snapshot', ...
        'fullsave', ...
        'postprocess', ...
        'finalization'};
    for idx = 1:numel(candidate_fields)
        record = struct_utils.opt_struct_field( ...
            artifact_status.final, candidate_fields{idx}, struct());
        if ~(isstruct(record) && isscalar(record) && ...
                ~logical(struct_utils.opt_struct_field(record, 'ok', true)))
            continue;
        end
        error_id = char(string(struct_utils.opt_struct_field( ...
            record, 'error_id', '')));
        error_message = char(string(struct_utils.opt_struct_field( ...
            record, 'error_message', '')));
        if ~isempty(error_id) || ~isempty(error_message)
            return;
        end
    end
end

function categories = build_status_failure_categories_local(cfg)
    run_end_state = cfg.run_end_state;
    terminal_state = struct_utils.opt_struct_field( ...
        cfg, 'terminal_propagated_state', struct());
    output_counts = count_output_io_failure_tags_local( ...
        struct_utils.opt_struct_field(cfg, 'run_warn_state', struct()));
    categories = struct( ...
        'bad_propagated_state', build_status_category_record_local( ...
            logical(struct_utils.opt_struct_field(terminal_state, 'ok', true)), ...
            'fatal', char(string(struct_utils.opt_struct_field( ...
            terminal_state, 'failure_class', 'none'))), ...
            strjoin(struct_utils.opt_struct_field( ...
            terminal_state, 'failure_tags', {}), ','), 0), ...
        'postprop_finalization', build_status_category_record_local( ...
            run_end_state.finalization.ok, 'failure', 'postprop_finalization', ...
            run_end_state.finalization.skipped_reason, 0), ...
        'terminal_store', build_status_category_record_local( ...
            cfg.terminal_store_contract.matches_accepted_state, 'failure', ...
            'terminal_store_mismatch', cfg.terminal_store_contract.reason, 0), ...
        'postprocess_family', build_status_category_record_local( ...
            run_end_state.postprocess.ok, 'failure', 'postprocess_family', ...
            run_end_state.postprocess.requested_outputs_skipped_reason, ...
            double(run_end_state.postprocess.family_failure_count) + ...
            double(run_end_state.postprocess.family_blocking_skip_count)), ...
        'plot_write', build_status_category_record_local( ...
            output_counts.plot_write == 0, 'failure', 'plot_write', ...
            'output_io_plot_write_tags', output_counts.plot_write), ...
        'restart_save', build_status_category_record_local( ...
            output_counts.restart_save == 0, 'failure', 'restart_save', ...
            'output_io_restart_save_tags', output_counts.restart_save), ...
        'final_save', build_status_category_record_local( ...
            output_counts.final_save == 0, 'failure', 'final_save', ...
            'output_io_final_save_tags', output_counts.final_save), ...
        'run_status_or_pointer_write', build_status_category_record_local( ...
            output_counts.status_pointer_write == 0, 'failure', ...
            'run_status_or_pointer_write', ...
            'output_io_status_pointer_tags', output_counts.status_pointer_write), ...
        'diagnostic_display_nan', build_status_category_record_local( ...
            true, 'warning', 'diagnostic_display_nan', ...
            'diagnostic_display_nonfinite_log_only', output_counts.diagnostic_info));
end

function category = build_status_category_record_local( ...
        ok, severity, failure_class, reason, count)
    category = struct( ...
        'ok', logical(ok), ...
        'failed', ~logical(ok), ...
        'severity', char(string(severity)), ...
        'failure_class', char(string(failure_class)), ...
        'reason', char(string(reason)), ...
        'count', double(count));
end

function counts = count_output_io_failure_tags_local(run_warn_state)
    counts = struct( ...
        'plot_write', 0, ...
        'restart_save', 0, ...
        'final_save', 0, ...
        'status_pointer_write', 0, ...
        'diagnostic_info', 0);
    if ~(isstruct(run_warn_state) && isfield(run_warn_state, 'output_io') && ...
            isstruct(run_warn_state.output_io) && isfield(run_warn_state.output_io, 'records'))
        return;
    end
    output_io_records = run_warn_state.output_io.records;
    plot_tags = {'png_export', 'fig_export', 'plot_output_dir_create'};
    restart_tags = {'intermediate_checkpoint', 'intermediate_checkpoint_fullsave', ...
        'a_s_rho_snapshot_checkpoint', 'final_restart_checkpoint'};
    final_save_tags = {'final_full_save', 'final_fullsave_build_failed', ...
        'end_snapshot_save'};
    status_pointer_tags = {'run_status_setup_write', 'run_status_final_write', ...
        'run_status_failure_write', 'current_run_pointer', ...
        'current_run_pointer_delete', 'latest_successful_run_pointer', ...
        'latest_fully_packaged_run_pointer', ...
        'latest_propagation_complete_pointer'};
    diagnostic_info_tags = {'nonfinite_diagnostic_log', 'output_io'};
    for rec_idx = 1:numel(output_io_records)
        rec = output_io_records(rec_idx);
        if ~(isstruct(rec) && isfield(rec, 'tag'))
            continue;
        end
        tag_value = char(string(rec.tag));
        rec_count = 1;
        if isfield(rec, 'count') && isnumeric(rec.count) && ...
                isfinite(rec.count)
            rec_count = max(floor(double(rec.count)), 0);
        end
        if any(strcmp(tag_value, diagnostic_info_tags))
            counts.diagnostic_info = counts.diagnostic_info + rec_count;
        elseif any(strcmp(tag_value, plot_tags))
            counts.plot_write = counts.plot_write + rec_count;
        elseif any(strcmp(tag_value, restart_tags))
            counts.restart_save = counts.restart_save + rec_count;
        elseif any(strcmp(tag_value, final_save_tags))
            counts.final_save = counts.final_save + rec_count;
        elseif any(strcmp(tag_value, status_pointer_tags))
            counts.status_pointer_write = counts.status_pointer_write + rec_count;
        end
    end
end

function status_extra_fields = build_status_extra_fields_local(cfg)
    terminal_propagated_state = struct_utils.opt_struct_field( ...
        cfg, 'terminal_propagated_state', struct());
    status_failure_categories = build_status_failure_categories_local(cfg);
    status_extra_fields = struct( ...
        'status_projection_version', 'non_self_referential_v3_status_classes', ...
        'propagation_success', cfg.propagation_success, ...
        'propagation_completed_requested_distance', ...
            cfg.propagation_completed_requested_distance, ...
        'physics_success', cfg.physics_success, ...
        'postprocess_phase_ok', cfg.postprocess_phase_ok, ...
        'postprocess_success', cfg.postprocess_success, ...
        'terminal_propagated_state_success', ...
            logical(struct_utils.opt_struct_field( ...
                terminal_propagated_state, 'ok', cfg.propagation_success)), ...
        'terminal_propagated_state_failure_class', char(string( ...
            struct_utils.opt_struct_field( ...
                terminal_propagated_state, 'failure_class', 'none'))), ...
        'terminal_propagated_state_failure_tags', {struct_utils.opt_struct_field( ...
            terminal_propagated_state, 'failure_tags', {})}, ...
        'status_failure_categories', status_failure_categories, ...
        'postprop_finalization_success', cfg.run_end_state.finalization.ok, ...
        'postprop_finalization_scaffold_success', ...
            cfg.run_end_state.finalization.scaffold_ok, ...
        'section6a_requested_outputs_complete', ...
            cfg.run_end_state.postprocess.requested_outputs_complete, ...
        'section6a_requested_outputs_skipped_reason', ...
            cfg.run_end_state.postprocess.requested_outputs_skipped_reason, ...
        'section6a_new_output_io_failure_count', ...
            cfg.run_end_state.postprocess.new_output_io_failure_count, ...
        'section6a_family_failure_count', ...
            cfg.run_end_state.postprocess.family_failure_count, ...
        'section6a_family_skip_count', ...
            cfg.run_end_state.postprocess.family_skip_count, ...
        'section6a_family_blocking_skip_count', ...
            cfg.run_end_state.postprocess.family_blocking_skip_count, ...
        'section6a_family_ledger', cfg.run_end_state.postprocess.family_ledger, ...
        'postprop_finalization_error_id', ...
            cfg.run_end_state.finalization.error_id, ...
        'postprop_finalization_error_message', ...
            cfg.run_end_state.finalization.error_message, ...
        'final_a_s_state_finite', cfg.final_a_s_state_finite, ...
        'final_a_f_state_finite', cfg.final_a_f_state_finite, ...
        'final_rho_state_finite', cfg.final_rho_state_finite, ...
        'final_rho_state_shape_ok', cfg.final_rho_state_shape_ok, ...
        'terminal_store_matches_accepted_state', ...
            cfg.terminal_store_contract.matches_accepted_state, ...
        'terminal_store_contract_reason', ...
            cfg.terminal_store_contract.reason, ...
        'intermediate_artifact_save_success_pre_status', ...
            cfg.intermediate_output_write_success_for_status, ...
        'final_output_write_success_pre_status', ...
            cfg.final_output_write_success_for_status, ...
        'reporting_success_pre_status', ...
            cfg.reporting_success_for_status, ...
        'completed_with_all_requested_outputs_pre_status', ...
            cfg.completed_with_all_requested_outputs_for_status, ...
        'intermediate_restart_stream_success_pre_status', ...
            cfg.run_end_state.intermediate.restart.ok, ...
        'intermediate_snapshot_stream_success_pre_status', ...
            cfg.run_end_state.intermediate.snapshot.ok, ...
        'intermediate_fullsave_stream_success_pre_status', ...
            cfg.run_end_state.intermediate.fullsave.ok, ...
        'final_restart_save_success', cfg.final_restart_save_ok, ...
        'final_restart_complete_package_ok_pre_status', ...
            logical(struct_utils.opt_struct_field( ...
                cfg.run_end_state.final_outputs.restart, ...
                'complete_package_ok', cfg.final_restart_save_ok)), ...
        'end_snapshot_save_success', cfg.end_snapshot_save_ok, ...
        'final_full_save_success', cfg.final_full_save_ok);
end

function status_extra_fields = ...
        extend_status_extra_fields_with_latest_pointer_results_local( ...
        status_extra_fields, run_end_state, ...
        latest_successful_pointer_eligible, ...
        latest_fully_packaged_pointer_eligible, ...
        latest_propagation_complete_pointer_eligible, ...
        final_output_write_success, reporting_success, ...
        completed_with_all_requested_outputs, attempt_reason)
    status_extra_fields.attempt_reason = attempt_reason;
    status_extra_fields.latest_successful_pointer_eligible = ...
        latest_successful_pointer_eligible;
    status_extra_fields.latest_fully_packaged_pointer_eligible = ...
        latest_fully_packaged_pointer_eligible;
    status_extra_fields.latest_propagation_complete_pointer_eligible = ...
        latest_propagation_complete_pointer_eligible;
    status_extra_fields.latest_successful_pointer_write_success = ...
        run_end_state.final_outputs.latest_successful_pointer.ok;
    status_extra_fields.latest_successful_pointer_ok = ...
        run_end_state.final_outputs.latest_successful_pointer.ok;
    status_extra_fields.latest_fully_packaged_pointer_write_success = ...
        run_end_state.final_outputs.latest_fully_packaged_pointer.ok;
    status_extra_fields.latest_fully_packaged_pointer_ok = ...
        run_end_state.final_outputs.latest_fully_packaged_pointer.ok;
    status_extra_fields.latest_propagation_complete_pointer_write_success = ...
        run_end_state.final_outputs.latest_propagation_complete_pointer.ok;
    status_extra_fields.latest_propagation_complete_pointer_ok = ...
        run_end_state.final_outputs.latest_propagation_complete_pointer.ok;
    status_extra_fields.latest_pointer_write_success = ...
        latest_pointer_outputs_ok_local(run_end_state.final_outputs);
    status_extra_fields.latest_pointer_ok = ...
        latest_pointer_outputs_ok_local(run_end_state.final_outputs);
    status_extra_fields.final_output_write_success_post_latest_pointers = ...
        final_output_write_success;
    status_extra_fields.reporting_success_post_latest_pointers = ...
        reporting_success;
    status_extra_fields.completed_with_all_requested_outputs_post_latest_pointers = ...
        completed_with_all_requested_outputs;
end

function artifact_status = build_artifact_status_tree_local(run_end_state)
    artifact_status = struct( ...
        'intermediate', run_end_state.intermediate, ...
        'final', struct( ...
            'finalization', run_end_state.finalization, ...
            'postprocess', run_end_state.postprocess, ...
            'restart', run_end_state.final_outputs.restart, ...
            'snapshot', run_end_state.final_outputs.snapshot, ...
            'fullsave', run_end_state.final_outputs.fullsave, ...
            'latest_successful_pointer', ...
                run_end_state.final_outputs.latest_successful_pointer, ...
            'latest_fully_packaged_pointer', ...
                run_end_state.final_outputs.latest_fully_packaged_pointer, ...
            'latest_propagation_complete_pointer', ...
                run_end_state.final_outputs.latest_propagation_complete_pointer, ...
            'run_status', run_end_state.final_outputs.run_status, ...
            'current_pointer', struct_utils.opt_struct_field( ...
                run_end_state.final_outputs, 'current_pointer', struct())));
end

function tf = intermediate_outputs_ok_local(intermediate_state)
    tf = intermediate_state.restart.ok && ...
        intermediate_state.snapshot.ok && ...
        intermediate_state.fullsave.ok;
end

function tf = final_core_outputs_ok_local(final_outputs)
    restart_complete_ok = logical(struct_utils.opt_struct_field( ...
        final_outputs.restart, 'complete_package_ok', final_outputs.restart.ok));
    tf = restart_complete_ok && ...
        final_outputs.snapshot.ok && ...
        final_outputs.fullsave.ok;
end

function tf = final_outputs_success_without_full_package_local(final_outputs)
    tf = final_outputs.restart.ok && ...
        final_outputs.snapshot.ok && ...
        final_outputs.fullsave.ok && ...
        struct_utils.opt_struct_field(final_outputs, 'current_pointer', ...
            build_artifact_status_record_local(false, false, true, ...
                'not_requested', '', '', 'skipped_not_requested')).ok && ...
        final_outputs.run_status.ok;
end

function tf = postprocess_has_any_ok_family_local(postprocess_state)
    tf = false;
    if ~isstruct(postprocess_state) || ...
            ~logical(struct_utils.opt_struct_field(postprocess_state, 'requested', false))
        return;
    end
    family_ledger = struct_utils.opt_struct_field( ...
        postprocess_state, 'family_ledger', struct());
    if ~isstruct(family_ledger)
        return;
    end
    family_names = fieldnames(family_ledger);
    for idx = 1:numel(family_names)
        family_state = family_ledger.(family_names{idx});
        if isstruct(family_state) && logical(struct_utils.opt_struct_field( ...
                family_state, 'ok', false))
            tf = true;
            return;
        end
    end
end

function tf = final_outputs_ok_for_status_local(final_outputs)
    tf = final_core_outputs_ok_local(final_outputs);
end

function tf = latest_pointer_outputs_ok_local(final_outputs)
    default_pointer = build_artifact_status_record_local( ...
        false, false, true, 'not_requested', '', '', 'skipped_not_requested');
    tf = struct_utils.opt_struct_field( ...
        final_outputs, 'latest_successful_pointer', default_pointer).ok && ...
        struct_utils.opt_struct_field( ...
        final_outputs, 'latest_fully_packaged_pointer', default_pointer).ok && ...
        struct_utils.opt_struct_field( ...
        final_outputs, 'latest_propagation_complete_pointer', default_pointer).ok;
end

function tf = final_outputs_ok_after_status_local(final_outputs)
    tf = final_outputs_ok_for_status_local(final_outputs) && ...
        latest_pointer_outputs_ok_local(final_outputs) && ...
        struct_utils.opt_struct_field(final_outputs, 'current_pointer', ...
            build_artifact_status_record_local(false, false, true, ...
                'not_requested', '', '', 'skipped_not_requested')).ok && ...
        final_outputs.run_status.ok;
end

function terminal_state = resolve_terminal_propagated_state_local(cfg, run_end_state)
    terminal_state = struct_utils.opt_struct_field( ...
        run_end_state, 'terminal_propagated_state', struct());
    if isstruct(terminal_state) && isscalar(terminal_state) && ...
            isfield(terminal_state, 'ok')
        return;
    end
    final_rho_state_shape_ok = logical(struct_utils.opt_struct_field( ...
        cfg, 'final_rho_state_shape_ok', true));
    terminal_ok = logical(cfg.final_a_s_state_finite) && ...
        logical(cfg.final_a_f_state_finite) && ...
        logical(cfg.final_rho_state_finite) && final_rho_state_shape_ok;
    failure_tags = {};
    if ~logical(cfg.final_a_s_state_finite)
        failure_tags{end + 1} = 'final_a_s_missing_or_nonfinite';
    end
    if ~logical(cfg.final_a_f_state_finite)
        failure_tags{end + 1} = 'final_a_f_missing_or_nonfinite';
    end
    if ~logical(cfg.final_rho_state_finite)
        failure_tags{end + 1} = 'final_rho_missing_or_nonfinite';
    end
    if ~final_rho_state_shape_ok
        failure_tags{end + 1} = 'final_rho_shape_mismatch';
    end
    if terminal_ok
        failure_class = 'none';
        severity = 'none';
    else
        failure_class = 'bad_propagated_state';
        severity = 'fatal';
    end
    terminal_state = struct( ...
        'ok', terminal_ok, ...
        'success', terminal_ok, ...
        'failure_class', failure_class, ...
        'severity', severity, ...
        'a_s_ok', logical(cfg.final_a_s_state_finite), ...
        'a_f_ok', logical(cfg.final_a_f_state_finite), ...
        'rho_ok', logical(cfg.final_rho_state_finite) && ...
            final_rho_state_shape_ok, ...
        'rho_finite_ok', logical(cfg.final_rho_state_finite), ...
        'rho_shape_ok', final_rho_state_shape_ok, ...
        'failure_tags', {failure_tags});
end

function pointer_status = build_pending_pointer_status_local(requested, pending_reason)
    if ~logical(requested)
        pending_reason = 'not_requested';
        pending_result = 'skipped_not_requested';
    else
        pending_result = 'pending_post_status_contract';
    end
    pointer_status = build_artifact_status_record_local( ...
        logical(requested), false, true, pending_reason, '', '', ...
        pending_result);
end

function terminal_store_contract = resolve_terminal_store_contract_local(run_end_state)
    terminal_store_contract = struct( ...
        'matches_accepted_state', true, ...
        'reason', '');
    raw_contract = struct_utils.opt_struct_field( ...
        run_end_state, 'terminal_store_contract', struct());
    if isstruct(raw_contract) && isscalar(raw_contract)
        terminal_store_contract.matches_accepted_state = logical( ...
            struct_utils.opt_struct_field( ...
                raw_contract, 'matches_accepted_state', true));
        terminal_store_contract.reason = char(string( ...
            struct_utils.opt_struct_field(raw_contract, 'reason', '')));
    end
end

function skipped_reason = resolve_terminal_store_skipped_reason_local( ...
        terminal_store_contract)
    skipped_reason = char(string(struct_utils.opt_struct_field( ...
        terminal_store_contract, 'reason', '')));
    if isempty(skipped_reason)
        skipped_reason = 'terminal_store_mismatch';
    end
end

function tf = any_restart_due_before_run_end_local( ...
        completed_z_steps, num_zsteps, checkpoint_stride_steps, ...
        save_final_restart_checkpoint_flag)
    checkpoint_stride_steps = normalize_positive_stride_local( ...
        checkpoint_stride_steps, 'checkpoint_stride_steps');
    due_step_count = floor(double(completed_z_steps) / checkpoint_stride_steps);
    if (double(completed_z_steps) == double(num_zsteps)) && ...
            logical(save_final_restart_checkpoint_flag) && ...
            (mod(double(num_zsteps), checkpoint_stride_steps) == 0)
        due_step_count = max(due_step_count - 1, 0);
    end
    tf = (due_step_count > 0);
end

function tf = any_snapshot_due_before_run_end_local( ...
        completed_z_steps, num_zsteps, snapshot_stride_steps)
    snapshot_stride_steps = normalize_positive_stride_local( ...
        snapshot_stride_steps, 'a_s_rho_snapshot_checkpoint_stride_steps');
    tf = (floor(double(completed_z_steps) / snapshot_stride_steps) > 0) || ...
        (double(completed_z_steps) == double(num_zsteps));
end

function tf = any_fullsave_due_before_run_end_local( ...
        completed_z_steps, num_zsteps, diagnostic_store_stride_steps, ...
        checkpoint_stride_steps)
    diagnostic_store_stride_steps = normalize_positive_stride_local( ...
        diagnostic_store_stride_steps, 'diagnostic_store_stride_steps');
    checkpoint_stride_steps = normalize_positive_stride_local( ...
        checkpoint_stride_steps, 'checkpoint_stride_steps');
    if double(completed_z_steps) <= 0
        tf = false;
        return;
    end
    first_store_step = Inf;
    if double(completed_z_steps) == double(num_zsteps)
        first_store_step = min(diagnostic_store_stride_steps, double(num_zsteps));
    elseif double(completed_z_steps) >= diagnostic_store_stride_steps
        first_store_step = diagnostic_store_stride_steps;
    end
    if ~isfinite(first_store_step)
        tf = false;
        return;
    end
    first_due_checkpoint_step = checkpoint_stride_steps * ...
        ceil(first_store_step / checkpoint_stride_steps);
    tf = (first_due_checkpoint_step <= double(completed_z_steps));
end

function stride_value = normalize_positive_stride_local(raw_stride_value, stride_name)
    stride_value = double(raw_stride_value);
    if ~isscalar(stride_value) || ~isfinite(stride_value) || ...
            ~isreal(stride_value) || (stride_value <= 0)
        error('CerUPP:InvalidSection6CStride', ...
            '%s must be a finite real scalar > 0 before Section 6C status collapse.', ...
            stride_name);
    end
end

function status_record = build_artifact_status_record_local( ...
        requested, attempted, ok, skipped_reason, error_id, ...
        error_message, result)
    status_record = struct( ...
        'requested', requested, ...
        'attempted', attempted, ...
        'ok', ok, ...
        'result', result, ...
        'skipped_reason', skipped_reason, ...
        'error_id', error_id, ...
        'error_message', error_message);
end
